// *********************************************************************************
// 1. 程式描述：系統管理–專案共用
// 2. 撰寫人員：Generated by WITSETER (by QFLin)
// *********************************************************************************
using System;
using System.Data;

namespace WIT.Template.Project
{
	/// <summary>
	/// 系統管理–專案共用
	/// </summary>
	public class i01Project
	{
		// =========================================================================
		/// <summary>
		/// 函式描述：取出專案資料庫系統編號
		/// </summary>
		/// <param name="as_nokind">要取得系統編號的種類</param>
		/// <param name="as_startswith">系統編號開始規格碼</param>
		/// <returns>系統編號(找資料庫最大編碼再加上 1)</returns>
		static public string uf_Get_SystemNo(string as_nokind, string as_startswith)
		{
			// ##### 宣告變數 #####
			string		ls_sql = "";
			string		ls_no, ls_maxno = null;
			int			li_len = 0, li_flen = 0;	// li_len：流水號的長度，li_flen：編號規格碼的長度
			string[]	lsa_startswith;

			// 判斷傳入參數是否正確
			if (as_nokind == null)
				as_nokind = "";
				
			if (as_startswith == null)
				as_startswith = "";
				
			// 分解 as_startswith 到陣列中
			lsa_startswith = as_startswith.Split(',');
			
			// 判斷是哪個編號，設定取出最大編號的方式 -------------- ☆ 1
			switch (as_nokind.ToLower())
			{
                     
                                      //●EntityAddHere!

                 //註解：
                 case "hmc101.hmc101_id":

                 	li_flen = as_startswith.Length;
                 	li_len = 6;
                 	ls_sql = "SELECT CAST(IsNull(Max(Cast(Right(hmc101_id,6) as int)), '0') as varchar(6)) FROM hmc101 ";
                 	
                 	break;

                     			    
			     //其它就直接關掉
				default:
					break;
					
			}

			// 實際取出最大編號的資料 ------------------------------ ☆ 2
			DbMethods.uf_ExecSQL(ls_sql, ref ls_maxno);

			// 判斷是否有找到符合的資料
			ls_maxno = ls_maxno.Trim();

			// 判斷是否有最大的編號，沒有則從 1 開始 --------------- ☆ 3
			if (ls_maxno == null || ls_maxno == "")				// 表格中沒有資料
				ls_no = as_startswith + Convert.ToString(1).PadLeft(li_len, '0');
			else
				ls_no = as_startswith + Convert.ToString(Convert.ToInt64(ls_maxno) + 1).PadLeft(li_len, '0');

			return ls_no;
		}
	}
}
