// *********************************************************************************
// 1. 程式描述：
// 2. 撰寫人員：Generated by WITSETER (by QFLin)
// *********************************************************************************
using System;
using System.Data;
using System.Configuration;
using System.Collections;
using System.Web;
using System.Web.Security;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Web.UI.WebControls.WebParts;
using System.Web.UI.HtmlControls;
using WIT.Template.Project;

public partial class sys_h_h02_p_h0201_02 : p_hrBase
{
	#region ☆ Declare Variables -------------------------------------- 撰寫人員：WITSETER (QFLin)

	/// <summary>變數描述：資料元件</summary>
	protected ndb_hmh201a indb_hmh201a = new ndb_hmh201a();

	#endregion

	// =========================================================================
	/// <summary>
	/// 事件描述：網頁開啟
	/// </summary>
	
	protected void Page_Load(object sender, EventArgs e)
    {
		// 初始化
		this.uf_InitializeQuery(dwQ, this.indb_hmh201a, bt_Query);
		this.uf_InitializeComponent(null, dgG, this.indb_hmh201a, null);
        this.dgG_Sort = "hmh201a_udt desc";

        // 註冊執行事件
        this.ue_PageLoad_AfterQueryRetrieve += new EventHandler(this.PageLoad_AfterQueryRetrieve);

	}

    // =========================================================================
    /// <summary>
    /// 事件描述：網頁開啟取出 Query 資料後處理事件
    /// </summary>
    private void PageLoad_AfterQueryRetrieve(object sender, System.EventArgs e)
    {
        // 如果是第一次執行此網頁
        if (!this.IsPostBack)
        {
            // 驅動查詢事件
            this.ibt_Query_Click(sender, EventArgs.Empty);
        }
    }

    public string uf_cut(object ao_string)
    {
        string ls_return = "";
        int li_count = 0;
        if (ao_string != null)
        {
            for (int li_row = 0; li_row < ao_string.ToString().Length; li_row++)
            {
                if (li_count > 25)
                {
                    ls_return += ao_string.ToString().Substring(li_row, 1) + "<br />";
                    li_count = 0;
                }
                else
                {
                    ls_return += ao_string.ToString().Substring(li_row, 1);
                    li_count++;
                }
            }
        }
        return ls_return;
    }

    public string uf_cutNum(object ao_string)
    {
        string ls_return = "";
        int li_countAll = 0;
        string[] lsa_num;

        if (ao_string != null)
        {
            lsa_num = ao_string.ToString().Split(';');

            for (int li_count = 0; li_count < lsa_num.Length; li_count++)
            {
                if (lsa_num[li_count] != "")
                    ls_return += lsa_num[li_count] + ";<br />";
            }
        }
        return ls_return;
    }

	// =========================================================================
	/// <summary>
	/// 事件描述：dgG 選擇某筆資料所要做的處理
	/// </summary>
	protected override void idgG_SelectedIndexChanged(object sender, EventArgs e)
    {
		this.uf_AddJavaScript("uf_LinkFrame('p_h0201_02.aspx', '02Frame', '" + dgG.DataKeys[dgG.SelectedIndex].ToString() + "')");
	}
	

    // =========================================================================
    /// <summary>
    /// 函式描述：資料控制項容器控制項組合出查詢語法之後針對特殊或不能處理的子控制項再修改組合出的查詢語法（一個控制項處理一次）（覆蓋上層）
    /// </summary>
    /// <param name="acto_Child">資料控制項容器上的子控制項</param>
    /// <param name="as_ColType">子控制項對應欄位的型態種類–清空時(空字串)；字串等於(S)；字串相似(SL)；日期時間(DT)；日期(D)；時間(T)；數值(N)</param>
    /// <param name="as_Value">子控制項對應欄位的值(已去空白)–傳入的值已處理不安全內容，如有變更需自行確認其安全性</param>
    /// <param name="a_Action">處理種類–清空(New)；查詢(Set)</param>
    /// <param name="as_AddSQL">清空(New)為空字串；查詢(Set)則傳入之前組合出的查詢語法(尚未加入此控制項語法)</param>
    /// <param name="ab_IsAdd">是否加入此控制項語法或參數–是(true)；否(false)</param>
    /// <param name="a_Kind">資料查詢種類–語法(AddSQL)；參數(AddArg)</param>
    /// <returns>成功(true)；失敗(false)</returns>
    protected override bool uf_DwQ_SQLAfter(Control acto_Child, ref string as_ColType, ref string as_Value, DwActions a_Action, ref string as_AddSQL, ref bool ab_IsAdd, DwQKinds a_Kind)
    {
   
   
           return true;
    }	
	
}
