// *********************************************************************************
// 1. 程式描述：
// 2. 撰寫人員：Generated by WITSETER (by QFLin)
// *********************************************************************************
using System;
using System.Data;
using System.Configuration;
using System.Collections;
using System.Web;
using System.Web.Security;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Web.UI.WebControls.WebParts;
using System.Web.UI.HtmlControls;
using WIT.Template.Project;

public partial class sys_h_h02_p_h0201_01 : p_hrBase
{
	#region ☆ Declare Variables -------------------------------------- 撰寫人員：WITSETER (by QFLin)

	/// <summary>變數描述：人員類別資料元件</summary>
	protected ndb_hmh201a indb_hmh201a = new ndb_hmh201a();

	#endregion

	// =========================================================================
	/// <summary>
	/// 事件描述：網頁開啟
	/// </summary>
	protected void Page_Load(object sender, EventArgs e)
    {
		// 如果是第一次執行此網頁
		if (!this.IsPostBack)
		{
            // 接收傳入值
            if (this.Request.QueryString["args"] != null)
            {
                this.StoredKey = Session["Query"].ToString().Replace("|", "\r\n");
                dwF_hmh201a_mlist.Text = this.StoredKey;
                this.uf_AddJavaScript("uf_SelectFrame(5);");
            }
		}
	}

    protected void bt_list_Click(object sender, EventArgs e)
    {
        this.uf_AddJavaScript("uf_OpenWindow('p_h0201_03.aspx?ReturnFormID=" + this.uf_GetFormID() + "&ReturnObjectID=" + dwF_hmh201a_mlist.ClientID + "&ObjectValue=" + dwF_hmh201a_mlist.Text.Replace("\r\n", ";") + "', '', 640, 450, 'no', 'no')");
        
    }

    protected string uf_TranNum(string as_num)
    {
        string ls_return;
        ls_return = as_num.Replace(',', ';');
        ls_return = ls_return.Replace('|', ';');
        ls_return = ls_return.Replace("\r\n", ";");
        return ls_return;
    }

    protected void bt_Conf_Click(object sender, EventArgs e)
    {
        if (dwF_hmh201a_stitle.Text.Trim() == "")
        {
            this.uf_Msg("請輸入賀卡標題！");
            return;
        }

        if (dwF_hmh201a_scontent.Text.Trim() == "" )
        {
            this.uf_Msg("請輸入賀卡內容！");
            return;
        }

        if (dwF_hmh201a_mlist.Text.Trim() == "")
        {
            this.uf_Msg("請輸入郵寄名單！");
            return;
        }

        string ls_list = dwF_hmh201a_mlist.Text.Trim() , ls_mail = "";

        if (ls_list != "")
        {
            ls_mail = uf_TranNum(ls_list);
            if (ls_list.Substring(ls_list.Length - 1) != ";")
                ls_mail += ";";
        }

        string[] lsa_mail;
        string PICUrl = "", STitle = "", SContent = "" , MailBody = "",ls_picurl = "";
        lsa_mail = ls_mail.Split(';');

        PICUrl = dwF_hmh201a_picurl_hf.Value;
        DbMethods.uf_ExecSQL(" select hmh200_picurl From hmh200 Where hmh200_cmid = '" + PICUrl + "' ", ref ls_picurl);
        STitle = dwF_hmh201a_stitle.Text.Trim();
        //string SName = "王先生";
        SContent = dwF_hmh201a_scontent.Text;

        for (int li_count = 0; li_count < lsa_mail.Length; li_count++)
        {
            if (lsa_mail[li_count] != "")
            {
                string ls_to = "", ls_cname = "";

                if (lsa_mail[li_count].IndexOf("(") > -1) //志工清單
                {
                    ls_to = lsa_mail[li_count].Substring(lsa_mail[li_count].IndexOf("(") + 1, lsa_mail[li_count].IndexOf(")") - lsa_mail[li_count].IndexOf("(") - 1);
                    ls_cname = lsa_mail[li_count].Substring(0, lsa_mail[li_count].IndexOf("("));
                }
                else
                {
                    ls_to = lsa_mail[li_count];
                    ls_cname = "博物館之友";
                }

                try
                {

                    //string MailList = "QFLin@edinet.com.tw";

                    MailBody = "<html>\n <head>		"
                                        + "		<STYLE type=\"text/css\">" + "\r\n"
                                        + "          Bt_Card {  "
                                         + "                	border:0;"
                                         + "           }"
                                        + "		</STYLE>" + "\r\n"
                                        + "</head><body>\n"
                                        + "  親愛的" + ls_cname + "：<BR><BR>"
                                        + "  <pre>" + SContent + "</pre><BR>"
                                        + "<IMG class=\"Bt_Card\" src=\"" + ls_picurl + "\"></IMG>"
                                        + "</body>\n</html>\n";

                    Email.uf_SendMail(ls_to, STitle, MailBody);
					

                }
                catch
                {
                    this.uf_Msg("寄送賀卡失敗！");
					return;
                }
            }
        }

        DataRowView ldrv_Row;
        indb_hmh201a.uf_InsertRow(out ldrv_Row);
        string ls_cid = h02Project.uf_Get_SystemNo("hmh201a.hmh201a_cid","");
        ldrv_Row["hmh201a_cid"] = ls_cid;
        ldrv_Row["hmh201a_picurl"] = ls_picurl;
        ldrv_Row["hmh201a_stitle"] = STitle;
        ldrv_Row["hmh201a_scontent"] = SContent;
        ldrv_Row["hmh201a_mlist"] = ls_mail;
        ldrv_Row["hmh201a_aid"] = LoginUser.ID;
        ldrv_Row["hmh201a_adt"] = DbMethods.uf_GetDateTime();
        ldrv_Row["hmh201a_uid"] = LoginUser.ID;
        ldrv_Row["hmh201a_udt"] = DbMethods.uf_GetDateTime();
        ldrv_Row.EndEdit();


        // 儲存資料
        if (indb_hmh201a.uf_Update() != 1)
        {
            this.uf_Msg(indb_hmh201a.ErrorMsg);
            indb_hmh201a.dv_View.Table.RejectChanges();
        }
        else
        {
            this.uf_Msg("寄送賀卡完成！");
        }

    }
    protected void bt_choose_Click(object sender, EventArgs e)
    {
        this.uf_AddJavaScript("uf_OpenWindow('p_h0201_04.aspx', '', 800, 600, 'yes', 'no')");
    }

    // =========================================================================
    // 事件
    // =========================================================================
    /// <summary>
    /// 事件描述：Html 送出前所要做的動作
    /// </summary>
    protected void Page_PreRender(object sender, System.EventArgs e)
    {
        dwF_hmh201a_picurl.Text = dwF_hmh201a_picurl_hf.Value;
    }
}
