// *********************************************************************************
// 1. 程式描述：系統管理–專案共用
// 2. 撰寫人員：Generated by WITSETER (by QFLin)
// *********************************************************************************
using System;
using System.Data;

namespace WIT.Template.Project
{
    /// <summary>
    /// 系統管理–專案共用
    /// </summary>
    public class f01Project
    {
        // =========================================================================
        /// <summary>
        /// 函式描述：取出專案資料庫系統編號
        /// </summary>
        /// <param name="as_nokind">要取得系統編號的種類</param>
        /// <param name="as_startswith">系統編號開始規格碼</param>
        /// <returns>系統編號(找資料庫最大編碼再加上 1)</returns>
        static public string uf_Get_SystemNo(string as_nokind, string as_startswith)
        {
            // ##### 宣告變數 #####
            string ls_sql = "";
            string ls_no, ls_maxno = null;
            int li_len = 0, li_flen = 0;	// li_len：流水號的長度，li_flen：編號規格碼的長度
            string[] lsa_startswith;

            // 判斷傳入參數是否正確
            if (as_nokind == null)
                as_nokind = "";

            if (as_startswith == null)
                as_startswith = "";

            // 分解 as_startswith 到陣列中
            lsa_startswith = as_startswith.Split(',');

            // 判斷是哪個編號，設定取出最大編號的方式 -------------- ☆ 1
            switch (as_nokind.ToLower())
            {

                                 //●EntityAddHere!

                 //註解：
                 case "hmf101b.hmf101b_certid":

                 	li_flen = as_startswith.Length;
                 	li_len = 5;
                 	ls_sql = "SELECT CAST(IsNull(Max(Cast(Right(hmf101b_certid,5) as int)), '0') as varchar(5)) FROM hmf101b ";
                 	
                 	break;


                //註解：
                case "hmf101a.hmf101a_certid":

                    li_flen = as_startswith.Length;
                    li_len = 5;
                    ls_sql = "SELECT CAST(IsNull(Max(Cast(Right(hmf101a_certid,5) as int)), '0') as varchar(5)) FROM hmf101a ";

                    break;


                //註解：
                case "hmf102.hmf102_trainid":

                    li_flen = as_startswith.Length;
                    li_len = 5;				// 流水號位數
                    ls_sql = "SELECT CAST(IsNull(Max(Cast(Right(hmf102_trainid,5) as int)), '0') as varchar(5)) FROM hmf102 ";

                    break;

                // ------------------------------------------------- ★ 勤務紀錄編號
                // "Slog" + 流水號(9位)
                case "hlf201.hlf201_lid":

                    // 得到規格碼的長度
                    li_flen = as_startswith.Length;

                    li_len = 9;			// 流水號 9 位

                    // 找出資料庫中最大的編號–且規格碼符合傳入的值
                    ls_sql = "SELECT IsNull(Max(SubString(hlf201_lid, " + Convert.ToString(li_flen + 1) + ", " + Convert.ToString(li_len) + ")), '0') as no " +
                                "FROM hlf201 " +
                                "WHERE SubString(hlf201_lid, 1, " + Convert.ToString(li_flen) + ") = '" + as_startswith + "' ";

                    break;

                //註解：
                case "hmf101.hmf101_courseid":

                    li_flen = as_startswith.Length;
                    li_len = 5;				// 流水號位數
                    ls_sql = "SELECT CAST(IsNull(Max(Cast(Right(hmf101_courseid,5) as int)), '0') as varchar(5)) FROM hmf101 ";

                    break;

                //其它就直接關掉
                default:
                    break;

            }

            // 實際取出最大編號的資料 ------------------------------ ☆ 2
            DbMethods.uf_ExecSQL(ls_sql, ref ls_maxno);

            // 判斷是否有最大的編號，沒有則從 1 開始 --------------- ☆ 3
            if (ls_maxno == null || ls_maxno == "")				// 表格中沒有資料
                ls_no = as_startswith + Convert.ToString(1).PadLeft(li_len, '0');
            else
                ls_no = as_startswith + Convert.ToString(Convert.ToInt64(ls_maxno) + 1).PadLeft(li_len, '0');

            return ls_no;
        }

        // =========================================================================
        /// <param name="ao_psid">課程代碼</param>
        /// <returns>課程名稱</returns>

        static public string uf_coursename(object ao_psid)
        {
            string li_count = "";
            if (ao_psid != null)
            {
                DbMethods.uf_ExecSQL("SELECT hmf101_name FROM hmf101 WHERE hmf101_courseid = '" + ao_psid.ToString().Trim() + "'", ref li_count);
            }
            return li_count;
        }


        // =========================================================================
        /// <param name="ao_psid">課程代碼</param>
        /// <returns>課程時數</returns>
        static public string uf_hourse(object ao_psid)
        {
            int li_count = 0;
            if (ao_psid != null)
            {
                DbMethods.uf_ExecSQL("SELECT hmf101_hourse FROM hmf101 WHERE hmf101_courseid = '" + ao_psid.ToString().Trim() + "'", ref li_count);
            }
            return li_count.ToString();
        }

        // =========================================================================
        /// <summary>
        /// 函式描述：計算修課人數班次
        /// </summary>
        /// <param name="ao_psid">排班表代碼</param>
        /// <returns>班次數量</returns>
        static public string uf_count1(object ao_psid)
        {
            int li_count = 0;
            if (ao_psid != null)
            {
                DbMethods.uf_ExecSQL("SELECT count(*) FROM hmf103 WHERE hmf103_trainid='" + ao_psid.ToString().Trim() + "'", ref li_count);
            }
            return li_count.ToString();
        }

        // =========================================================================
        /// <summary>
        /// 函式描述：計算修課人數班次
        /// </summary>
        /// <param name="ao_psid">排班表代碼</param>
        /// <returns>班次數量</returns>
        static public string uf_count2(object ao_psid)
        {
            int li_count = 0;
            if (ao_psid != null)
            {
                DbMethods.uf_ExecSQL("SELECT count(*) FROM hmf302 WHERE hmf302_trainid='" + ao_psid.ToString().Trim() + "' AND hmf302_score is not null", ref li_count);
            }
            return li_count.ToString();
        }

        // =========================================================================
        /// <summary>
        /// 函式描述：計算認證人數
        /// </summary>
        /// <param name="ao_certid">認證代碼</param>
        /// <returns>認證人數</returns>
        static public string uf_CertPCount(object ao_certid)
        {
            // ##### 宣告變數 #####
            string ls_datastring = "" , ls_certsql = "";
            DataSet lds_data;
            DataView dv_data;
            int li_count = 0 , li_return = 0 , li_get = 0;

            if (ao_certid != null && ao_certid.ToString() != "")
            {
                ls_datastring = @" Select distinct hmf302_vid
                                    From hmf302 Inner Join hmf102 ON hmf102_trainid = hmf302_trainid
                                    Inner Join hmf101b ON hmf102_courseid = hmf101b_courseid
                                    Where hmf302_passed = 'Y' ";

                ls_datastring += " And hmf101b_certid = '" + ao_certid.ToString() + "' ";

                // 利用 SQL 語法產生資料集
                DbMethods.uf_Retrieve_FromSQL(out lds_data, ls_datastring);
                dv_data = lds_data.Tables[0].DefaultView;

                if (dv_data.Count > 0)
                {
                    for (int li_row = 0; li_row < dv_data.Count; li_row++)
                    {                         
                        ls_certsql = "";
                        ls_certsql += " Select count(*) From hmf101b Where hmf101b_certid = '"+ ao_certid.ToString() +"' ";
                        ls_certsql += " AND hmf101b_courseid not in ";
                        ls_certsql += " ( Select distinct hmf102_courseid ";
                        ls_certsql += "     From hmf302 Inner Join hmf102 ON hmf102_trainid = hmf302_trainid ";
                        ls_certsql += "     Inner Join hmf101b ON hmf102_courseid = hmf101b_courseid ";
                        ls_certsql += "     Where hmf302_passed = 'Y'  ";
                        ls_certsql += "     AND hmf101b_certid = '"+ ao_certid.ToString() +"' ";
                        ls_certsql += "     AND hmf302_vid = '" + dv_data[li_row][0].ToString() + "' ) ";

                        DbMethods.uf_ExecSQL(ls_certsql, ref li_count);

                        if (li_count <= 0)
                        {
                            DbMethods.uf_ExecSQL("SELECT count(*) FROM hmf401 WHERE hmf401_certid = '" + ao_certid.ToString() + "' AND hmf401_vid = '" + dv_data[li_row][0].ToString() + "'", ref li_get);
                            if (li_get <= 0) li_return++;
                        }
                    }
                }

            }
            return li_return.ToString();
        }

        // =========================================================================
        /// <summary>
        /// 函式描述：計算認證人數
        /// </summary>
        /// <param name="ao_certid">認證代碼</param>
        /// <returns>志工代碼組成語法</returns>
        static public string uf_CertPeople(object ao_certid)
        {
            // ##### 宣告變數 #####
            string ls_datastring = "", ls_certsql = "";
            DataSet lds_data;
            DataView dv_data;
            int li_count = 0 , li_get = 0;
            string ls_return = "";

            if (ao_certid != null && ao_certid.ToString() != "")
            {
                ls_datastring = @" Select distinct hmf302_vid
                                    From hmf302 Inner Join hmf102 ON hmf102_trainid = hmf302_trainid
                                    Inner Join hmf101b ON hmf102_courseid = hmf101b_courseid
                                    Where hmf302_passed = 'Y' ";

                ls_datastring += " And hmf101b_certid = '" + ao_certid.ToString() + "' ";

                // 利用 SQL 語法產生資料集
                DbMethods.uf_Retrieve_FromSQL(out lds_data, ls_datastring);
                dv_data = lds_data.Tables[0].DefaultView;

                if (dv_data.Count > 0)
                {
                    for (int li_row = 0; li_row < dv_data.Count; li_row++)
                    {
                        ls_certsql = "";
                        ls_certsql += " Select count(*) From hmf101b Where hmf101b_certid = '" + ao_certid.ToString() + "' ";
                        ls_certsql += " AND hmf101b_courseid not in ";
                        ls_certsql += " ( Select distinct hmf102_courseid ";
                        ls_certsql += "     From hmf302 Inner Join hmf102 ON hmf102_trainid = hmf302_trainid ";
                        ls_certsql += "     Inner Join hmf101b ON hmf102_courseid = hmf101b_courseid ";
                        ls_certsql += "     Where hmf302_passed = 'Y'  ";
                        ls_certsql += "     AND hmf101b_certid = '" + ao_certid.ToString() + "' ";
                        ls_certsql += "     AND hmf302_vid = '" + dv_data[li_row][0].ToString() + "' ) ";

                        DbMethods.uf_ExecSQL(ls_certsql, ref li_count);

                        if (li_count <= 0)
                        {
                            DbMethods.uf_ExecSQL("SELECT count(*) FROM hmf401 WHERE hmf401_certid = '" + ao_certid.ToString() + "' AND hmf401_vid = '" + dv_data[li_row][0].ToString() + "'", ref li_get);
                            if (li_get <= 0)
                            {
                                if (ls_return != "") ls_return += " , ";
                                ls_return += "'" + dv_data[li_row][0].ToString() + "'";
                            }
                        }
                    }
                }

            }
            if (ls_return == "") ls_return = "'xxx'";
            return ls_return;
        }
    }
}