// *********************************************************************************
// 1. 程式描述：hle501資料元件–無傳入值
// 2. 撰寫人員：generated by WITSTER  0.2.2 beta (by QFLin)
// *********************************************************************************
using System;
using System.ComponentModel;
using System.Collections;
using System.Diagnostics;

/// <summary>
/// hle501資料元件–無傳入值
/// </summary>
public class ndb_hle501 : WIT.Template.Project.n_dbbase
{
	private System.Data.OleDb.OleDbCommand oleDbDeleteCommand;
	private System.Data.OleDb.OleDbCommand oleDbInsertCommand;
	private System.Data.OleDb.OleDbCommand oleDbSelectCommand;
	private System.Data.OleDb.OleDbCommand oleDbUpdateCommand;
	private System.Data.OleDb.OleDbDataAdapter da_SQL_current;
	
	public ndb_hle501(System.ComponentModel.IContainer container)
	{
		container.Add(this);
		InitializeComponent();
		// 將資料配接器設為 current
		da_SQL = da_SQL_current;
	}

	public ndb_hle501()
	{
		InitializeComponent();
		// 將資料配接器設為 current
		da_SQL = da_SQL_current;
	}

	#region Component Designer generated code
	
	/// <summary>
	/// 此為設計工具支援所必需的方法 - 請勿使用程式碼編輯器修改
	/// 這個方法的內容。
	/// </summary>
	private void InitializeComponent()
	{
		System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(ndb_hle501));
		this.da_SQL_current = new System.Data.OleDb.OleDbDataAdapter();
		this.oleDbDeleteCommand = new System.Data.OleDb.OleDbCommand();
		this.oleDbInsertCommand = new System.Data.OleDb.OleDbCommand();
		this.oleDbSelectCommand = new System.Data.OleDb.OleDbCommand();
		this.oleDbUpdateCommand = new System.Data.OleDb.OleDbCommand();
		((System.ComponentModel.ISupportInitialize)(this.ds_Data)).BeginInit();
		((System.ComponentModel.ISupportInitialize)(this.dv_View)).BeginInit();
		// 
		// da_SQL_current
		// 
		this.da_SQL_current.DeleteCommand = this.oleDbDeleteCommand;
		this.da_SQL_current.InsertCommand = this.oleDbInsertCommand;
		this.da_SQL_current.SelectCommand = this.oleDbSelectCommand;
		this.da_SQL_current.TableMappings.AddRange(new System.Data.Common.DataTableMapping[] {
            new System.Data.Common.DataTableMapping("Table", "hle501", new System.Data.Common.DataColumnMapping[] {
                        new System.Data.Common.DataColumnMapping("hle501_plid", "hle501_plid"),
                        new System.Data.Common.DataColumnMapping("hle501_vid", "hle501_vid"),
                        new System.Data.Common.DataColumnMapping("hle501_tid", "hle501_tid"),
                        new System.Data.Common.DataColumnMapping("hle501_syear", "hle501_syear"),
                        new System.Data.Common.DataColumnMapping("hle501_score1", "hle501_score1"),
                        new System.Data.Common.DataColumnMapping("hle501_score2", "hle501_score2"),
                        new System.Data.Common.DataColumnMapping("hle501_score3", "hle501_score3"),
                        new System.Data.Common.DataColumnMapping("hle501_score4", "hle501_score4"),
                        new System.Data.Common.DataColumnMapping("hle501_tscore1", "hle501_tscore1"),
                        new System.Data.Common.DataColumnMapping("hle501_tscore2", "hle501_tscore2"),
                        new System.Data.Common.DataColumnMapping("hle501_tscore3", "hle501_tscore3"),
                        new System.Data.Common.DataColumnMapping("hle501_tscore4", "hle501_tscore4"),
                        new System.Data.Common.DataColumnMapping("hle501_ps", "hle501_ps"),
                        new System.Data.Common.DataColumnMapping("hle501_aid", "hle501_aid"),
                        new System.Data.Common.DataColumnMapping("hle501_adt", "hle501_adt"),
                        new System.Data.Common.DataColumnMapping("hle501_uid", "hle501_uid"),
                        new System.Data.Common.DataColumnMapping("hle501_udt", "hle501_udt")})});
		this.da_SQL_current.UpdateCommand = this.oleDbUpdateCommand;
		// 
		// oleDbDeleteCommand
		// 
		this.oleDbDeleteCommand.CommandText = "DELETE FROM [hle501] WHERE (([hle501_plid] = ?))";
		this.oleDbDeleteCommand.Connection = this.cn_DB;
		this.oleDbDeleteCommand.Parameters.AddRange(new System.Data.OleDb.OleDbParameter[] {
            new System.Data.OleDb.OleDbParameter("Original_hle501_plid", System.Data.OleDb.OleDbType.VarWChar, 0, System.Data.ParameterDirection.Input, false, ((byte)(0)), ((byte)(0)), "hle501_plid", System.Data.DataRowVersion.Original, null)});
		// 
		// oleDbInsertCommand
		// 
		this.oleDbInsertCommand.CommandText = "INSERT INTO [hle501] ([hle501_plid], [hle501_vid], [hle501_tid], [hle501_syear], [hle501_score1], [hle501_score2], [hle501_score3], [hle501_score4], [hle501_tscore1], [hle501_tscore2], [hle501_tscore3], [hle501_tscore4], [hle501_ps], [hle501_aid], [hle501_adt], [hle501_uid], [hle501_udt]) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
		this.oleDbInsertCommand.Connection = this.cn_DB;
		this.oleDbInsertCommand.Parameters.AddRange(new System.Data.OleDb.OleDbParameter[] {
            new System.Data.OleDb.OleDbParameter("hle501_plid", System.Data.OleDb.OleDbType.VarWChar, 0, "hle501_plid"),
            new System.Data.OleDb.OleDbParameter("hle501_vid", System.Data.OleDb.OleDbType.VarWChar, 0, "hle501_vid"),
            new System.Data.OleDb.OleDbParameter("hle501_tid", System.Data.OleDb.OleDbType.VarWChar, 0, "hle501_tid"),
            new System.Data.OleDb.OleDbParameter("hle501_syear", System.Data.OleDb.OleDbType.WChar, 0, "hle501_syear"),
            new System.Data.OleDb.OleDbParameter("hle501_score1", System.Data.OleDb.OleDbType.SmallInt, 0, "hle501_score1"),
            new System.Data.OleDb.OleDbParameter("hle501_score2", System.Data.OleDb.OleDbType.SmallInt, 0, "hle501_score2"),
            new System.Data.OleDb.OleDbParameter("hle501_score3", System.Data.OleDb.OleDbType.SmallInt, 0, "hle501_score3"),
            new System.Data.OleDb.OleDbParameter("hle501_score4", System.Data.OleDb.OleDbType.SmallInt, 0, "hle501_score4"),
            new System.Data.OleDb.OleDbParameter("hle501_tscore1", System.Data.OleDb.OleDbType.SmallInt, 0, "hle501_tscore1"),
            new System.Data.OleDb.OleDbParameter("hle501_tscore2", System.Data.OleDb.OleDbType.SmallInt, 0, "hle501_tscore2"),
            new System.Data.OleDb.OleDbParameter("hle501_tscore3", System.Data.OleDb.OleDbType.SmallInt, 0, "hle501_tscore3"),
            new System.Data.OleDb.OleDbParameter("hle501_tscore4", System.Data.OleDb.OleDbType.SmallInt, 0, "hle501_tscore4"),
            new System.Data.OleDb.OleDbParameter("hle501_ps", System.Data.OleDb.OleDbType.VarWChar, 0, "hle501_ps"),
            new System.Data.OleDb.OleDbParameter("hle501_aid", System.Data.OleDb.OleDbType.VarWChar, 0, "hle501_aid"),
            new System.Data.OleDb.OleDbParameter("hle501_adt", System.Data.OleDb.OleDbType.DBTimeStamp, 0, "hle501_adt"),
            new System.Data.OleDb.OleDbParameter("hle501_uid", System.Data.OleDb.OleDbType.VarWChar, 0, "hle501_uid"),
            new System.Data.OleDb.OleDbParameter("hle501_udt", System.Data.OleDb.OleDbType.DBTimeStamp, 0, "hle501_udt")});
		// 
		// oleDbSelectCommand
		// 
		this.oleDbSelectCommand.CommandText = "SELECT * FROM [hle501] WHERE (1=1) ";
		this.oleDbSelectCommand.Connection = this.cn_DB;
		// 
		// oleDbUpdateCommand
		// 
		this.oleDbUpdateCommand.CommandText = "UPDATE [hle501] SET [hle501_plid] = ?, [hle501_vid] = ?, [hle501_tid] = ?, [hle501_syear] = ?, [hle501_score1] = ?, [hle501_score2] = ?, [hle501_score3] = ?, [hle501_score4] = ?, [hle501_tscore1] = ?, [hle501_tscore2] = ?, [hle501_tscore3] = ?, [hle501_tscore4] = ?, [hle501_ps] = ?, [hle501_aid] = ?, [hle501_adt] = ?, [hle501_uid] = ?, [hle501_udt] = ? WHERE (([hle501_plid] = ?))";
		this.oleDbUpdateCommand.Connection = this.cn_DB;
		this.oleDbUpdateCommand.Parameters.AddRange(new System.Data.OleDb.OleDbParameter[] {
            new System.Data.OleDb.OleDbParameter("hle501_plid", System.Data.OleDb.OleDbType.VarWChar, 0, "hle501_plid"),
            new System.Data.OleDb.OleDbParameter("hle501_vid", System.Data.OleDb.OleDbType.VarWChar, 0, "hle501_vid"),
            new System.Data.OleDb.OleDbParameter("hle501_tid", System.Data.OleDb.OleDbType.VarWChar, 0, "hle501_tid"),
            new System.Data.OleDb.OleDbParameter("hle501_syear", System.Data.OleDb.OleDbType.WChar, 0, "hle501_syear"),
            new System.Data.OleDb.OleDbParameter("hle501_score1", System.Data.OleDb.OleDbType.SmallInt, 0, "hle501_score1"),
            new System.Data.OleDb.OleDbParameter("hle501_score2", System.Data.OleDb.OleDbType.SmallInt, 0, "hle501_score2"),
            new System.Data.OleDb.OleDbParameter("hle501_score3", System.Data.OleDb.OleDbType.SmallInt, 0, "hle501_score3"),
            new System.Data.OleDb.OleDbParameter("hle501_score4", System.Data.OleDb.OleDbType.SmallInt, 0, "hle501_score4"),
            new System.Data.OleDb.OleDbParameter("hle501_tscore1", System.Data.OleDb.OleDbType.SmallInt, 0, "hle501_tscore1"),
            new System.Data.OleDb.OleDbParameter("hle501_tscore2", System.Data.OleDb.OleDbType.SmallInt, 0, "hle501_tscore2"),
            new System.Data.OleDb.OleDbParameter("hle501_tscore3", System.Data.OleDb.OleDbType.SmallInt, 0, "hle501_tscore3"),
            new System.Data.OleDb.OleDbParameter("hle501_tscore4", System.Data.OleDb.OleDbType.SmallInt, 0, "hle501_tscore4"),
            new System.Data.OleDb.OleDbParameter("hle501_ps", System.Data.OleDb.OleDbType.VarWChar, 0, "hle501_ps"),
            new System.Data.OleDb.OleDbParameter("hle501_aid", System.Data.OleDb.OleDbType.VarWChar, 0, "hle501_aid"),
            new System.Data.OleDb.OleDbParameter("hle501_adt", System.Data.OleDb.OleDbType.DBTimeStamp, 0, "hle501_adt"),
            new System.Data.OleDb.OleDbParameter("hle501_uid", System.Data.OleDb.OleDbType.VarWChar, 0, "hle501_uid"),
            new System.Data.OleDb.OleDbParameter("hle501_udt", System.Data.OleDb.OleDbType.DBTimeStamp, 0, "hle501_udt"),
            new System.Data.OleDb.OleDbParameter("Original_hle501_plid", System.Data.OleDb.OleDbType.VarWChar, 0, System.Data.ParameterDirection.Input, false, ((byte)(0)), ((byte)(0)), "hle501_plid", System.Data.DataRowVersion.Original, null)});
		((System.ComponentModel.ISupportInitialize)(this.ds_Data)).EndInit();
		((System.ComponentModel.ISupportInitialize)(this.dv_View)).EndInit();

	}
	#endregion

	// =========================================================================
	/// <summary>
	/// 函式描述：自訂初始化函式（覆蓋上層）
	/// </summary>
	protected override void uf_InitializeComponent()
	{
		// 先將 DataSet 宣告為指定的結構再初始化
		this.ds_Data = new d_hle501();
		this.uf_Initialize();
	}
}
