// *********************************************************************************
// 1. 程式描述：hmf101a資料元件–無傳入值
// 2. 撰寫人員：generated by WITSTER  0.2.2 beta (by QFLin)
// *********************************************************************************
using System;
using System.ComponentModel;
using System.Collections;
using System.Diagnostics;

/// <summary>
/// hmf101a資料元件–無傳入值
/// </summary>
public class ndb_hmf101a : WIT.Template.Project.n_dbbase
{
	private System.Data.OleDb.OleDbCommand oleDbDeleteCommand;
	private System.Data.OleDb.OleDbCommand oleDbInsertCommand;
	private System.Data.OleDb.OleDbCommand oleDbSelectCommand;
	private System.Data.OleDb.OleDbCommand oleDbUpdateCommand;
	private System.Data.OleDb.OleDbDataAdapter da_SQL_current;
	
	public ndb_hmf101a(System.ComponentModel.IContainer container)
	{
		container.Add(this);
		InitializeComponent();
		// 將資料配接器設為 current
		da_SQL = da_SQL_current;
	}

	public ndb_hmf101a()
	{
		InitializeComponent();
		// 將資料配接器設為 current
		da_SQL = da_SQL_current;
	}

	#region Component Designer generated code
	
	/// <summary>
	/// 此為設計工具支援所必需的方法 - 請勿使用程式碼編輯器修改
	/// 這個方法的內容。
	/// </summary>
	private void InitializeComponent()
	{
		this.da_SQL_current = new System.Data.OleDb.OleDbDataAdapter();
		this.oleDbDeleteCommand = new System.Data.OleDb.OleDbCommand();
		this.oleDbInsertCommand = new System.Data.OleDb.OleDbCommand();
		this.oleDbSelectCommand = new System.Data.OleDb.OleDbCommand();
		this.oleDbUpdateCommand = new System.Data.OleDb.OleDbCommand();
		
		((System.ComponentModel.ISupportInitialize)(this.ds_Data)).BeginInit();
		((System.ComponentModel.ISupportInitialize)(this.dv_View)).BeginInit();

		// 
		// 容器
		// 
		this.da_SQL_current.TableMappings.AddRange(new System.Data.Common.DataTableMapping[] {
			
                                           new System.Data.Common.DataTableMapping("Table", "hmf101a", new System.Data.Common.DataColumnMapping[] {
                                           new System.Data.Common.DataColumnMapping("hmf101a_certid", "hmf101a_certid"),
                                           new System.Data.Common.DataColumnMapping("hmf101a_name", "hmf101a_name"),
                                           new System.Data.Common.DataColumnMapping("hmf101a_stop", "hmf101a_stop"),
                                           new System.Data.Common.DataColumnMapping("hmf101a_ps", "hmf101a_ps"),
                                           new System.Data.Common.DataColumnMapping("hmf101a_aid", "hmf101a_aid"),
                                           new System.Data.Common.DataColumnMapping("hmf101a_adt", "hmf101a_adt"),
                                           new System.Data.Common.DataColumnMapping("hmf101a_uid", "hmf101a_uid"),
                                           new System.Data.Common.DataColumnMapping("hmf101a_udt", "hmf101a_udt")
                                           })
            });
                                           
		// 
		// 刪除命令
		// 
		this.da_SQL_current.DeleteCommand = this.oleDbDeleteCommand;
		this.oleDbDeleteCommand.CommandText = "DELETE FROM [hmf101a] WHERE (([hmf101a_certid] = ?)) ";
		this.oleDbDeleteCommand.Connection = this.cn_DB;
		this.oleDbDeleteCommand.Parameters.AddRange(new System.Data.OleDb.OleDbParameter[] {
		                                                           new System.Data.OleDb.OleDbParameter("Original_hmf101a_certid", System.Data.OleDb.OleDbType.VarChar, 0, System.Data.ParameterDirection.Input, false, ((byte)(20)), ((byte)(0)), "hmf101a_certid", System.Data.DataRowVersion.Original, null)
		});


		// 
		// 新增區
		// 
		this.da_SQL_current.InsertCommand = this.oleDbInsertCommand;
		this.oleDbInsertCommand.CommandText = "INSERT INTO [hmf101a] ([hmf101a_certid],[hmf101a_name],[hmf101a_stop],[hmf101a_ps],[hmf101a_aid],[hmf101a_adt],[hmf101a_uid],[hmf101a_udt]) VALUES (?,?,?,?,?,?,?,?)";
		this.oleDbInsertCommand.Connection = this.cn_DB;
		this.oleDbInsertCommand.Parameters.AddRange(new System.Data.OleDb.OleDbParameter[] {
		                                                           new System.Data.OleDb.OleDbParameter("hmf101a_certid", System.Data.OleDb.OleDbType.VarChar, 0, "hmf101a_certid"),
                                                     new System.Data.OleDb.OleDbParameter("hmf101a_name", System.Data.OleDb.OleDbType.VarChar, 0, "hmf101a_name"),
                                                     new System.Data.OleDb.OleDbParameter("hmf101a_stop", System.Data.OleDb.OleDbType.Char, 0, "hmf101a_stop"),
                                                     new System.Data.OleDb.OleDbParameter("hmf101a_ps", System.Data.OleDb.OleDbType.LongVarChar, 0, "hmf101a_ps"),
                                                     new System.Data.OleDb.OleDbParameter("hmf101a_aid", System.Data.OleDb.OleDbType.VarChar, 0, "hmf101a_aid"),
                                                     new System.Data.OleDb.OleDbParameter("hmf101a_adt", System.Data.OleDb.OleDbType.DBTimeStamp, 0, "hmf101a_adt"),
                                                     new System.Data.OleDb.OleDbParameter("hmf101a_uid", System.Data.OleDb.OleDbType.VarChar, 0, "hmf101a_uid"),
                                                     new System.Data.OleDb.OleDbParameter("hmf101a_udt", System.Data.OleDb.OleDbType.DBTimeStamp, 0, "hmf101a_udt")
		});


		// 
		// 查詢區
		// 
		this.da_SQL_current.SelectCommand = this.oleDbSelectCommand;				this.oleDbSelectCommand.CommandText = "SELECT * FROM [hmf101a] WHERE (1=1) ";		this.oleDbSelectCommand.Connection = this.cn_DB;

		// 
		// 更新區
		// 
		this.da_SQL_current.UpdateCommand = this.oleDbUpdateCommand;
		this.oleDbUpdateCommand.CommandText = "UPDATE [hmf101a] SET  [hmf101a_certid] = ?, [hmf101a_name] = ?, [hmf101a_stop] = ?, [hmf101a_ps] = ?, [hmf101a_aid] = ?, [hmf101a_adt] = ?, [hmf101a_uid] = ?, [hmf101a_udt] = ?  WHERE (([hmf101a_certid] = ?))";
		this.oleDbUpdateCommand.Connection = this.cn_DB;
		this.oleDbUpdateCommand.Parameters.AddRange(new System.Data.OleDb.OleDbParameter[] {
		                                                           new System.Data.OleDb.OleDbParameter("hmf101a_certid", System.Data.OleDb.OleDbType.VarChar, 0, "hmf101a_certid"),
                                                     new System.Data.OleDb.OleDbParameter("hmf101a_name", System.Data.OleDb.OleDbType.VarChar, 0, "hmf101a_name"),
                                                     new System.Data.OleDb.OleDbParameter("hmf101a_stop", System.Data.OleDb.OleDbType.Char, 0, "hmf101a_stop"),
                                                     new System.Data.OleDb.OleDbParameter("hmf101a_ps", System.Data.OleDb.OleDbType.LongVarChar, 0, "hmf101a_ps"),
                                                     new System.Data.OleDb.OleDbParameter("hmf101a_aid", System.Data.OleDb.OleDbType.VarChar, 0, "hmf101a_aid"),
                                                     new System.Data.OleDb.OleDbParameter("hmf101a_adt", System.Data.OleDb.OleDbType.DBTimeStamp, 0, "hmf101a_adt"),
                                                     new System.Data.OleDb.OleDbParameter("hmf101a_uid", System.Data.OleDb.OleDbType.VarChar, 0, "hmf101a_uid"),
                                                     new System.Data.OleDb.OleDbParameter("hmf101a_udt", System.Data.OleDb.OleDbType.DBTimeStamp, 0, "hmf101a_udt"),
                                                     new System.Data.OleDb.OleDbParameter("Original_hmf101a_certid", System.Data.OleDb.OleDbType.VarChar, 0, System.Data.ParameterDirection.Input, false, ((byte)(20)), ((byte)(0)), "hmf101a_certid", System.Data.DataRowVersion.Original, null)                                                });

		((System.ComponentModel.ISupportInitialize)(this.ds_Data)).EndInit();
		((System.ComponentModel.ISupportInitialize)(this.dv_View)).EndInit();


	}
	#endregion

	// =========================================================================
	/// <summary>
	/// 函式描述：自訂初始化函式（覆蓋上層）
	/// </summary>
	protected override void uf_InitializeComponent()
	{
		// 先將 DataSet 宣告為指定的結構再初始化
		this.ds_Data = new d_hmf101a();
		this.uf_Initialize();
	}
}
