// *********************************************************************************
// 1. 程式描述：hme101c資料元件–無傳入值
// 2. 撰寫人員：generated by WITSTER  0.2.2 beta (by QFLin)
// *********************************************************************************
using System;
using System.ComponentModel;
using System.Collections;
using System.Diagnostics;

/// <summary>
/// hme101c資料元件–無傳入值
/// </summary>
public class ndb_hme101c : WIT.Template.Project.n_dbbase
{
	private System.Data.OleDb.OleDbCommand oleDbDeleteCommand;
	private System.Data.OleDb.OleDbCommand oleDbInsertCommand;
	private System.Data.OleDb.OleDbCommand oleDbSelectCommand;
	private System.Data.OleDb.OleDbCommand oleDbUpdateCommand;
	private System.Data.OleDb.OleDbDataAdapter da_SQL_current;
	
	public ndb_hme101c(System.ComponentModel.IContainer container)
	{
		container.Add(this);
		InitializeComponent();
		// 將資料配接器設為 current
		da_SQL = da_SQL_current;
	}

	public ndb_hme101c()
	{
		InitializeComponent();
		// 將資料配接器設為 current
		da_SQL = da_SQL_current;
	}

	#region Component Designer generated code
	
	/// <summary>
	/// 此為設計工具支援所必需的方法 - 請勿使用程式碼編輯器修改
	/// 這個方法的內容。
	/// </summary>
	private void InitializeComponent()
	{
		this.da_SQL_current = new System.Data.OleDb.OleDbDataAdapter();
		this.oleDbDeleteCommand = new System.Data.OleDb.OleDbCommand();
		this.oleDbInsertCommand = new System.Data.OleDb.OleDbCommand();
		this.oleDbSelectCommand = new System.Data.OleDb.OleDbCommand();
		this.oleDbUpdateCommand = new System.Data.OleDb.OleDbCommand();
		
		((System.ComponentModel.ISupportInitialize)(this.ds_Data)).BeginInit();
		((System.ComponentModel.ISupportInitialize)(this.dv_View)).BeginInit();

		// 
		// 容器
		// 
		this.da_SQL_current.TableMappings.AddRange(new System.Data.Common.DataTableMapping[] {
			
                                           new System.Data.Common.DataTableMapping("Table", "hme101c", new System.Data.Common.DataColumnMapping[] {
                                           new System.Data.Common.DataColumnMapping("hme101c_vid", "hme101c_vid"),
                                           new System.Data.Common.DataColumnMapping("hme101c_pdid", "hme101c_pdid"),
                                           new System.Data.Common.DataColumnMapping("hme101c_onduty", "hme101c_onduty"),
                                           new System.Data.Common.DataColumnMapping("hme101c_absent", "hme101c_absent"),
                                           new System.Data.Common.DataColumnMapping("hme101c_cway", "hme101c_cway"),
                                           new System.Data.Common.DataColumnMapping("hme101c_aid", "hme101c_aid"),
                                           new System.Data.Common.DataColumnMapping("hme101c_adt", "hme101c_adt"),
                                           new System.Data.Common.DataColumnMapping("hme101c_uid", "hme101c_uid"),
                                           new System.Data.Common.DataColumnMapping("hme101c_udt", "hme101c_udt")
                                           })
            });
                                           
		// 
		// 刪除命令
		// 
		this.da_SQL_current.DeleteCommand = this.oleDbDeleteCommand;
		this.oleDbDeleteCommand.CommandText = "DELETE FROM [hme101c] WHERE (([hme101c_vid] = ?))  AND (([hme101c_pdid] = ?)) ";
		this.oleDbDeleteCommand.Connection = this.cn_DB;
		this.oleDbDeleteCommand.Parameters.AddRange(new System.Data.OleDb.OleDbParameter[] {
		                                                           new System.Data.OleDb.OleDbParameter("Original_hme101c_vid", System.Data.OleDb.OleDbType.VarChar, 0, System.Data.ParameterDirection.Input, false, ((byte)(12)), ((byte)(0)), "hme101c_vid", System.Data.DataRowVersion.Original, null),
                                                     new System.Data.OleDb.OleDbParameter("Original_hme101c_pdid", System.Data.OleDb.OleDbType.VarChar, 0, System.Data.ParameterDirection.Input, false, ((byte)(20)), ((byte)(0)), "hme101c_pdid", System.Data.DataRowVersion.Original, null)

		});


		// 
		// 新增區
		// 
		this.da_SQL_current.InsertCommand = this.oleDbInsertCommand;
		this.oleDbInsertCommand.CommandText = "INSERT INTO [hme101c] ([hme101c_vid],[hme101c_pdid],[hme101c_onduty],[hme101c_absent],[hme101c_cway],[hme101c_aid],[hme101c_adt],[hme101c_uid],[hme101c_udt]) VALUES (?,?,?,?,?,?,?,?,?)";
		this.oleDbInsertCommand.Connection = this.cn_DB;
		this.oleDbInsertCommand.Parameters.AddRange(new System.Data.OleDb.OleDbParameter[] {
		                                                           new System.Data.OleDb.OleDbParameter("hme101c_vid", System.Data.OleDb.OleDbType.VarChar, 0, "hme101c_vid"),
                                                     new System.Data.OleDb.OleDbParameter("hme101c_pdid", System.Data.OleDb.OleDbType.VarChar, 0, "hme101c_pdid"),
                                                     new System.Data.OleDb.OleDbParameter("hme101c_onduty", System.Data.OleDb.OleDbType.Double, 0, "hme101c_onduty"),
                                                     new System.Data.OleDb.OleDbParameter("hme101c_absent", System.Data.OleDb.OleDbType.Double, 0, "hme101c_absent"),
                                                     new System.Data.OleDb.OleDbParameter("hme101c_cway", System.Data.OleDb.OleDbType.VarChar, 0, "hme101c_cway"),
                                                     new System.Data.OleDb.OleDbParameter("hme101c_aid", System.Data.OleDb.OleDbType.VarChar, 0, "hme101c_aid"),
                                                     new System.Data.OleDb.OleDbParameter("hme101c_adt", System.Data.OleDb.OleDbType.DBTimeStamp, 0, "hme101c_adt"),
                                                     new System.Data.OleDb.OleDbParameter("hme101c_uid", System.Data.OleDb.OleDbType.VarChar, 0, "hme101c_uid"),
                                                     new System.Data.OleDb.OleDbParameter("hme101c_udt", System.Data.OleDb.OleDbType.DBTimeStamp, 0, "hme101c_udt")
		});


		// 
		// 查詢區
		// 
		this.da_SQL_current.SelectCommand = this.oleDbSelectCommand;				this.oleDbSelectCommand.CommandText = "SELECT * FROM [hme101c] WHERE (1=1) ";		this.oleDbSelectCommand.Connection = this.cn_DB;

		// 
		// 更新區
		// 
		this.da_SQL_current.UpdateCommand = this.oleDbUpdateCommand;
		this.oleDbUpdateCommand.CommandText = "UPDATE [hme101c] SET  [hme101c_vid] = ?, [hme101c_pdid] = ?, [hme101c_onduty] = ?, [hme101c_absent] = ?, [hme101c_cway] = ?, [hme101c_aid] = ?, [hme101c_adt] = ?, [hme101c_uid] = ?, [hme101c_udt] = ?  WHERE (([hme101c_vid] = ?)) AND (([hme101c_pdid] = ?)) ";
		this.oleDbUpdateCommand.Connection = this.cn_DB;
		this.oleDbUpdateCommand.Parameters.AddRange(new System.Data.OleDb.OleDbParameter[] {
		                                                           new System.Data.OleDb.OleDbParameter("hme101c_vid", System.Data.OleDb.OleDbType.VarChar, 0, "hme101c_vid"),
                                                     new System.Data.OleDb.OleDbParameter("hme101c_pdid", System.Data.OleDb.OleDbType.VarChar, 0, "hme101c_pdid"),
                                                     new System.Data.OleDb.OleDbParameter("hme101c_onduty", System.Data.OleDb.OleDbType.Double, 0, "hme101c_onduty"),
                                                     new System.Data.OleDb.OleDbParameter("hme101c_absent", System.Data.OleDb.OleDbType.Double, 0, "hme101c_absent"),
                                                     new System.Data.OleDb.OleDbParameter("hme101c_cway", System.Data.OleDb.OleDbType.VarChar, 0, "hme101c_cway"),
                                                     new System.Data.OleDb.OleDbParameter("hme101c_aid", System.Data.OleDb.OleDbType.VarChar, 0, "hme101c_aid"),
                                                     new System.Data.OleDb.OleDbParameter("hme101c_adt", System.Data.OleDb.OleDbType.DBTimeStamp, 0, "hme101c_adt"),
                                                     new System.Data.OleDb.OleDbParameter("hme101c_uid", System.Data.OleDb.OleDbType.VarChar, 0, "hme101c_uid"),
                                                     new System.Data.OleDb.OleDbParameter("hme101c_udt", System.Data.OleDb.OleDbType.DBTimeStamp, 0, "hme101c_udt"),
                                                     new System.Data.OleDb.OleDbParameter("Original_hme101c_vid", System.Data.OleDb.OleDbType.VarChar, 0, System.Data.ParameterDirection.Input, false, ((byte)(12)), ((byte)(0)), "hme101c_vid", System.Data.DataRowVersion.Original, null),
                                                     new System.Data.OleDb.OleDbParameter("Original_hme101c_pdid", System.Data.OleDb.OleDbType.VarChar, 0, System.Data.ParameterDirection.Input, false, ((byte)(20)), ((byte)(0)), "hme101c_pdid", System.Data.DataRowVersion.Original, null)
                                                });

		((System.ComponentModel.ISupportInitialize)(this.ds_Data)).EndInit();
		((System.ComponentModel.ISupportInitialize)(this.dv_View)).EndInit();


	}
	#endregion

	// =========================================================================
	/// <summary>
	/// 函式描述：自訂初始化函式（覆蓋上層）
	/// </summary>
	protected override void uf_InitializeComponent()
	{
		// 先將 DataSet 宣告為指定的結構再初始化
		this.ds_Data = new d_hme101c();
		this.uf_Initialize();
	}
}
