// *********************************************************************************
// 1. 程式描述：hme101a資料元件–無傳入值
// 2. 撰寫人員：generated by WITSTER  0.2.2 beta (by QFLin)
// *********************************************************************************
using System;
using System.ComponentModel;
using System.Collections;
using System.Diagnostics;

/// <summary>
/// hme101a資料元件–無傳入值
/// </summary>
public class ndb_hme101a : WIT.Template.Project.n_dbbase
{
	private System.Data.OleDb.OleDbCommand oleDbDeleteCommand;
	private System.Data.OleDb.OleDbCommand oleDbInsertCommand;
	private System.Data.OleDb.OleDbCommand oleDbSelectCommand;
	private System.Data.OleDb.OleDbCommand oleDbUpdateCommand;
	private System.Data.OleDb.OleDbDataAdapter da_SQL_current;
	
	public ndb_hme101a(System.ComponentModel.IContainer container)
	{
		container.Add(this);
		InitializeComponent();
		// 將資料配接器設為 current
		da_SQL = da_SQL_current;
	}

	public ndb_hme101a()
	{
		InitializeComponent();
		// 將資料配接器設為 current
		da_SQL = da_SQL_current;
	}

	#region Component Designer generated code
	
	/// <summary>
	/// 此為設計工具支援所必需的方法 - 請勿使用程式碼編輯器修改
	/// 這個方法的內容。
	/// </summary>
	private void InitializeComponent()
	{
		System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(ndb_hme101a));
		this.da_SQL_current = new System.Data.OleDb.OleDbDataAdapter();
		this.oleDbDeleteCommand = new System.Data.OleDb.OleDbCommand();
		this.oleDbInsertCommand = new System.Data.OleDb.OleDbCommand();
		this.oleDbSelectCommand = new System.Data.OleDb.OleDbCommand();
		this.oleDbUpdateCommand = new System.Data.OleDb.OleDbCommand();
		((System.ComponentModel.ISupportInitialize)(this.ds_Data)).BeginInit();
		((System.ComponentModel.ISupportInitialize)(this.dv_View)).BeginInit();
		// 
		// da_SQL_current
		// 
		this.da_SQL_current.DeleteCommand = this.oleDbDeleteCommand;
		this.da_SQL_current.InsertCommand = this.oleDbInsertCommand;
		this.da_SQL_current.SelectCommand = this.oleDbSelectCommand;
		this.da_SQL_current.TableMappings.AddRange(new System.Data.Common.DataTableMapping[] {
            new System.Data.Common.DataTableMapping("Table", "hme101a", new System.Data.Common.DataColumnMapping[] {
                        new System.Data.Common.DataColumnMapping("hme101a_psid", "hme101a_psid"),
                        new System.Data.Common.DataColumnMapping("hme101a_tid", "hme101a_tid"),
                        new System.Data.Common.DataColumnMapping("hme101a_syear", "hme101a_syear"),
                        new System.Data.Common.DataColumnMapping("hme101a_smonth", "hme101a_smonth"),
                        new System.Data.Common.DataColumnMapping("hme101a_makeflag", "hme101a_makeflag"),
                        new System.Data.Common.DataColumnMapping("hme101a_okflag", "hme101a_okflag"),
                        new System.Data.Common.DataColumnMapping("hme101a_openflag", "hme101a_openflag"),
                        new System.Data.Common.DataColumnMapping("hme101a_aid", "hme101a_aid"),
                        new System.Data.Common.DataColumnMapping("hme101a_adt", "hme101a_adt"),
                        new System.Data.Common.DataColumnMapping("hme101a_uid", "hme101a_uid"),
                        new System.Data.Common.DataColumnMapping("hme101a_udt", "hme101a_udt"),
                        new System.Data.Common.DataColumnMapping("hme101a_hrneedno", "hme101a_hrneedno")})});
		this.da_SQL_current.UpdateCommand = this.oleDbUpdateCommand;
		// 
		// oleDbDeleteCommand
		// 
		this.oleDbDeleteCommand.CommandText = "DELETE FROM [hme101a] WHERE (([hme101a_psid] = ?))";
		this.oleDbDeleteCommand.Connection = this.cn_DB;
		this.oleDbDeleteCommand.Parameters.AddRange(new System.Data.OleDb.OleDbParameter[] {
            new System.Data.OleDb.OleDbParameter("Original_hme101a_psid", System.Data.OleDb.OleDbType.VarWChar, 0, System.Data.ParameterDirection.Input, false, ((byte)(0)), ((byte)(0)), "hme101a_psid", System.Data.DataRowVersion.Original, null)});
		// 
		// oleDbInsertCommand
		// 
		this.oleDbInsertCommand.CommandText = "INSERT INTO [hme101a] ([hme101a_psid], [hme101a_tid], [hme101a_syear], [hme101a_smonth], [hme101a_makeflag], [hme101a_okflag], [hme101a_openflag], [hme101a_aid], [hme101a_adt], [hme101a_uid], [hme101a_udt],[hme101a_hrneedno]) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
		this.oleDbInsertCommand.Connection = this.cn_DB;
		this.oleDbInsertCommand.Parameters.AddRange(new System.Data.OleDb.OleDbParameter[] {
            new System.Data.OleDb.OleDbParameter("hme101a_psid", System.Data.OleDb.OleDbType.VarWChar, 0, "hme101a_psid"),
            new System.Data.OleDb.OleDbParameter("hme101a_tid", System.Data.OleDb.OleDbType.WChar, 0, "hme101a_tid"),
            new System.Data.OleDb.OleDbParameter("hme101a_syear", System.Data.OleDb.OleDbType.WChar, 0, "hme101a_syear"),
            new System.Data.OleDb.OleDbParameter("hme101a_smonth", System.Data.OleDb.OleDbType.WChar, 0, "hme101a_smonth"),
            new System.Data.OleDb.OleDbParameter("hme101a_makeflag", System.Data.OleDb.OleDbType.WChar, 0, "hme101a_makeflag"),
            new System.Data.OleDb.OleDbParameter("hme101a_okflag", System.Data.OleDb.OleDbType.WChar, 0, "hme101a_okflag"),
            new System.Data.OleDb.OleDbParameter("hme101a_openflag", System.Data.OleDb.OleDbType.WChar, 0, "hme101a_openflag"),
            new System.Data.OleDb.OleDbParameter("hme101a_aid", System.Data.OleDb.OleDbType.VarWChar, 0, "hme101a_aid"),
            new System.Data.OleDb.OleDbParameter("hme101a_adt", System.Data.OleDb.OleDbType.DBTimeStamp, 0, "hme101a_adt"),
            new System.Data.OleDb.OleDbParameter("hme101a_uid", System.Data.OleDb.OleDbType.VarWChar, 0, "hme101a_uid"),
            new System.Data.OleDb.OleDbParameter("hme101a_udt", System.Data.OleDb.OleDbType.DBTimeStamp, 0, "hme101a_udt"),
            new System.Data.OleDb.OleDbParameter("hme101a_hrneedno", System.Data.OleDb.OleDbType.WChar, 0, "hme101a_hrneedno")});
		// 
		// oleDbSelectCommand
		// 
		this.oleDbSelectCommand.CommandText = "SELECT * FROM [hme101a] WHERE (1=1) ";
		this.oleDbSelectCommand.Connection = this.cn_DB;
		// 
		// oleDbUpdateCommand
		// 
		this.oleDbUpdateCommand.CommandText = "UPDATE [hme101a] SET [hme101a_psid] = ?, [hme101a_tid] = ?, [hme101a_syear] = ?, [hme101a_smonth] = ?, [hme101a_makeflag] = ?, [hme101a_okflag] = ?, [hme101a_openflag] = ?, [hme101a_aid] = ?, [hme101a_adt] = ?, [hme101a_uid] = ?, [hme101a_udt] = ?, [hme101a_hrneedno] = ? WHERE (([hme101a_psid] = ?))";
		this.oleDbUpdateCommand.Connection = this.cn_DB;
		this.oleDbUpdateCommand.Parameters.AddRange(new System.Data.OleDb.OleDbParameter[] {
            new System.Data.OleDb.OleDbParameter("hme101a_psid", System.Data.OleDb.OleDbType.VarWChar, 0, "hme101a_psid"),
            new System.Data.OleDb.OleDbParameter("hme101a_tid", System.Data.OleDb.OleDbType.WChar, 0, "hme101a_tid"),
            new System.Data.OleDb.OleDbParameter("hme101a_syear", System.Data.OleDb.OleDbType.WChar, 0, "hme101a_syear"),
            new System.Data.OleDb.OleDbParameter("hme101a_smonth", System.Data.OleDb.OleDbType.WChar, 0, "hme101a_smonth"),
            new System.Data.OleDb.OleDbParameter("hme101a_makeflag", System.Data.OleDb.OleDbType.WChar, 0, "hme101a_makeflag"),
            new System.Data.OleDb.OleDbParameter("hme101a_okflag", System.Data.OleDb.OleDbType.WChar, 0, "hme101a_okflag"),
            new System.Data.OleDb.OleDbParameter("hme101a_openflag", System.Data.OleDb.OleDbType.WChar, 0, "hme101a_openflag"),
            new System.Data.OleDb.OleDbParameter("hme101a_aid", System.Data.OleDb.OleDbType.VarWChar, 0, "hme101a_aid"),
            new System.Data.OleDb.OleDbParameter("hme101a_adt", System.Data.OleDb.OleDbType.DBTimeStamp, 0, "hme101a_adt"),
            new System.Data.OleDb.OleDbParameter("hme101a_uid", System.Data.OleDb.OleDbType.VarWChar, 0, "hme101a_uid"),
            new System.Data.OleDb.OleDbParameter("hme101a_udt", System.Data.OleDb.OleDbType.DBTimeStamp, 0, "hme101a_udt"),
            new System.Data.OleDb.OleDbParameter("hme101a_hrneedno", System.Data.OleDb.OleDbType.WChar, 0, "hme101a_hrneedno"),
            new System.Data.OleDb.OleDbParameter("Original_hme101a_psid", System.Data.OleDb.OleDbType.VarWChar, 0, System.Data.ParameterDirection.Input, false, ((byte)(0)), ((byte)(0)), "hme101a_psid", System.Data.DataRowVersion.Original, null)});
		((System.ComponentModel.ISupportInitialize)(this.ds_Data)).EndInit();
		((System.ComponentModel.ISupportInitialize)(this.dv_View)).EndInit();

	}
	#endregion

	// =========================================================================
	/// <summary>
	/// 函式描述：自訂初始化函式（覆蓋上層）
	/// </summary>
	protected override void uf_InitializeComponent()
	{
		// 先將 DataSet 宣告為指定的結構再初始化
		this.ds_Data = new d_hme101a();
		this.uf_Initialize();
	}
}
