// *********************************************************************************
// 1. 程式描述：hca211資料元件–無傳入值
// 2. 撰寫人員：generated by WITSTER  0.2.2 beta (by QFLin)
// *********************************************************************************
using System;
using System.ComponentModel;
using System.Collections;
using System.Diagnostics;


/// <summary>
/// ndb_hca212 的摘要描述
/// </summary>
public class ndb_hca212: WIT.Template.Project.n_dbbase
{
	private System.Data.OleDb.OleDbCommand oleDbDeleteCommand;
	private System.Data.OleDb.OleDbCommand oleDbInsertCommand;
	private System.Data.OleDb.OleDbCommand oleDbSelectCommand;
	private System.Data.OleDb.OleDbCommand oleDbUpdateCommand;
	private System.Data.OleDb.OleDbDataAdapter da_SQL_current;
	
	public ndb_hca212(System.ComponentModel.IContainer container)
	{
		container.Add(this);
		InitializeComponent();
		// 將資料配接器設為 current
		da_SQL = da_SQL_current;
	}

	public ndb_hca212()
	{
		InitializeComponent();
		// 將資料配接器設為 current
		da_SQL = da_SQL_current;
	}

	#region Component Designer generated code
	
	/// <summary>
	/// 此為設計工具支援所必需的方法 - 請勿使用程式碼編輯器修改
	/// 這個方法的內容。
	/// </summary>
	private void InitializeComponent()
	{
		this.da_SQL_current = new System.Data.OleDb.OleDbDataAdapter();
		this.oleDbDeleteCommand = new System.Data.OleDb.OleDbCommand();
		this.oleDbInsertCommand = new System.Data.OleDb.OleDbCommand();
		this.oleDbSelectCommand = new System.Data.OleDb.OleDbCommand();
		this.oleDbUpdateCommand = new System.Data.OleDb.OleDbCommand();
		((System.ComponentModel.ISupportInitialize)(this.ds_Data)).BeginInit();
		((System.ComponentModel.ISupportInitialize)(this.dv_View)).BeginInit();
		// 
		// da_SQL_current
		// 
		this.da_SQL_current.DeleteCommand = this.oleDbDeleteCommand;
		this.da_SQL_current.InsertCommand = this.oleDbInsertCommand;
		this.da_SQL_current.SelectCommand = this.oleDbSelectCommand;
		this.da_SQL_current.TableMappings.AddRange(new System.Data.Common.DataTableMapping[] {
            new System.Data.Common.DataTableMapping("Table", "hca212", new System.Data.Common.DataColumnMapping[] {
                        new System.Data.Common.DataColumnMapping("hca212_id", "hca212_id"),
                        new System.Data.Common.DataColumnMapping("hca212_name", "hca212_name"),
                        new System.Data.Common.DataColumnMapping("hca212_sort", "hca212_sort"),
                        new System.Data.Common.DataColumnMapping("hca212_stop", "hca212_stop"),
                        new System.Data.Common.DataColumnMapping("hca212_aid", "hca212_aid"),
                        new System.Data.Common.DataColumnMapping("hca212_adt", "hca212_adt"),
                        new System.Data.Common.DataColumnMapping("hca212_uid", "hca212_uid"),
                        new System.Data.Common.DataColumnMapping("hca212_udt", "hca212_udt")})});
		this.da_SQL_current.UpdateCommand = this.oleDbUpdateCommand;
		// 
		// oleDbDeleteCommand
		// 
		this.oleDbDeleteCommand.CommandText = "DELETE FROM [hca212] WHERE (([hca212_id] = ?))";
		this.oleDbDeleteCommand.Connection = this.cn_DB;
		this.oleDbDeleteCommand.Parameters.AddRange(new System.Data.OleDb.OleDbParameter[] {
            new System.Data.OleDb.OleDbParameter("Original_hca212_id", System.Data.OleDb.OleDbType.WChar, 0, System.Data.ParameterDirection.Input, false, ((byte)(0)), ((byte)(0)), "hca212_id", System.Data.DataRowVersion.Original, null)});
		// 
		// oleDbInsertCommand
		// 
		this.oleDbInsertCommand.CommandText = "INSERT INTO [hca212] ([hca212_id], [hca212_name], [hca212_sort], [hca212_stop], [" +
			"hca212_aid], [hca212_adt], [hca212_uid], [hca212_udt]) VALUES (?, ?, ?, ?, ?, ?," +
			" ?, ?)";
		this.oleDbInsertCommand.Connection = this.cn_DB;
		this.oleDbInsertCommand.Parameters.AddRange(new System.Data.OleDb.OleDbParameter[] {
            new System.Data.OleDb.OleDbParameter("hca212_id", System.Data.OleDb.OleDbType.WChar, 0, "hca212_id"),
            new System.Data.OleDb.OleDbParameter("hca212_name", System.Data.OleDb.OleDbType.WChar, 0, "hca212_name"),
            new System.Data.OleDb.OleDbParameter("hca212_sort", System.Data.OleDb.OleDbType.SmallInt, 0, "hca212_sort"),
            new System.Data.OleDb.OleDbParameter("hca212_stop", System.Data.OleDb.OleDbType.WChar, 0, "hca212_stop"),
            new System.Data.OleDb.OleDbParameter("hca212_aid", System.Data.OleDb.OleDbType.VarWChar, 0, "hca212_aid"),
            new System.Data.OleDb.OleDbParameter("hca212_adt", System.Data.OleDb.OleDbType.DBTimeStamp, 0, "hca212_adt"),
            new System.Data.OleDb.OleDbParameter("hca212_uid", System.Data.OleDb.OleDbType.VarWChar, 0, "hca212_uid"),
            new System.Data.OleDb.OleDbParameter("hca212_udt", System.Data.OleDb.OleDbType.DBTimeStamp, 0, "hca212_udt")});
		// 
		// oleDbSelectCommand
		// 
		this.oleDbSelectCommand.CommandText = "SELECT         hca212_id, hca212_name, hca212_sort, hca212_stop, hca212_aid, hca2" +
			"12_adt, \r\n                          hca212_uid, hca212_udt\r\nFROM             hca" +
			"212\r\nWHERE         (1 = 1)";
		this.oleDbSelectCommand.Connection = this.cn_DB;
		// 
		// oleDbUpdateCommand
		// 
		this.oleDbUpdateCommand.CommandText = "UPDATE [hca212] SET [hca212_id] = ?, [hca212_name] = ?, [hca212_sort] = ?, [hca21" +
			"2_stop] = ?, [hca212_aid] = ?, [hca212_adt] = ?, [hca212_uid] = ?, [hca212_udt] " +
			"= ? WHERE (([hca212_id] = ?))";
		this.oleDbUpdateCommand.Connection = this.cn_DB;
		this.oleDbUpdateCommand.Parameters.AddRange(new System.Data.OleDb.OleDbParameter[] {
            new System.Data.OleDb.OleDbParameter("hca212_id", System.Data.OleDb.OleDbType.WChar, 0, "hca212_id"),
            new System.Data.OleDb.OleDbParameter("hca212_name", System.Data.OleDb.OleDbType.WChar, 0, "hca212_name"),
            new System.Data.OleDb.OleDbParameter("hca212_sort", System.Data.OleDb.OleDbType.SmallInt, 0, "hca212_sort"),
            new System.Data.OleDb.OleDbParameter("hca212_stop", System.Data.OleDb.OleDbType.WChar, 0, "hca212_stop"),
            new System.Data.OleDb.OleDbParameter("hca212_aid", System.Data.OleDb.OleDbType.VarWChar, 0, "hca212_aid"),
            new System.Data.OleDb.OleDbParameter("hca212_adt", System.Data.OleDb.OleDbType.DBTimeStamp, 0, "hca212_adt"),
            new System.Data.OleDb.OleDbParameter("hca212_uid", System.Data.OleDb.OleDbType.VarWChar, 0, "hca212_uid"),
            new System.Data.OleDb.OleDbParameter("hca212_udt", System.Data.OleDb.OleDbType.DBTimeStamp, 0, "hca212_udt"),
            new System.Data.OleDb.OleDbParameter("Original_hca212_id", System.Data.OleDb.OleDbType.WChar, 0, System.Data.ParameterDirection.Input, false, ((byte)(0)), ((byte)(0)), "hca212_id", System.Data.DataRowVersion.Original, null)});
		((System.ComponentModel.ISupportInitialize)(this.ds_Data)).EndInit();
		((System.ComponentModel.ISupportInitialize)(this.dv_View)).EndInit();

	}
	#endregion

	// =========================================================================
	/// <summary>
	/// 函式描述：自訂初始化函式（覆蓋上層）
	/// </summary>
	protected override void uf_InitializeComponent()
	{
		// 先將 DataSet 宣告為指定的結構再初始化
		this.ds_Data = new d_hca212();
		this.uf_Initialize();
	}
}
