// *********************************************************************************
// 1. 程式描述：hmf103資料元件–無傳入值
// 2. 撰寫人員：generated by WITSTER  0.2.2 beta (by QFLin)
// *********************************************************************************
using System;
using System.ComponentModel;
using System.Collections;
using System.Diagnostics;

/// <summary>
/// hmf103資料元件–無傳入值
/// </summary>
public class ndb_hmf103 : WIT.Template.Project.n_dbbase
{
	private System.Data.OleDb.OleDbCommand oleDbDeleteCommand;
	private System.Data.OleDb.OleDbCommand oleDbInsertCommand;
	private System.Data.OleDb.OleDbCommand oleDbSelectCommand;
	private System.Data.OleDb.OleDbCommand oleDbUpdateCommand;
	private System.Data.OleDb.OleDbDataAdapter da_SQL_current;
	
	public ndb_hmf103(System.ComponentModel.IContainer container)
	{
		container.Add(this);
		InitializeComponent();
		// 將資料配接器設為 current
		da_SQL = da_SQL_current;
	}

	public ndb_hmf103()
	{
		InitializeComponent();
		// 將資料配接器設為 current
		da_SQL = da_SQL_current;
	}

	#region Component Designer generated code
	
	/// <summary>
	/// 此為設計工具支援所必需的方法 - 請勿使用程式碼編輯器修改
	/// 這個方法的內容。
	/// </summary>
	private void InitializeComponent()
	{
		this.da_SQL_current = new System.Data.OleDb.OleDbDataAdapter();
		this.oleDbDeleteCommand = new System.Data.OleDb.OleDbCommand();
		this.oleDbInsertCommand = new System.Data.OleDb.OleDbCommand();
		this.oleDbSelectCommand = new System.Data.OleDb.OleDbCommand();
		this.oleDbUpdateCommand = new System.Data.OleDb.OleDbCommand();
		
		((System.ComponentModel.ISupportInitialize)(this.ds_Data)).BeginInit();
		((System.ComponentModel.ISupportInitialize)(this.dv_View)).BeginInit();

		// 
		// 容器
		// 
		this.da_SQL_current.TableMappings.AddRange(new System.Data.Common.DataTableMapping[] {
			
                                           new System.Data.Common.DataTableMapping("Table", "hmf103", new System.Data.Common.DataColumnMapping[] {
                                           new System.Data.Common.DataColumnMapping("hmf103_trainid", "hmf103_trainid"),
                                           new System.Data.Common.DataColumnMapping("hmf103_vid", "hmf103_vid"),
                                           new System.Data.Common.DataColumnMapping("hmf103_ps", "hmf103_ps"),
                                           new System.Data.Common.DataColumnMapping("hmf103_onduty", "hmf103_onduty"),
                                           new System.Data.Common.DataColumnMapping("hmf103_absent", "hmf103_absent"),
                                           new System.Data.Common.DataColumnMapping("hmf103_cway", "hmf103_cway"),
                                           new System.Data.Common.DataColumnMapping("hmf103_aid", "hmf103_aid"),
                                           new System.Data.Common.DataColumnMapping("hmf103_adt", "hmf103_adt"),
                                           new System.Data.Common.DataColumnMapping("hmf103_uid", "hmf103_uid"),
                                           new System.Data.Common.DataColumnMapping("hmf103_udt", "hmf103_udt")
                                           })
            });
                                           
		// 
		// 刪除命令
		// 
		this.da_SQL_current.DeleteCommand = this.oleDbDeleteCommand;
		this.oleDbDeleteCommand.CommandText = "DELETE FROM [hmf103] WHERE (([hmf103_trainid] = ?))  AND (([hmf103_vid] = ?)) ";
		this.oleDbDeleteCommand.Connection = this.cn_DB;
		this.oleDbDeleteCommand.Parameters.AddRange(new System.Data.OleDb.OleDbParameter[] {
		                                                           new System.Data.OleDb.OleDbParameter("Original_hmf103_trainid", System.Data.OleDb.OleDbType.VarChar, 0, System.Data.ParameterDirection.Input, false, ((byte)(20)), ((byte)(0)), "hmf103_trainid", System.Data.DataRowVersion.Original, null),
                                                     new System.Data.OleDb.OleDbParameter("Original_hmf103_vid", System.Data.OleDb.OleDbType.VarChar, 0, System.Data.ParameterDirection.Input, false, ((byte)(20)), ((byte)(0)), "hmf103_vid", System.Data.DataRowVersion.Original, null)

		});


		// 
		// 新增區
		// 
		this.da_SQL_current.InsertCommand = this.oleDbInsertCommand;
		this.oleDbInsertCommand.CommandText = "INSERT INTO [hmf103] ([hmf103_trainid],[hmf103_vid],[hmf103_ps],[hmf103_onduty],[hmf103_absent],[hmf103_cway],[hmf103_aid],[hmf103_adt],[hmf103_uid],[hmf103_udt]) VALUES (?,?,?,?,?,?,?,?,?,?)";
		this.oleDbInsertCommand.Connection = this.cn_DB;
		this.oleDbInsertCommand.Parameters.AddRange(new System.Data.OleDb.OleDbParameter[] {
		                                                           new System.Data.OleDb.OleDbParameter("hmf103_trainid", System.Data.OleDb.OleDbType.VarChar, 0, "hmf103_trainid"),
                                                     new System.Data.OleDb.OleDbParameter("hmf103_vid", System.Data.OleDb.OleDbType.VarChar, 0, "hmf103_vid"),
                                                     new System.Data.OleDb.OleDbParameter("hmf103_ps", System.Data.OleDb.OleDbType.LongVarChar, 0, "hmf103_ps"),
                                                     new System.Data.OleDb.OleDbParameter("hmf103_onduty", System.Data.OleDb.OleDbType.Double, 0, "hmf103_onduty"),
                                                     new System.Data.OleDb.OleDbParameter("hmf103_absent", System.Data.OleDb.OleDbType.Double, 0, "hmf103_absent"),
                                                     new System.Data.OleDb.OleDbParameter("hmf103_cway", System.Data.OleDb.OleDbType.VarChar, 0, "hmf103_cway"),
                                                     new System.Data.OleDb.OleDbParameter("hmf103_aid", System.Data.OleDb.OleDbType.VarChar, 0, "hmf103_aid"),
                                                     new System.Data.OleDb.OleDbParameter("hmf103_adt", System.Data.OleDb.OleDbType.DBTimeStamp, 0, "hmf103_adt"),
                                                     new System.Data.OleDb.OleDbParameter("hmf103_uid", System.Data.OleDb.OleDbType.VarChar, 0, "hmf103_uid"),
                                                     new System.Data.OleDb.OleDbParameter("hmf103_udt", System.Data.OleDb.OleDbType.DBTimeStamp, 0, "hmf103_udt")
		});


		// 
		// 查詢區
		// 
		this.da_SQL_current.SelectCommand = this.oleDbSelectCommand;				this.oleDbSelectCommand.CommandText = "SELECT * FROM [hmf103] WHERE (1=1) ";		this.oleDbSelectCommand.Connection = this.cn_DB;

		// 
		// 更新區
		// 
		this.da_SQL_current.UpdateCommand = this.oleDbUpdateCommand;
		this.oleDbUpdateCommand.CommandText = "UPDATE [hmf103] SET  [hmf103_trainid] = ?, [hmf103_vid] = ?, [hmf103_ps] = ?, [hmf103_onduty] = ?, [hmf103_absent] = ?, [hmf103_cway] = ?, [hmf103_aid] = ?, [hmf103_adt] = ?, [hmf103_uid] = ?, [hmf103_udt] = ?  WHERE (([hmf103_trainid] = ?)) AND (([hmf103_vid] = ?)) ";
		this.oleDbUpdateCommand.Connection = this.cn_DB;
		this.oleDbUpdateCommand.Parameters.AddRange(new System.Data.OleDb.OleDbParameter[] {
		                                                           new System.Data.OleDb.OleDbParameter("hmf103_trainid", System.Data.OleDb.OleDbType.VarChar, 0, "hmf103_trainid"),
                                                     new System.Data.OleDb.OleDbParameter("hmf103_vid", System.Data.OleDb.OleDbType.VarChar, 0, "hmf103_vid"),
                                                     new System.Data.OleDb.OleDbParameter("hmf103_ps", System.Data.OleDb.OleDbType.LongVarChar, 0, "hmf103_ps"),
                                                     new System.Data.OleDb.OleDbParameter("hmf103_onduty", System.Data.OleDb.OleDbType.Double, 0, "hmf103_onduty"),
                                                     new System.Data.OleDb.OleDbParameter("hmf103_absent", System.Data.OleDb.OleDbType.Double, 0, "hmf103_absent"),
                                                     new System.Data.OleDb.OleDbParameter("hmf103_cway", System.Data.OleDb.OleDbType.VarChar, 0, "hmf103_cway"),
                                                     new System.Data.OleDb.OleDbParameter("hmf103_aid", System.Data.OleDb.OleDbType.VarChar, 0, "hmf103_aid"),
                                                     new System.Data.OleDb.OleDbParameter("hmf103_adt", System.Data.OleDb.OleDbType.DBTimeStamp, 0, "hmf103_adt"),
                                                     new System.Data.OleDb.OleDbParameter("hmf103_uid", System.Data.OleDb.OleDbType.VarChar, 0, "hmf103_uid"),
                                                     new System.Data.OleDb.OleDbParameter("hmf103_udt", System.Data.OleDb.OleDbType.DBTimeStamp, 0, "hmf103_udt"),
                                                     new System.Data.OleDb.OleDbParameter("Original_hmf103_trainid", System.Data.OleDb.OleDbType.VarChar, 0, System.Data.ParameterDirection.Input, false, ((byte)(20)), ((byte)(0)), "hmf103_trainid", System.Data.DataRowVersion.Original, null),
                                                     new System.Data.OleDb.OleDbParameter("Original_hmf103_vid", System.Data.OleDb.OleDbType.VarChar, 0, System.Data.ParameterDirection.Input, false, ((byte)(20)), ((byte)(0)), "hmf103_vid", System.Data.DataRowVersion.Original, null)
                                                });

		((System.ComponentModel.ISupportInitialize)(this.ds_Data)).EndInit();
		((System.ComponentModel.ISupportInitialize)(this.dv_View)).EndInit();


	}
	#endregion

	// =========================================================================
	/// <summary>
	/// 函式描述：自訂初始化函式（覆蓋上層）
	/// </summary>
	protected override void uf_InitializeComponent()
	{
		// 先將 DataSet 宣告為指定的結構再初始化
		this.ds_Data = new d_hmf103();
		this.uf_Initialize();
	}
}
