// *********************************************************************************
// 1. 程式描述：hmd201資料元件–無傳入值
// 2. 撰寫人員：generated by WITSTER  0.2.2 beta (by QFLin)
// *********************************************************************************
using System;
using System.ComponentModel;
using System.Collections;
using System.Diagnostics;

/// <summary>
/// hmd201資料元件–無傳入值
/// </summary>
public class ndb_hmd201 : WIT.Template.Project.n_dbbase
{
	private System.Data.OleDb.OleDbCommand oleDbDeleteCommand;
	private System.Data.OleDb.OleDbCommand oleDbInsertCommand;
	private System.Data.OleDb.OleDbCommand oleDbSelectCommand;
	private System.Data.OleDb.OleDbCommand oleDbUpdateCommand;
	private System.Data.OleDb.OleDbDataAdapter da_SQL_current;
	
	public ndb_hmd201(System.ComponentModel.IContainer container)
	{
		container.Add(this);
		InitializeComponent();
		// 將資料配接器設為 current
		da_SQL = da_SQL_current;
	}

	public ndb_hmd201()
	{
		InitializeComponent();
		// 將資料配接器設為 current
		da_SQL = da_SQL_current;
	}

	#region Component Designer generated code
	
	/// <summary>
	/// 此為設計工具支援所必需的方法 - 請勿使用程式碼編輯器修改
	/// 這個方法的內容。
	/// </summary>
	private void InitializeComponent()
	{
		System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(ndb_hmd201));
		this.da_SQL_current = new System.Data.OleDb.OleDbDataAdapter();
		this.oleDbDeleteCommand = new System.Data.OleDb.OleDbCommand();
		this.oleDbInsertCommand = new System.Data.OleDb.OleDbCommand();
		this.oleDbSelectCommand = new System.Data.OleDb.OleDbCommand();
		this.oleDbUpdateCommand = new System.Data.OleDb.OleDbCommand();
		((System.ComponentModel.ISupportInitialize)(this.ds_Data)).BeginInit();
		((System.ComponentModel.ISupportInitialize)(this.dv_View)).BeginInit();
		// 
		// da_SQL_current
		// 
		this.da_SQL_current.DeleteCommand = this.oleDbDeleteCommand;
		this.da_SQL_current.InsertCommand = this.oleDbInsertCommand;
		this.da_SQL_current.SelectCommand = this.oleDbSelectCommand;
		this.da_SQL_current.TableMappings.AddRange(new System.Data.Common.DataTableMapping[] {
            new System.Data.Common.DataTableMapping("Table", "hmd201", new System.Data.Common.DataColumnMapping[] {
                        new System.Data.Common.DataColumnMapping("hmd201_vid", "hmd201_vid"),
                        new System.Data.Common.DataColumnMapping("hmd201_id", "hmd201_id"),
                        new System.Data.Common.DataColumnMapping("hmd201_cname", "hmd201_cname"),
                        new System.Data.Common.DataColumnMapping("hmd201_ename", "hmd201_ename"),
                        new System.Data.Common.DataColumnMapping("hmd201_gent", "hmd201_gent"),
                        new System.Data.Common.DataColumnMapping("hmd201_bday", "hmd201_bday"),
                        new System.Data.Common.DataColumnMapping("hmd201_SSN", "hmd201_SSN"),
                        new System.Data.Common.DataColumnMapping("hmd201_eduid", "hmd201_eduid"),
                        new System.Data.Common.DataColumnMapping("hmd201_jobid", "hmd201_jobid"),
                        new System.Data.Common.DataColumnMapping("hmd201_joborg", "hmd201_joborg"),
                        new System.Data.Common.DataColumnMapping("hmd201_jobtitle", "hmd201_jobtitle"),
                        new System.Data.Common.DataColumnMapping("hmd201_addid", "hmd201_addid"),
                        new System.Data.Common.DataColumnMapping("hmd201_addot", "hmd201_addot"),
                        new System.Data.Common.DataColumnMapping("hmd201_email", "hmd201_email"),
                        new System.Data.Common.DataColumnMapping("hmd201_phnow", "hmd201_phnow"),
                        new System.Data.Common.DataColumnMapping("hmd201_phnowex", "hmd201_phnowex"),
                        new System.Data.Common.DataColumnMapping("hmd201_phnoa", "hmd201_phnoa"),
                        new System.Data.Common.DataColumnMapping("hmd201_phnom", "hmd201_phnom"),
                        new System.Data.Common.DataColumnMapping("hmd201_memberid", "hmd201_memberid"),
                        new System.Data.Common.DataColumnMapping("hmd201_memberpwd", "hmd201_memberpwd"),
                        new System.Data.Common.DataColumnMapping("hmd201_passed", "hmd201_passed"),
                        new System.Data.Common.DataColumnMapping("hmd201_rejectepaper", "hmd201_rejectepaper"),
                        new System.Data.Common.DataColumnMapping("hmd201_ps", "hmd201_ps"),
                        new System.Data.Common.DataColumnMapping("hmd201_notel", "hmd201_notel"),
                        new System.Data.Common.DataColumnMapping("hmd201_expert", "hmd201_expert"),
                        new System.Data.Common.DataColumnMapping("hmd201_tid", "hmd201_tid"),
                        new System.Data.Common.DataColumnMapping("hmd201_marriage", "hmd201_marriage"),
                        new System.Data.Common.DataColumnMapping("hmd201_children", "hmd201_children"),
                        new System.Data.Common.DataColumnMapping("hmd201_account", "hmd201_account"),
                        new System.Data.Common.DataColumnMapping("hmd201_pwd", "hmd201_pwd"),
                        new System.Data.Common.DataColumnMapping("hmd201_ssntype", "hmd201_ssntype"),
                        new System.Data.Common.DataColumnMapping("hmd201_bookid", "hmd201_bookid"),
                        new System.Data.Common.DataColumnMapping("hmd201_weburl", "hmd201_weburl"),
                        new System.Data.Common.DataColumnMapping("hmd201_introtext", "hmd201_introtext"),
                        new System.Data.Common.DataColumnMapping("hmd201_serviceexp", "hmd201_serviceexp"),
                        new System.Data.Common.DataColumnMapping("hmd201_lvid", "hmd201_lvid"),
                        new System.Data.Common.DataColumnMapping("hmd201_status", "hmd201_status"),
                        new System.Data.Common.DataColumnMapping("hmd201_workday", "hmd201_workday"),
                        new System.Data.Common.DataColumnMapping("hmd201_lappdt", "hmd201_lappdt"),
                        new System.Data.Common.DataColumnMapping("hmd201_creatway", "hmd201_creatway"),
                        new System.Data.Common.DataColumnMapping("hmd201_photo", "hmd201_photo"),
                        new System.Data.Common.DataColumnMapping("hmd201_filetype", "hmd201_filetype"),
                        new System.Data.Common.DataColumnMapping("hmd201_enCodeID", "hmd201_enCodeID"),
                        new System.Data.Common.DataColumnMapping("hmd201_Forum_id", "hmd201_Forum_id"),
                        new System.Data.Common.DataColumnMapping("hmd201_aid", "hmd201_aid"),
                        new System.Data.Common.DataColumnMapping("hmd201_adt", "hmd201_adt"),
                        new System.Data.Common.DataColumnMapping("hmd201_uid", "hmd201_uid"),
                        new System.Data.Common.DataColumnMapping("hmd201_udt", "hmd201_udt")})});
		this.da_SQL_current.UpdateCommand = this.oleDbUpdateCommand;
		// 
		// oleDbDeleteCommand
		// 
		this.oleDbDeleteCommand.CommandText = "DELETE FROM [hmd201] WHERE (([hmd201_vid] = ?))";
		this.oleDbDeleteCommand.Connection = this.cn_DB;
		this.oleDbDeleteCommand.Parameters.AddRange(new System.Data.OleDb.OleDbParameter[] {
            new System.Data.OleDb.OleDbParameter("Original_hmd201_vid", System.Data.OleDb.OleDbType.VarWChar, 0, System.Data.ParameterDirection.Input, false, ((byte)(0)), ((byte)(0)), "hmd201_vid", System.Data.DataRowVersion.Original, null)});
		// 
		// oleDbInsertCommand
		// 
		this.oleDbInsertCommand.CommandText = "INSERT INTO [hmd201] ([hmd201_vid], [hmd201_id], [hmd201_cname], [hmd201_ename], [hmd201_gent], [hmd201_bday], [hmd201_SSN], [hmd201_eduid], [hmd201_jobid], [hmd201_joborg], [hmd201_jobtitle], [hmd201_addid], [hmd201_addot], [hmd201_email], [hmd201_phnow], [hmd201_phnowex], [hmd201_phnoa], [hmd201_phnom], [hmd201_memberid], [hmd201_memberpwd], [hmd201_passed], [hmd201_rejectepaper], [hmd201_ps], [hmd201_notel], [hmd201_expert], [hmd201_tid], [hmd201_marriage], [hmd201_children], [hmd201_account], [hmd201_pwd], [hmd201_ssntype], [hmd201_bookid], [hmd201_weburl], [hmd201_introtext], [hmd201_serviceexp], [hmd201_lvid], [hmd201_status], [hmd201_workday], [hmd201_lappdt], [hmd201_creatway], [hmd201_photo], [hmd201_filetype], [hmd201_enCodeID], [hmd201_Forum_id], [hmd201_aid], [hmd201_adt], [hmd201_uid], [hmd201_udt]) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
		this.oleDbInsertCommand.Connection = this.cn_DB;
		this.oleDbInsertCommand.Parameters.AddRange(new System.Data.OleDb.OleDbParameter[] {
            new System.Data.OleDb.OleDbParameter("hmd201_vid", System.Data.OleDb.OleDbType.VarWChar, 0, "hmd201_vid"),
            new System.Data.OleDb.OleDbParameter("hmd201_id", System.Data.OleDb.OleDbType.VarWChar, 0, "hmd201_id"),
            new System.Data.OleDb.OleDbParameter("hmd201_cname", System.Data.OleDb.OleDbType.VarWChar, 0, "hmd201_cname"),
            new System.Data.OleDb.OleDbParameter("hmd201_ename", System.Data.OleDb.OleDbType.VarWChar, 0, "hmd201_ename"),
            new System.Data.OleDb.OleDbParameter("hmd201_gent", System.Data.OleDb.OleDbType.WChar, 0, "hmd201_gent"),
            new System.Data.OleDb.OleDbParameter("hmd201_bday", System.Data.OleDb.OleDbType.DBTimeStamp, 0, "hmd201_bday"),
            new System.Data.OleDb.OleDbParameter("hmd201_SSN", System.Data.OleDb.OleDbType.VarWChar, 0, "hmd201_SSN"),
            new System.Data.OleDb.OleDbParameter("hmd201_eduid", System.Data.OleDb.OleDbType.WChar, 0, "hmd201_eduid"),
            new System.Data.OleDb.OleDbParameter("hmd201_jobid", System.Data.OleDb.OleDbType.WChar, 0, "hmd201_jobid"),
            new System.Data.OleDb.OleDbParameter("hmd201_joborg", System.Data.OleDb.OleDbType.VarWChar, 0, "hmd201_joborg"),
            new System.Data.OleDb.OleDbParameter("hmd201_jobtitle", System.Data.OleDb.OleDbType.VarWChar, 0, "hmd201_jobtitle"),
            new System.Data.OleDb.OleDbParameter("hmd201_addid", System.Data.OleDb.OleDbType.WChar, 0, "hmd201_addid"),
            new System.Data.OleDb.OleDbParameter("hmd201_addot", System.Data.OleDb.OleDbType.VarWChar, 0, "hmd201_addot"),
            new System.Data.OleDb.OleDbParameter("hmd201_email", System.Data.OleDb.OleDbType.VarWChar, 0, "hmd201_email"),
            new System.Data.OleDb.OleDbParameter("hmd201_phnow", System.Data.OleDb.OleDbType.WChar, 0, "hmd201_phnow"),
            new System.Data.OleDb.OleDbParameter("hmd201_phnowex", System.Data.OleDb.OleDbType.WChar, 0, "hmd201_phnowex"),
            new System.Data.OleDb.OleDbParameter("hmd201_phnoa", System.Data.OleDb.OleDbType.WChar, 0, "hmd201_phnoa"),
            new System.Data.OleDb.OleDbParameter("hmd201_phnom", System.Data.OleDb.OleDbType.WChar, 0, "hmd201_phnom"),
            new System.Data.OleDb.OleDbParameter("hmd201_memberid", System.Data.OleDb.OleDbType.VarWChar, 0, "hmd201_memberid"),
            new System.Data.OleDb.OleDbParameter("hmd201_memberpwd", System.Data.OleDb.OleDbType.VarWChar, 0, "hmd201_memberpwd"),
            new System.Data.OleDb.OleDbParameter("hmd201_passed", System.Data.OleDb.OleDbType.WChar, 0, "hmd201_passed"),
            new System.Data.OleDb.OleDbParameter("hmd201_rejectepaper", System.Data.OleDb.OleDbType.WChar, 0, "hmd201_rejectepaper"),
            new System.Data.OleDb.OleDbParameter("hmd201_ps", System.Data.OleDb.OleDbType.LongVarWChar, 0, "hmd201_ps"),
            new System.Data.OleDb.OleDbParameter("hmd201_notel", System.Data.OleDb.OleDbType.LongVarWChar, 0, "hmd201_notel"),
            new System.Data.OleDb.OleDbParameter("hmd201_expert", System.Data.OleDb.OleDbType.LongVarWChar, 0, "hmd201_expert"),
            new System.Data.OleDb.OleDbParameter("hmd201_tid", System.Data.OleDb.OleDbType.VarWChar, 0, "hmd201_tid"),
            new System.Data.OleDb.OleDbParameter("hmd201_marriage", System.Data.OleDb.OleDbType.WChar, 0, "hmd201_marriage"),
            new System.Data.OleDb.OleDbParameter("hmd201_children", System.Data.OleDb.OleDbType.SmallInt, 0, "hmd201_children"),
            new System.Data.OleDb.OleDbParameter("hmd201_account", System.Data.OleDb.OleDbType.WChar, 0, "hmd201_account"),
            new System.Data.OleDb.OleDbParameter("hmd201_pwd", System.Data.OleDb.OleDbType.WChar, 0, "hmd201_pwd"),
            new System.Data.OleDb.OleDbParameter("hmd201_ssntype", System.Data.OleDb.OleDbType.WChar, 0, "hmd201_ssntype"),
            new System.Data.OleDb.OleDbParameter("hmd201_bookid", System.Data.OleDb.OleDbType.VarWChar, 0, "hmd201_bookid"),
            new System.Data.OleDb.OleDbParameter("hmd201_weburl", System.Data.OleDb.OleDbType.VarWChar, 0, "hmd201_weburl"),
            new System.Data.OleDb.OleDbParameter("hmd201_introtext", System.Data.OleDb.OleDbType.LongVarWChar, 0, "hmd201_introtext"),
            new System.Data.OleDb.OleDbParameter("hmd201_serviceexp", System.Data.OleDb.OleDbType.LongVarWChar, 0, "hmd201_serviceexp"),
            new System.Data.OleDb.OleDbParameter("hmd201_lvid", System.Data.OleDb.OleDbType.WChar, 0, "hmd201_lvid"),
            new System.Data.OleDb.OleDbParameter("hmd201_status", System.Data.OleDb.OleDbType.WChar, 0, "hmd201_status"),
            new System.Data.OleDb.OleDbParameter("hmd201_workday", System.Data.OleDb.OleDbType.WChar, 0, "hmd201_workday"),
            new System.Data.OleDb.OleDbParameter("hmd201_lappdt", System.Data.OleDb.OleDbType.DBTimeStamp, 0, "hmd201_lappdt"),
            new System.Data.OleDb.OleDbParameter("hmd201_creatway", System.Data.OleDb.OleDbType.WChar, 0, "hmd201_creatway"),
            new System.Data.OleDb.OleDbParameter("hmd201_photo", System.Data.OleDb.OleDbType.LongVarBinary, 0, "hmd201_photo"),
            new System.Data.OleDb.OleDbParameter("hmd201_filetype", System.Data.OleDb.OleDbType.VarWChar, 0, "hmd201_filetype"),
            new System.Data.OleDb.OleDbParameter("hmd201_enCodeID", System.Data.OleDb.OleDbType.VarWChar, 0, "hmd201_enCodeID"),
            new System.Data.OleDb.OleDbParameter("hmd201_Forum_id", System.Data.OleDb.OleDbType.Integer, 0, "hmd201_Forum_id"),
            new System.Data.OleDb.OleDbParameter("hmd201_aid", System.Data.OleDb.OleDbType.VarWChar, 0, "hmd201_aid"),
            new System.Data.OleDb.OleDbParameter("hmd201_adt", System.Data.OleDb.OleDbType.DBTimeStamp, 0, "hmd201_adt"),
            new System.Data.OleDb.OleDbParameter("hmd201_uid", System.Data.OleDb.OleDbType.VarWChar, 0, "hmd201_uid"),
            new System.Data.OleDb.OleDbParameter("hmd201_udt", System.Data.OleDb.OleDbType.DBTimeStamp, 0, "hmd201_udt")});
		// 
		// oleDbSelectCommand
		// 
		this.oleDbSelectCommand.CommandText = "SELECT * FROM [hmd201] WHERE (1=1) ";
		this.oleDbSelectCommand.Connection = this.cn_DB;
		// 
		// oleDbUpdateCommand
		// 
		this.oleDbUpdateCommand.CommandText = "UPDATE [hmd201] SET [hmd201_vid] = ?, [hmd201_id] = ?, [hmd201_cname] = ?, [hmd201_ename] = ?, [hmd201_gent] = ?, [hmd201_bday] = ?, [hmd201_SSN] = ?, [hmd201_eduid] = ?, [hmd201_jobid] = ?, [hmd201_joborg] = ?, [hmd201_jobtitle] = ?, [hmd201_addid] = ?, [hmd201_addot] = ?, [hmd201_email] = ?, [hmd201_phnow] = ?, [hmd201_phnowex] = ?, [hmd201_phnoa] = ?, [hmd201_phnom] = ?, [hmd201_memberid] = ?, [hmd201_memberpwd] = ?, [hmd201_passed] = ?, [hmd201_rejectepaper] = ?, [hmd201_ps] = ?, [hmd201_notel] = ?, [hmd201_expert] = ?, [hmd201_tid] = ?, [hmd201_marriage] = ?, [hmd201_children] = ?, [hmd201_account] = ?, [hmd201_pwd] = ?, [hmd201_ssntype] = ?, [hmd201_bookid] = ?, [hmd201_weburl] = ?, [hmd201_introtext] = ?, [hmd201_serviceexp] = ?, [hmd201_lvid] = ?, [hmd201_status] = ?, [hmd201_workday] = ?, [hmd201_lappdt] = ?, [hmd201_creatway] = ?, [hmd201_photo] = ?, [hmd201_filetype] = ?, [hmd201_enCodeID] = ?, [hmd201_Forum_id] = ?, [hmd201_aid] = ?, [hmd201_adt] = ?, [hmd201_uid] = ?, [hmd201_udt] = ? WHERE (([hmd201_vid] = ?))";
		this.oleDbUpdateCommand.Connection = this.cn_DB;
		this.oleDbUpdateCommand.Parameters.AddRange(new System.Data.OleDb.OleDbParameter[] {
            new System.Data.OleDb.OleDbParameter("hmd201_vid", System.Data.OleDb.OleDbType.VarWChar, 0, "hmd201_vid"),
            new System.Data.OleDb.OleDbParameter("hmd201_id", System.Data.OleDb.OleDbType.VarWChar, 0, "hmd201_id"),
            new System.Data.OleDb.OleDbParameter("hmd201_cname", System.Data.OleDb.OleDbType.VarWChar, 0, "hmd201_cname"),
            new System.Data.OleDb.OleDbParameter("hmd201_ename", System.Data.OleDb.OleDbType.VarWChar, 0, "hmd201_ename"),
            new System.Data.OleDb.OleDbParameter("hmd201_gent", System.Data.OleDb.OleDbType.WChar, 0, "hmd201_gent"),
            new System.Data.OleDb.OleDbParameter("hmd201_bday", System.Data.OleDb.OleDbType.DBTimeStamp, 0, "hmd201_bday"),
            new System.Data.OleDb.OleDbParameter("hmd201_SSN", System.Data.OleDb.OleDbType.VarWChar, 0, "hmd201_SSN"),
            new System.Data.OleDb.OleDbParameter("hmd201_eduid", System.Data.OleDb.OleDbType.WChar, 0, "hmd201_eduid"),
            new System.Data.OleDb.OleDbParameter("hmd201_jobid", System.Data.OleDb.OleDbType.WChar, 0, "hmd201_jobid"),
            new System.Data.OleDb.OleDbParameter("hmd201_joborg", System.Data.OleDb.OleDbType.VarWChar, 0, "hmd201_joborg"),
            new System.Data.OleDb.OleDbParameter("hmd201_jobtitle", System.Data.OleDb.OleDbType.VarWChar, 0, "hmd201_jobtitle"),
            new System.Data.OleDb.OleDbParameter("hmd201_addid", System.Data.OleDb.OleDbType.WChar, 0, "hmd201_addid"),
            new System.Data.OleDb.OleDbParameter("hmd201_addot", System.Data.OleDb.OleDbType.VarWChar, 0, "hmd201_addot"),
            new System.Data.OleDb.OleDbParameter("hmd201_email", System.Data.OleDb.OleDbType.VarWChar, 0, "hmd201_email"),
            new System.Data.OleDb.OleDbParameter("hmd201_phnow", System.Data.OleDb.OleDbType.WChar, 0, "hmd201_phnow"),
            new System.Data.OleDb.OleDbParameter("hmd201_phnowex", System.Data.OleDb.OleDbType.WChar, 0, "hmd201_phnowex"),
            new System.Data.OleDb.OleDbParameter("hmd201_phnoa", System.Data.OleDb.OleDbType.WChar, 0, "hmd201_phnoa"),
            new System.Data.OleDb.OleDbParameter("hmd201_phnom", System.Data.OleDb.OleDbType.WChar, 0, "hmd201_phnom"),
            new System.Data.OleDb.OleDbParameter("hmd201_memberid", System.Data.OleDb.OleDbType.VarWChar, 0, "hmd201_memberid"),
            new System.Data.OleDb.OleDbParameter("hmd201_memberpwd", System.Data.OleDb.OleDbType.VarWChar, 0, "hmd201_memberpwd"),
            new System.Data.OleDb.OleDbParameter("hmd201_passed", System.Data.OleDb.OleDbType.WChar, 0, "hmd201_passed"),
            new System.Data.OleDb.OleDbParameter("hmd201_rejectepaper", System.Data.OleDb.OleDbType.WChar, 0, "hmd201_rejectepaper"),
            new System.Data.OleDb.OleDbParameter("hmd201_ps", System.Data.OleDb.OleDbType.LongVarWChar, 0, "hmd201_ps"),
            new System.Data.OleDb.OleDbParameter("hmd201_notel", System.Data.OleDb.OleDbType.LongVarWChar, 0, "hmd201_notel"),
            new System.Data.OleDb.OleDbParameter("hmd201_expert", System.Data.OleDb.OleDbType.LongVarWChar, 0, "hmd201_expert"),
            new System.Data.OleDb.OleDbParameter("hmd201_tid", System.Data.OleDb.OleDbType.VarWChar, 0, "hmd201_tid"),
            new System.Data.OleDb.OleDbParameter("hmd201_marriage", System.Data.OleDb.OleDbType.WChar, 0, "hmd201_marriage"),
            new System.Data.OleDb.OleDbParameter("hmd201_children", System.Data.OleDb.OleDbType.SmallInt, 0, "hmd201_children"),
            new System.Data.OleDb.OleDbParameter("hmd201_account", System.Data.OleDb.OleDbType.WChar, 0, "hmd201_account"),
            new System.Data.OleDb.OleDbParameter("hmd201_pwd", System.Data.OleDb.OleDbType.WChar, 0, "hmd201_pwd"),
            new System.Data.OleDb.OleDbParameter("hmd201_ssntype", System.Data.OleDb.OleDbType.WChar, 0, "hmd201_ssntype"),
            new System.Data.OleDb.OleDbParameter("hmd201_bookid", System.Data.OleDb.OleDbType.VarWChar, 0, "hmd201_bookid"),
            new System.Data.OleDb.OleDbParameter("hmd201_weburl", System.Data.OleDb.OleDbType.VarWChar, 0, "hmd201_weburl"),
            new System.Data.OleDb.OleDbParameter("hmd201_introtext", System.Data.OleDb.OleDbType.LongVarWChar, 0, "hmd201_introtext"),
            new System.Data.OleDb.OleDbParameter("hmd201_serviceexp", System.Data.OleDb.OleDbType.LongVarWChar, 0, "hmd201_serviceexp"),
            new System.Data.OleDb.OleDbParameter("hmd201_lvid", System.Data.OleDb.OleDbType.WChar, 0, "hmd201_lvid"),
            new System.Data.OleDb.OleDbParameter("hmd201_status", System.Data.OleDb.OleDbType.WChar, 0, "hmd201_status"),
            new System.Data.OleDb.OleDbParameter("hmd201_workday", System.Data.OleDb.OleDbType.WChar, 0, "hmd201_workday"),
            new System.Data.OleDb.OleDbParameter("hmd201_lappdt", System.Data.OleDb.OleDbType.DBTimeStamp, 0, "hmd201_lappdt"),
            new System.Data.OleDb.OleDbParameter("hmd201_creatway", System.Data.OleDb.OleDbType.WChar, 0, "hmd201_creatway"),
            new System.Data.OleDb.OleDbParameter("hmd201_photo", System.Data.OleDb.OleDbType.LongVarBinary, 0, "hmd201_photo"),
            new System.Data.OleDb.OleDbParameter("hmd201_filetype", System.Data.OleDb.OleDbType.VarWChar, 0, "hmd201_filetype"),
            new System.Data.OleDb.OleDbParameter("hmd201_enCodeID", System.Data.OleDb.OleDbType.VarWChar, 0, "hmd201_enCodeID"),
            new System.Data.OleDb.OleDbParameter("hmd201_Forum_id", System.Data.OleDb.OleDbType.Integer, 0, "hmd201_Forum_id"),
            new System.Data.OleDb.OleDbParameter("hmd201_aid", System.Data.OleDb.OleDbType.VarWChar, 0, "hmd201_aid"),
            new System.Data.OleDb.OleDbParameter("hmd201_adt", System.Data.OleDb.OleDbType.DBTimeStamp, 0, "hmd201_adt"),
            new System.Data.OleDb.OleDbParameter("hmd201_uid", System.Data.OleDb.OleDbType.VarWChar, 0, "hmd201_uid"),
            new System.Data.OleDb.OleDbParameter("hmd201_udt", System.Data.OleDb.OleDbType.DBTimeStamp, 0, "hmd201_udt"),
            new System.Data.OleDb.OleDbParameter("Original_hmd201_vid", System.Data.OleDb.OleDbType.VarWChar, 0, System.Data.ParameterDirection.Input, false, ((byte)(0)), ((byte)(0)), "hmd201_vid", System.Data.DataRowVersion.Original, null)});
		((System.ComponentModel.ISupportInitialize)(this.ds_Data)).EndInit();
		((System.ComponentModel.ISupportInitialize)(this.dv_View)).EndInit();

	}
	#endregion

	// =========================================================================
	/// <summary>
	/// 函式描述：自訂初始化函式（覆蓋上層）
	/// </summary>
	protected override void uf_InitializeComponent()
	{
		// 先將 DataSet 宣告為指定的結構再初始化
		this.ds_Data = new d_hmd201();
		this.uf_Initialize();
	}
}
