// *********************************************************************************
// 1. 程式描述：hmd100a資料元件–無傳入值
// 2. 撰寫人員：generated by WITSTER  0.2.2 beta (by QFLin)
// *********************************************************************************
using System;
using System.ComponentModel;
using System.Collections;
using System.Diagnostics;

/// <summary>
/// hmd100a資料元件–無傳入值
/// </summary>
public class ndb_hmd100a : WIT.Template.Project.n_dbbase
{
	private System.Data.OleDb.OleDbCommand oleDbDeleteCommand;
	private System.Data.OleDb.OleDbCommand oleDbInsertCommand;
	private System.Data.OleDb.OleDbCommand oleDbSelectCommand;
	private System.Data.OleDb.OleDbCommand oleDbUpdateCommand;
	private System.Data.OleDb.OleDbDataAdapter da_SQL_current;
	
	public ndb_hmd100a(System.ComponentModel.IContainer container)
	{
		container.Add(this);
		InitializeComponent();
		// 將資料配接器設為 current
		da_SQL = da_SQL_current;
	}

	public ndb_hmd100a()
	{
		InitializeComponent();
		// 將資料配接器設為 current
		da_SQL = da_SQL_current;
	}

	#region Component Designer generated code
	
	/// <summary>
	/// 此為設計工具支援所必需的方法 - 請勿使用程式碼編輯器修改
	/// 這個方法的內容。
	/// </summary>
	private void InitializeComponent()
	{
		this.da_SQL_current = new System.Data.OleDb.OleDbDataAdapter();
		this.oleDbDeleteCommand = new System.Data.OleDb.OleDbCommand();
		this.oleDbInsertCommand = new System.Data.OleDb.OleDbCommand();
		this.oleDbSelectCommand = new System.Data.OleDb.OleDbCommand();
		this.oleDbUpdateCommand = new System.Data.OleDb.OleDbCommand();
		
		((System.ComponentModel.ISupportInitialize)(this.ds_Data)).BeginInit();
		((System.ComponentModel.ISupportInitialize)(this.dv_View)).BeginInit();

		// 
		// 容器
		// 
		this.da_SQL_current.TableMappings.AddRange(new System.Data.Common.DataTableMapping[] {
			
                                           new System.Data.Common.DataTableMapping("Table", "hmd100a", new System.Data.Common.DataColumnMapping[] {
                                           new System.Data.Common.DataColumnMapping("hmd100a_posid", "hmd100a_posid"),
                                           new System.Data.Common.DataColumnMapping("hmd100a_posname", "hmd100a_posname"),
                                           new System.Data.Common.DataColumnMapping("hmd100a_belon", "hmd100a_belon"),
                                           new System.Data.Common.DataColumnMapping("hmd100a_poslvtype", "hmd100a_poslvtype"),
                                           new System.Data.Common.DataColumnMapping("hmd100a_poslv", "hmd100a_poslv"),
                                           new System.Data.Common.DataColumnMapping("hmd100a_posno", "hmd100a_posno"),
                                           new System.Data.Common.DataColumnMapping("hmd100a_stop", "hmd100a_stop"),
                                           new System.Data.Common.DataColumnMapping("hmd100a_aid", "hmd100a_aid"),
                                           new System.Data.Common.DataColumnMapping("hmd100a_adt", "hmd100a_adt"),
                                           new System.Data.Common.DataColumnMapping("hmd100a_uid", "hmd100a_uid"),
                                           new System.Data.Common.DataColumnMapping("hmd100a_udt", "hmd100a_udt")
                                           })
            });
                                           
		// 
		// 刪除命令
		// 
		this.da_SQL_current.DeleteCommand = this.oleDbDeleteCommand;
		this.oleDbDeleteCommand.CommandText = "DELETE FROM [hmd100a] WHERE (([hmd100a_posid] = ?)) ";
		this.oleDbDeleteCommand.Connection = this.cn_DB;
		this.oleDbDeleteCommand.Parameters.AddRange(new System.Data.OleDb.OleDbParameter[] {
		                                                           new System.Data.OleDb.OleDbParameter("Original_hmd100a_posid", System.Data.OleDb.OleDbType.VarChar, 0, System.Data.ParameterDirection.Input, false, ((byte)(20)), ((byte)(0)), "hmd100a_posid", System.Data.DataRowVersion.Original, null)
		});


		// 
		// 新增區
		// 
		this.da_SQL_current.InsertCommand = this.oleDbInsertCommand;
		this.oleDbInsertCommand.CommandText = "INSERT INTO [hmd100a] ([hmd100a_posid],[hmd100a_posname],[hmd100a_belon],[hmd100a_poslvtype],[hmd100a_poslv],[hmd100a_posno],[hmd100a_stop],[hmd100a_aid],[hmd100a_adt],[hmd100a_uid],[hmd100a_udt]) VALUES (?,?,?,?,?,?,?,?,?,?,?)";
		this.oleDbInsertCommand.Connection = this.cn_DB;
		this.oleDbInsertCommand.Parameters.AddRange(new System.Data.OleDb.OleDbParameter[] {
		                                                           new System.Data.OleDb.OleDbParameter("hmd100a_posid", System.Data.OleDb.OleDbType.VarChar, 0, "hmd100a_posid"),
                                                     new System.Data.OleDb.OleDbParameter("hmd100a_posname", System.Data.OleDb.OleDbType.VarChar, 0, "hmd100a_posname"),
                                                     new System.Data.OleDb.OleDbParameter("hmd100a_belon", System.Data.OleDb.OleDbType.Char, 0, "hmd100a_belon"),
                                                     new System.Data.OleDb.OleDbParameter("hmd100a_poslvtype", System.Data.OleDb.OleDbType.Char, 0, "hmd100a_poslvtype"),
                                                     new System.Data.OleDb.OleDbParameter("hmd100a_poslv", System.Data.OleDb.OleDbType.VarChar, 0, "hmd100a_poslv"),
                                                     new System.Data.OleDb.OleDbParameter("hmd100a_posno", System.Data.OleDb.OleDbType.SmallInt, 0, "hmd100a_posno"),
                                                     new System.Data.OleDb.OleDbParameter("hmd100a_stop", System.Data.OleDb.OleDbType.Char, 0, "hmd100a_stop"),
                                                     new System.Data.OleDb.OleDbParameter("hmd100a_aid", System.Data.OleDb.OleDbType.VarChar, 0, "hmd100a_aid"),
                                                     new System.Data.OleDb.OleDbParameter("hmd100a_adt", System.Data.OleDb.OleDbType.DBTimeStamp, 0, "hmd100a_adt"),
                                                     new System.Data.OleDb.OleDbParameter("hmd100a_uid", System.Data.OleDb.OleDbType.VarChar, 0, "hmd100a_uid"),
                                                     new System.Data.OleDb.OleDbParameter("hmd100a_udt", System.Data.OleDb.OleDbType.DBTimeStamp, 0, "hmd100a_udt")
		});


		// 
		// 查詢區
		// 
		this.da_SQL_current.SelectCommand = this.oleDbSelectCommand;				this.oleDbSelectCommand.CommandText = "SELECT * FROM [hmd100a] WHERE (1=1) ";		this.oleDbSelectCommand.Connection = this.cn_DB;

		// 
		// 更新區
		// 
		this.da_SQL_current.UpdateCommand = this.oleDbUpdateCommand;
		this.oleDbUpdateCommand.CommandText = "UPDATE [hmd100a] SET  [hmd100a_posid] = ?, [hmd100a_posname] = ?, [hmd100a_belon] = ?, [hmd100a_poslvtype] = ?, [hmd100a_poslv] = ?, [hmd100a_posno] = ?, [hmd100a_stop] = ?, [hmd100a_aid] = ?, [hmd100a_adt] = ?, [hmd100a_uid] = ?, [hmd100a_udt] = ?  WHERE (([hmd100a_posid] = ?))";
		this.oleDbUpdateCommand.Connection = this.cn_DB;
		this.oleDbUpdateCommand.Parameters.AddRange(new System.Data.OleDb.OleDbParameter[] {
		                                                           new System.Data.OleDb.OleDbParameter("hmd100a_posid", System.Data.OleDb.OleDbType.VarChar, 0, "hmd100a_posid"),
                                                     new System.Data.OleDb.OleDbParameter("hmd100a_posname", System.Data.OleDb.OleDbType.VarChar, 0, "hmd100a_posname"),
                                                     new System.Data.OleDb.OleDbParameter("hmd100a_belon", System.Data.OleDb.OleDbType.Char, 0, "hmd100a_belon"),
                                                     new System.Data.OleDb.OleDbParameter("hmd100a_poslvtype", System.Data.OleDb.OleDbType.Char, 0, "hmd100a_poslvtype"),
                                                     new System.Data.OleDb.OleDbParameter("hmd100a_poslv", System.Data.OleDb.OleDbType.VarChar, 0, "hmd100a_poslv"),
                                                     new System.Data.OleDb.OleDbParameter("hmd100a_posno", System.Data.OleDb.OleDbType.SmallInt, 0, "hmd100a_posno"),
                                                     new System.Data.OleDb.OleDbParameter("hmd100a_stop", System.Data.OleDb.OleDbType.Char, 0, "hmd100a_stop"),
                                                     new System.Data.OleDb.OleDbParameter("hmd100a_aid", System.Data.OleDb.OleDbType.VarChar, 0, "hmd100a_aid"),
                                                     new System.Data.OleDb.OleDbParameter("hmd100a_adt", System.Data.OleDb.OleDbType.DBTimeStamp, 0, "hmd100a_adt"),
                                                     new System.Data.OleDb.OleDbParameter("hmd100a_uid", System.Data.OleDb.OleDbType.VarChar, 0, "hmd100a_uid"),
                                                     new System.Data.OleDb.OleDbParameter("hmd100a_udt", System.Data.OleDb.OleDbType.DBTimeStamp, 0, "hmd100a_udt"),
                                                     new System.Data.OleDb.OleDbParameter("Original_hmd100a_posid", System.Data.OleDb.OleDbType.VarChar, 0, System.Data.ParameterDirection.Input, false, ((byte)(20)), ((byte)(0)), "hmd100a_posid", System.Data.DataRowVersion.Original, null)                                                });

		((System.ComponentModel.ISupportInitialize)(this.ds_Data)).EndInit();
		((System.ComponentModel.ISupportInitialize)(this.dv_View)).EndInit();


	}
	#endregion

	// =========================================================================
	/// <summary>
	/// 函式描述：自訂初始化函式（覆蓋上層）
	/// </summary>
	protected override void uf_InitializeComponent()
	{
		// 先將 DataSet 宣告為指定的結構再初始化
		this.ds_Data = new d_hmd100a();
		this.uf_Initialize();
	}
}
