// *********************************************************************************
// 1. 程式描述：htemp01資料元件–無傳入值
// 2. 撰寫人員：generated by WITSTER  0.2.2 beta (by QFLin)
// *********************************************************************************
using System;
using System.ComponentModel;
using System.Collections;
using System.Diagnostics;

/// <summary>
/// htemp01資料元件–無傳入值
/// </summary>
public class ndb_htemp01 : WIT.Template.Project.n_dbbase
{
	private System.Data.OleDb.OleDbCommand oleDbDeleteCommand;
	private System.Data.OleDb.OleDbCommand oleDbInsertCommand;
	private System.Data.OleDb.OleDbCommand oleDbSelectCommand;
	private System.Data.OleDb.OleDbCommand oleDbUpdateCommand;
	private System.Data.OleDb.OleDbDataAdapter da_SQL_current;
	
	public ndb_htemp01(System.ComponentModel.IContainer container)
	{
		container.Add(this);
		InitializeComponent();
		// 將資料配接器設為 current
		da_SQL = da_SQL_current;
	}

	public ndb_htemp01()
	{
		InitializeComponent();
		// 將資料配接器設為 current
		da_SQL = da_SQL_current;
	}

	#region Component Designer generated code
	
	/// <summary>
	/// 此為設計工具支援所必需的方法 - 請勿使用程式碼編輯器修改
	/// 這個方法的內容。
	/// </summary>
	private void InitializeComponent()
	{
		this.da_SQL_current = new System.Data.OleDb.OleDbDataAdapter();
		this.oleDbDeleteCommand = new System.Data.OleDb.OleDbCommand();
		this.oleDbInsertCommand = new System.Data.OleDb.OleDbCommand();
		this.oleDbSelectCommand = new System.Data.OleDb.OleDbCommand();
		this.oleDbUpdateCommand = new System.Data.OleDb.OleDbCommand();
		
		((System.ComponentModel.ISupportInitialize)(this.ds_Data)).BeginInit();
		((System.ComponentModel.ISupportInitialize)(this.dv_View)).BeginInit();

		// 
		// 容器
		// 
		this.da_SQL_current.TableMappings.AddRange(new System.Data.Common.DataTableMapping[] {
			
                                           new System.Data.Common.DataTableMapping("Table", "htemp01", new System.Data.Common.DataColumnMapping[] {
                                           new System.Data.Common.DataColumnMapping("VID", "VID"),
                                           new System.Data.Common.DataColumnMapping("LID1", "LID1"),
                                           new System.Data.Common.DataColumnMapping("LID2", "LID2"),
                                           new System.Data.Common.DataColumnMapping("ST1", "ST1"),
                                           new System.Data.Common.DataColumnMapping("ST2", "ST2"),
                                           new System.Data.Common.DataColumnMapping("hours", "hours"),
                                           new System.Data.Common.DataColumnMapping("PS", "PS")
                                           })
            });
                                           
		// 
		// 刪除命令
		// 


		// 
		// 新增區
		// 
		this.da_SQL_current.InsertCommand = this.oleDbInsertCommand;
		this.oleDbInsertCommand.CommandText = "INSERT INTO [htemp01] ([VID],[LID1],[LID2],[ST1],[ST2],[hours],[PS]) VALUES (?,?,?,?,?,?,?)";
		this.oleDbInsertCommand.Connection = this.cn_DB;
		this.oleDbInsertCommand.Parameters.AddRange(new System.Data.OleDb.OleDbParameter[] {
		                                                           new System.Data.OleDb.OleDbParameter("VID", System.Data.OleDb.OleDbType.VarChar, 0, "VID"),
                                                     new System.Data.OleDb.OleDbParameter("LID1", System.Data.OleDb.OleDbType.VarChar, 0, "LID1"),
                                                     new System.Data.OleDb.OleDbParameter("LID2", System.Data.OleDb.OleDbType.VarChar, 0, "LID2"),
                                                     new System.Data.OleDb.OleDbParameter("ST1", System.Data.OleDb.OleDbType.DBTimeStamp, 0, "ST1"),
                                                     new System.Data.OleDb.OleDbParameter("ST2", System.Data.OleDb.OleDbType.DBTimeStamp, 0, "ST2"),
                                                     new System.Data.OleDb.OleDbParameter("hours", System.Data.OleDb.OleDbType.Double, 0, "hours"),
                                                     new System.Data.OleDb.OleDbParameter("PS", System.Data.OleDb.OleDbType.VarChar, 0, "PS")
		});


		// 
		// 查詢區
		// 
		this.da_SQL_current.SelectCommand = this.oleDbSelectCommand;				this.oleDbSelectCommand.CommandText = "SELECT * FROM [htemp01] WHERE (1=1) ";		this.oleDbSelectCommand.Connection = this.cn_DB;

		// 
		// 更新區
		// 


	}
	#endregion

	// =========================================================================
	/// <summary>
	/// 函式描述：自訂初始化函式（覆蓋上層）
	/// </summary>
	protected override void uf_InitializeComponent()
	{
		// 先將 DataSet 宣告為指定的結構再初始化
		this.ds_Data = new d_htemp01();
		this.uf_Initialize();
	}
}
