// *********************************************************************************
// 1. 程式描述：hlg203資料元件–無傳入值
// 2. 撰寫人員：generated by WITSTER  0.2.2 beta (by QFLin)
// *********************************************************************************
using System;
using System.ComponentModel;
using System.Collections;
using System.Diagnostics;

/// <summary>
/// hlg203資料元件–無傳入值
/// </summary>
public class ndb_hlg203 : WIT.Template.Project.n_dbbase
{
	private System.Data.OleDb.OleDbCommand oleDbDeleteCommand;
	private System.Data.OleDb.OleDbCommand oleDbInsertCommand;
	private System.Data.OleDb.OleDbCommand oleDbSelectCommand;
	private System.Data.OleDb.OleDbCommand oleDbUpdateCommand;
	private System.Data.OleDb.OleDbDataAdapter da_SQL_current;
	
	public ndb_hlg203(System.ComponentModel.IContainer container)
	{
		container.Add(this);
		InitializeComponent();
		this.uf_InitializeCommand();
		// 將資料配接器設為 current
		da_SQL = da_SQL_current;
	}

	public ndb_hlg203()
	{
		InitializeComponent();
		this.uf_InitializeCommand();
		// 將資料配接器設為 current
		da_SQL = da_SQL_current;
	}

	#region Component Designer generated code
	
	/// <summary>
	/// 此為設計工具支援所必需的方法 - 請勿使用程式碼編輯器修改
	/// 這個方法的內容。
	/// </summary>
	private void InitializeComponent()
	{
		System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(ndb_hlg203));
		this.da_SQL_current = new System.Data.OleDb.OleDbDataAdapter();
		this.oleDbDeleteCommand = new System.Data.OleDb.OleDbCommand();
		this.oleDbInsertCommand = new System.Data.OleDb.OleDbCommand();
		this.oleDbSelectCommand = new System.Data.OleDb.OleDbCommand();
		this.oleDbUpdateCommand = new System.Data.OleDb.OleDbCommand();
		((System.ComponentModel.ISupportInitialize)(this.ds_Data)).BeginInit();
		((System.ComponentModel.ISupportInitialize)(this.dv_View)).BeginInit();
		// 
		// da_SQL_current
		// 
		this.da_SQL_current.DeleteCommand = this.oleDbDeleteCommand;
		this.da_SQL_current.InsertCommand = this.oleDbInsertCommand;
		this.da_SQL_current.SelectCommand = this.oleDbSelectCommand;
		this.da_SQL_current.TableMappings.AddRange(new System.Data.Common.DataTableMapping[] {
            new System.Data.Common.DataTableMapping("Table", "hlg203", new System.Data.Common.DataColumnMapping[] {
                        new System.Data.Common.DataColumnMapping("hlg203_kid", "hlg203_kid"),
                        new System.Data.Common.DataColumnMapping("hlg203_vid", "hlg203_vid"),
                        new System.Data.Common.DataColumnMapping("hlg203_metalname", "hlg203_metalname"),
                        new System.Data.Common.DataColumnMapping("hlg203_mdate", "hlg203_mdate"),
                        new System.Data.Common.DataColumnMapping("hlg203_appno", "hlg203_appno"),
                        new System.Data.Common.DataColumnMapping("hlg203_app_date", "hlg203_app_date"),
                        new System.Data.Common.DataColumnMapping("hlg203_aid", "hlg203_aid"),
                        new System.Data.Common.DataColumnMapping("hlg203_adt", "hlg203_adt"),
                        new System.Data.Common.DataColumnMapping("hlg203_uid", "hlg203_uid"),
                        new System.Data.Common.DataColumnMapping("hlg203_udt", "hlg203_udt")})});
		this.da_SQL_current.UpdateCommand = this.oleDbUpdateCommand;
		// 
		// oleDbDeleteCommand
		// 
		this.oleDbDeleteCommand.CommandText = "DELETE FROM [hlg203] WHERE (([hlg203_kid] = ?))";
		this.oleDbDeleteCommand.Connection = this.cn_DB;
		this.oleDbDeleteCommand.Parameters.AddRange(new System.Data.OleDb.OleDbParameter[] {
            new System.Data.OleDb.OleDbParameter("Original_hlg203_kid", System.Data.OleDb.OleDbType.Numeric, 0, System.Data.ParameterDirection.Input, false, ((byte)(18)), ((byte)(0)), "hlg203_kid", System.Data.DataRowVersion.Original, null)});
		// 
		// oleDbInsertCommand
		// 
		this.oleDbInsertCommand.CommandText = "INSERT INTO [hlg203] ([hlg203_vid], [hlg203_metalname], [hlg203_mdate], [hlg203_a" +
			"ppno], [hlg203_app_date], [hlg203_aid], [hlg203_adt], [hlg203_uid], [hlg203_udt]" +
			") VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";
		this.oleDbInsertCommand.Connection = this.cn_DB;
		this.oleDbInsertCommand.Parameters.AddRange(new System.Data.OleDb.OleDbParameter[] {
            new System.Data.OleDb.OleDbParameter("hlg203_vid", System.Data.OleDb.OleDbType.VarWChar, 0, "hlg203_vid"),
            new System.Data.OleDb.OleDbParameter("hlg203_metalname", System.Data.OleDb.OleDbType.VarWChar, 0, "hlg203_metalname"),
            new System.Data.OleDb.OleDbParameter("hlg203_mdate", System.Data.OleDb.OleDbType.DBTimeStamp, 0, "hlg203_mdate"),
            new System.Data.OleDb.OleDbParameter("hlg203_appno", System.Data.OleDb.OleDbType.VarWChar, 0, "hlg203_appno"),
            new System.Data.OleDb.OleDbParameter("hlg203_app_date", System.Data.OleDb.OleDbType.DBTimeStamp, 0, "hlg203_app_date"),
            new System.Data.OleDb.OleDbParameter("hlg203_aid", System.Data.OleDb.OleDbType.VarWChar, 0, "hlg203_aid"),
            new System.Data.OleDb.OleDbParameter("hlg203_adt", System.Data.OleDb.OleDbType.DBTimeStamp, 0, "hlg203_adt"),
            new System.Data.OleDb.OleDbParameter("hlg203_uid", System.Data.OleDb.OleDbType.VarWChar, 0, "hlg203_uid"),
            new System.Data.OleDb.OleDbParameter("hlg203_udt", System.Data.OleDb.OleDbType.DBTimeStamp, 0, "hlg203_udt")});
		// 
		// oleDbSelectCommand
		// 
		this.oleDbSelectCommand.CommandText = "SELECT * FROM [hlg203] WHERE (1=1) ";
		this.oleDbSelectCommand.Connection = this.cn_DB;
		// 
		// oleDbUpdateCommand
		// 
		this.oleDbUpdateCommand.CommandText = "UPDATE [hlg203] SET [hlg203_vid] = ?, [hlg203_metalname] = ?, [hlg203_mdate] = ?, [hlg203_appno] = ?, [hlg203_app_date] = ?, [hlg203_aid] = ?, [hlg203_adt] = ?, [hlg203_uid] = ?, [hlg203_udt] = ? WHERE (([hlg203_kid] = ?))";
		this.oleDbUpdateCommand.Connection = this.cn_DB;
		this.oleDbUpdateCommand.Parameters.AddRange(new System.Data.OleDb.OleDbParameter[] {
            new System.Data.OleDb.OleDbParameter("hlg203_vid", System.Data.OleDb.OleDbType.VarWChar, 0, "hlg203_vid"),
            new System.Data.OleDb.OleDbParameter("hlg203_metalname", System.Data.OleDb.OleDbType.VarWChar, 0, "hlg203_metalname"),
            new System.Data.OleDb.OleDbParameter("hlg203_mdate", System.Data.OleDb.OleDbType.DBTimeStamp, 0, "hlg203_mdate"),
            new System.Data.OleDb.OleDbParameter("hlg203_appno", System.Data.OleDb.OleDbType.VarWChar, 0, "hlg203_appno"),
            new System.Data.OleDb.OleDbParameter("hlg203_app_date", System.Data.OleDb.OleDbType.DBTimeStamp, 0, "hlg203_app_date"),
            new System.Data.OleDb.OleDbParameter("hlg203_aid", System.Data.OleDb.OleDbType.VarWChar, 0, "hlg203_aid"),
            new System.Data.OleDb.OleDbParameter("hlg203_adt", System.Data.OleDb.OleDbType.DBTimeStamp, 0, "hlg203_adt"),
            new System.Data.OleDb.OleDbParameter("hlg203_uid", System.Data.OleDb.OleDbType.VarWChar, 0, "hlg203_uid"),
            new System.Data.OleDb.OleDbParameter("hlg203_udt", System.Data.OleDb.OleDbType.DBTimeStamp, 0, "hlg203_udt"),
            new System.Data.OleDb.OleDbParameter("Original_hlg203_kid", System.Data.OleDb.OleDbType.Numeric, 0, System.Data.ParameterDirection.Input, false, ((byte)(18)), ((byte)(0)), "hlg203_kid", System.Data.DataRowVersion.Original, null)});
		((System.ComponentModel.ISupportInitialize)(this.ds_Data)).EndInit();
		((System.ComponentModel.ISupportInitialize)(this.dv_View)).EndInit();

	}
	#endregion

	// =========================================================================
	/// <summary>
	/// 函式描述：自訂初始化函式（覆蓋上層）
	/// </summary>
	protected override void uf_InitializeComponent()
	{
		// 先將 DataSet 宣告為指定的結構再初始化
		this.ds_Data = new d_hlg203();
		this.uf_Initialize();
	}

	// =========================================================================
	/// <summary>
	/// 函式描述：初始化 Command 物件函式
	/// </summary>
	private void uf_InitializeCommand()
	{
		// 替 Insert 語法增加取回 IDENTITY 值的語法
		this.oleDbInsertCommand.CommandText += ";SELECT ? = @@IDENTITY";

		// 替 Insert 語法增加回值參數
		System.Data.OleDb.OleDbParameter myParm = this.oleDbInsertCommand.Parameters.Add("@Identity", System.Data.OleDb.OleDbType.Numeric, 0, "hlg203_kid");
		myParm.Direction = System.Data.ParameterDirection.Output;
	}
}
