// *********************************************************************************
// 1. 程式描述：hmh201a資料元件–無傳入值
// 2. 撰寫人員：generated by WITSTER  0.2.2 beta (by QFLin)
// *********************************************************************************
using System;
using System.ComponentModel;
using System.Collections;
using System.Diagnostics;

/// <summary>
/// hmh201a資料元件–無傳入值
/// </summary>
public class ndb_hmh201a : WIT.Template.Project.n_dbbase
{
	private System.Data.OleDb.OleDbCommand oleDbDeleteCommand;
	private System.Data.OleDb.OleDbCommand oleDbInsertCommand;
	private System.Data.OleDb.OleDbCommand oleDbSelectCommand;
	private System.Data.OleDb.OleDbCommand oleDbUpdateCommand;
	private System.Data.OleDb.OleDbDataAdapter da_SQL_current;
	
	public ndb_hmh201a(System.ComponentModel.IContainer container)
	{
		container.Add(this);
		InitializeComponent();
		// 將資料配接器設為 current
		da_SQL = da_SQL_current;
	}

	public ndb_hmh201a()
	{
		InitializeComponent();
		// 將資料配接器設為 current
		da_SQL = da_SQL_current;
	}

	#region Component Designer generated code
	
	/// <summary>
	/// 此為設計工具支援所必需的方法 - 請勿使用程式碼編輯器修改
	/// 這個方法的內容。
	/// </summary>
	private void InitializeComponent()
	{
		this.da_SQL_current = new System.Data.OleDb.OleDbDataAdapter();
		this.oleDbDeleteCommand = new System.Data.OleDb.OleDbCommand();
		this.oleDbInsertCommand = new System.Data.OleDb.OleDbCommand();
		this.oleDbSelectCommand = new System.Data.OleDb.OleDbCommand();
		this.oleDbUpdateCommand = new System.Data.OleDb.OleDbCommand();
		
		((System.ComponentModel.ISupportInitialize)(this.ds_Data)).BeginInit();
		((System.ComponentModel.ISupportInitialize)(this.dv_View)).BeginInit();

		// 
		// 容器
		// 
		this.da_SQL_current.TableMappings.AddRange(new System.Data.Common.DataTableMapping[] {
			
                                           new System.Data.Common.DataTableMapping("Table", "hmh201a", new System.Data.Common.DataColumnMapping[] {
                                           new System.Data.Common.DataColumnMapping("hmh201a_cid", "hmh201a_cid"),
                                           new System.Data.Common.DataColumnMapping("hmh201a_picurl", "hmh201a_picurl"),
                                           new System.Data.Common.DataColumnMapping("hmh201a_stitle", "hmh201a_stitle"),
                                           new System.Data.Common.DataColumnMapping("hmh201a_scontent", "hmh201a_scontent"),
                                           new System.Data.Common.DataColumnMapping("hmh201a_mlist", "hmh201a_mlist"),
                                           new System.Data.Common.DataColumnMapping("hmh201a_aid", "hmh201a_aid"),
                                           new System.Data.Common.DataColumnMapping("hmh201a_adt", "hmh201a_adt"),
                                           new System.Data.Common.DataColumnMapping("hmh201a_uid", "hmh201a_uid"),
                                           new System.Data.Common.DataColumnMapping("hmh201a_udt", "hmh201a_udt")
                                           })
            });
                                           
		// 
		// 刪除命令
		// 
		this.da_SQL_current.DeleteCommand = this.oleDbDeleteCommand;
		this.oleDbDeleteCommand.CommandText = "DELETE FROM [hmh201a] WHERE (([hmh201a_cid] = ?)) ";
		this.oleDbDeleteCommand.Connection = this.cn_DB;
		this.oleDbDeleteCommand.Parameters.AddRange(new System.Data.OleDb.OleDbParameter[] {
		                                                           new System.Data.OleDb.OleDbParameter("Original_hmh201a_cid", System.Data.OleDb.OleDbType.VarChar, 0, System.Data.ParameterDirection.Input, false, ((byte)(50)), ((byte)(0)), "hmh201a_cid", System.Data.DataRowVersion.Original, null)
		});


		// 
		// 新增區
		// 
		this.da_SQL_current.InsertCommand = this.oleDbInsertCommand;
		this.oleDbInsertCommand.CommandText = "INSERT INTO [hmh201a] ([hmh201a_cid],[hmh201a_picurl],[hmh201a_stitle],[hmh201a_scontent],[hmh201a_mlist],[hmh201a_aid],[hmh201a_adt],[hmh201a_uid],[hmh201a_udt]) VALUES (?,?,?,?,?,?,?,?,?)";
		this.oleDbInsertCommand.Connection = this.cn_DB;
		this.oleDbInsertCommand.Parameters.AddRange(new System.Data.OleDb.OleDbParameter[] {
		                                                           new System.Data.OleDb.OleDbParameter("hmh201a_cid", System.Data.OleDb.OleDbType.VarChar, 0, "hmh201a_cid"),
                                                     new System.Data.OleDb.OleDbParameter("hmh201a_picurl", System.Data.OleDb.OleDbType.VarChar, 0, "hmh201a_picurl"),
                                                     new System.Data.OleDb.OleDbParameter("hmh201a_stitle", System.Data.OleDb.OleDbType.VarChar, 0, "hmh201a_stitle"),
                                                     new System.Data.OleDb.OleDbParameter("hmh201a_scontent", System.Data.OleDb.OleDbType.VarChar, 0, "hmh201a_scontent"),
                                                     new System.Data.OleDb.OleDbParameter("hmh201a_mlist", System.Data.OleDb.OleDbType.VarChar, 0, "hmh201a_mlist"),
                                                     new System.Data.OleDb.OleDbParameter("hmh201a_aid", System.Data.OleDb.OleDbType.VarChar, 0, "hmh201a_aid"),
                                                     new System.Data.OleDb.OleDbParameter("hmh201a_adt", System.Data.OleDb.OleDbType.DBTimeStamp, 0, "hmh201a_adt"),
                                                     new System.Data.OleDb.OleDbParameter("hmh201a_uid", System.Data.OleDb.OleDbType.VarChar, 0, "hmh201a_uid"),
                                                     new System.Data.OleDb.OleDbParameter("hmh201a_udt", System.Data.OleDb.OleDbType.DBTimeStamp, 0, "hmh201a_udt")
		});


		// 
		// 查詢區
		// 
		this.da_SQL_current.SelectCommand = this.oleDbSelectCommand;				this.oleDbSelectCommand.CommandText = "SELECT * FROM [hmh201a] WHERE (1=1) ";		this.oleDbSelectCommand.Connection = this.cn_DB;

		// 
		// 更新區
		// 
		this.da_SQL_current.UpdateCommand = this.oleDbUpdateCommand;
		this.oleDbUpdateCommand.CommandText = "UPDATE [hmh201a] SET  [hmh201a_cid] = ?, [hmh201a_picurl] = ?, [hmh201a_stitle] = ?, [hmh201a_scontent] = ?, [hmh201a_mlist] = ?, [hmh201a_aid] = ?, [hmh201a_adt] = ?, [hmh201a_uid] = ?, [hmh201a_udt] = ?  WHERE (([hmh201a_cid] = ?))";
		this.oleDbUpdateCommand.Connection = this.cn_DB;
		this.oleDbUpdateCommand.Parameters.AddRange(new System.Data.OleDb.OleDbParameter[] {
		                                                           new System.Data.OleDb.OleDbParameter("hmh201a_cid", System.Data.OleDb.OleDbType.VarChar, 0, "hmh201a_cid"),
                                                     new System.Data.OleDb.OleDbParameter("hmh201a_picurl", System.Data.OleDb.OleDbType.VarChar, 0, "hmh201a_picurl"),
                                                     new System.Data.OleDb.OleDbParameter("hmh201a_stitle", System.Data.OleDb.OleDbType.VarChar, 0, "hmh201a_stitle"),
                                                     new System.Data.OleDb.OleDbParameter("hmh201a_scontent", System.Data.OleDb.OleDbType.VarChar, 0, "hmh201a_scontent"),
                                                     new System.Data.OleDb.OleDbParameter("hmh201a_mlist", System.Data.OleDb.OleDbType.VarChar, 0, "hmh201a_mlist"),
                                                     new System.Data.OleDb.OleDbParameter("hmh201a_aid", System.Data.OleDb.OleDbType.VarChar, 0, "hmh201a_aid"),
                                                     new System.Data.OleDb.OleDbParameter("hmh201a_adt", System.Data.OleDb.OleDbType.DBTimeStamp, 0, "hmh201a_adt"),
                                                     new System.Data.OleDb.OleDbParameter("hmh201a_uid", System.Data.OleDb.OleDbType.VarChar, 0, "hmh201a_uid"),
                                                     new System.Data.OleDb.OleDbParameter("hmh201a_udt", System.Data.OleDb.OleDbType.DBTimeStamp, 0, "hmh201a_udt"),
                                                     new System.Data.OleDb.OleDbParameter("Original_hmh201a_cid", System.Data.OleDb.OleDbType.VarChar, 0, System.Data.ParameterDirection.Input, false, ((byte)(50)), ((byte)(0)), "hmh201a_cid", System.Data.DataRowVersion.Original, null)                                                });

		((System.ComponentModel.ISupportInitialize)(this.ds_Data)).EndInit();
		((System.ComponentModel.ISupportInitialize)(this.dv_View)).EndInit();


	}
	#endregion

	// =========================================================================
	/// <summary>
	/// 函式描述：自訂初始化函式（覆蓋上層）
	/// </summary>
	protected override void uf_InitializeComponent()
	{
		// 先將 DataSet 宣告為指定的結構再初始化
		this.ds_Data = new d_hmh201a();
		this.uf_Initialize();
	}
}
