// *********************************************************************************
// 1. 程式描述：bld0121資料元件–無傳入值
// 2. 撰寫人員：generated by WITSTER  0.2.2 beta (by QFLin)
// *********************************************************************************
using System;
using System.ComponentModel;
using System.Collections;
using System.Diagnostics;

/// <summary>
/// bld0121資料元件–無傳入值
/// </summary>
public class ndb_bld0121 : WIT.Template.Project.n_dbbase
{
	private System.Data.OleDb.OleDbCommand oleDbDeleteCommand;
	private System.Data.OleDb.OleDbCommand oleDbInsertCommand;
	private System.Data.OleDb.OleDbCommand oleDbSelectCommand;
	private System.Data.OleDb.OleDbCommand oleDbUpdateCommand;
	private System.Data.OleDb.OleDbDataAdapter da_SQL_current;
	
	public ndb_bld0121(System.ComponentModel.IContainer container)
	{
		container.Add(this);
		InitializeComponent();
		// 將資料配接器設為 current
		da_SQL = da_SQL_current;
	}

	public ndb_bld0121()
	{
		InitializeComponent();
		// 將資料配接器設為 current
		da_SQL = da_SQL_current;
	}

	#region Component Designer generated code
	
	/// <summary>
	/// 此為設計工具支援所必需的方法 - 請勿使用程式碼編輯器修改
	/// 這個方法的內容。
	/// </summary>
	private void InitializeComponent()
	{
		this.da_SQL_current = new System.Data.OleDb.OleDbDataAdapter();
		this.oleDbDeleteCommand = new System.Data.OleDb.OleDbCommand();
		this.oleDbInsertCommand = new System.Data.OleDb.OleDbCommand();
		this.oleDbSelectCommand = new System.Data.OleDb.OleDbCommand();
		this.oleDbUpdateCommand = new System.Data.OleDb.OleDbCommand();
		
		((System.ComponentModel.ISupportInitialize)(this.ds_Data)).BeginInit();
		((System.ComponentModel.ISupportInitialize)(this.dv_View)).BeginInit();

		// 
		// 容器
		// 
		this.da_SQL_current.TableMappings.AddRange(new System.Data.Common.DataTableMapping[] {
			
                                           new System.Data.Common.DataTableMapping("Table", "bld0121", new System.Data.Common.DataColumnMapping[] {
                                           new System.Data.Common.DataColumnMapping("ld0121_md012no", "ld0121_md012no"),
                                           new System.Data.Common.DataColumnMapping("ld0121_seq", "ld0121_seq"),
                                           new System.Data.Common.DataColumnMapping("ld0121_cg0211code", "ld0121_cg0211code"),
                                           new System.Data.Common.DataColumnMapping("ld0121_cf041code", "ld0121_cf041code"),
                                           new System.Data.Common.DataColumnMapping("ld0121_amt", "ld0121_amt"),
                                           new System.Data.Common.DataColumnMapping("ld0121_applied_amt", "ld0121_applied_amt"),
                                           new System.Data.Common.DataColumnMapping("ld0121_prepayl", "ld0121_prepayl"),
                                           new System.Data.Common.DataColumnMapping("ld0121_reason", "ld0121_reason"),
                                           new System.Data.Common.DataColumnMapping("ld0121_pname", "ld0121_pname"),
                                           new System.Data.Common.DataColumnMapping("ld0121_pno", "ld0121_pno"),
                                           new System.Data.Common.DataColumnMapping("ld0121_punit", "ld0121_punit"),
                                           new System.Data.Common.DataColumnMapping("ld0121_ppicurl", "ld0121_ppicurl"),
                                           new System.Data.Common.DataColumnMapping("ld0121_received", "ld0121_received"),
                                           new System.Data.Common.DataColumnMapping("ld0121_receive_left", "ld0121_receive_left"),
                                           new System.Data.Common.DataColumnMapping("ld0121_applied_received", "ld0121_applied_received"),
                                           new System.Data.Common.DataColumnMapping("ld0121_isloaded", "ld0121_isloaded"),
                                           new System.Data.Common.DataColumnMapping("ld0121_date", "ld0121_date")
                                           })
            });
                                           
		// 
		// 刪除命令
		// 
		this.da_SQL_current.DeleteCommand = this.oleDbDeleteCommand;
		this.oleDbDeleteCommand.CommandText = "DELETE FROM [bld0121] WHERE (([ld0121_md012no] = ?))  AND (([ld0121_seq] = ?)) ";
		this.oleDbDeleteCommand.Connection = this.cn_DB;
		this.oleDbDeleteCommand.Parameters.AddRange(new System.Data.OleDb.OleDbParameter[] {
		                                                           new System.Data.OleDb.OleDbParameter("Original_ld0121_md012no", System.Data.OleDb.OleDbType.Char, 0, System.Data.ParameterDirection.Input, false, ((byte)(14)), ((byte)(0)), "ld0121_md012no", System.Data.DataRowVersion.Original, null),
                                                     new System.Data.OleDb.OleDbParameter("Original_ld0121_seq", System.Data.OleDb.OleDbType.SmallInt, 0, System.Data.ParameterDirection.Input, false, ((byte)(5)), ((byte)(0)), "ld0121_seq", System.Data.DataRowVersion.Original, null)

		});


		// 
		// 新增區
		// 
		this.da_SQL_current.InsertCommand = this.oleDbInsertCommand;
		this.oleDbInsertCommand.CommandText = "INSERT INTO [bld0121] ([ld0121_md012no],[ld0121_seq],[ld0121_cg0211code],[ld0121_cf041code],[ld0121_amt],[ld0121_applied_amt],[ld0121_prepayl],[ld0121_reason],[ld0121_pname],[ld0121_pno],[ld0121_punit],[ld0121_ppicurl],[ld0121_received],[ld0121_receive_left],[ld0121_applied_received],[ld0121_isloaded],[ld0121_date]) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
		this.oleDbInsertCommand.Connection = this.cn_DB;
		this.oleDbInsertCommand.Parameters.AddRange(new System.Data.OleDb.OleDbParameter[] {
		                                                           new System.Data.OleDb.OleDbParameter("ld0121_md012no", System.Data.OleDb.OleDbType.Char, 0, "ld0121_md012no"),
                                                     new System.Data.OleDb.OleDbParameter("ld0121_seq", System.Data.OleDb.OleDbType.SmallInt, 0, "ld0121_seq"),
                                                     new System.Data.OleDb.OleDbParameter("ld0121_cg0211code", System.Data.OleDb.OleDbType.Char, 0, "ld0121_cg0211code"),
                                                     new System.Data.OleDb.OleDbParameter("ld0121_cf041code", System.Data.OleDb.OleDbType.Char, 0, "ld0121_cf041code"),
                                                     new System.Data.OleDb.OleDbParameter("ld0121_amt", System.Data.OleDb.OleDbType.Char, 0, "ld0121_amt"),
                                                     new System.Data.OleDb.OleDbParameter("ld0121_applied_amt", System.Data.OleDb.OleDbType.Numeric, 0, "ld0121_applied_amt"),
                                                     new System.Data.OleDb.OleDbParameter("ld0121_prepayl", System.Data.OleDb.OleDbType.Numeric, 0, "ld0121_prepayl"),
                                                     new System.Data.OleDb.OleDbParameter("ld0121_reason", System.Data.OleDb.OleDbType.VarChar, 0, "ld0121_reason"),
                                                     new System.Data.OleDb.OleDbParameter("ld0121_pname", System.Data.OleDb.OleDbType.VarChar, 0, "ld0121_pname"),
                                                     new System.Data.OleDb.OleDbParameter("ld0121_pno", System.Data.OleDb.OleDbType.Numeric, 0, "ld0121_pno"),
                                                     new System.Data.OleDb.OleDbParameter("ld0121_punit", System.Data.OleDb.OleDbType.VarChar, 0, "ld0121_punit"),
                                                     new System.Data.OleDb.OleDbParameter("ld0121_ppicurl", System.Data.OleDb.OleDbType.VarChar, 0, "ld0121_ppicurl"),
                                                     new System.Data.OleDb.OleDbParameter("ld0121_received", System.Data.OleDb.OleDbType.Numeric, 0, "ld0121_received"),
                                                     new System.Data.OleDb.OleDbParameter("ld0121_receive_left", System.Data.OleDb.OleDbType.Numeric, 0, "ld0121_receive_left"),
                                                     new System.Data.OleDb.OleDbParameter("ld0121_applied_received", System.Data.OleDb.OleDbType.Numeric, 0, "ld0121_applied_received"),
                                                     new System.Data.OleDb.OleDbParameter("ld0121_isloaded", System.Data.OleDb.OleDbType.Char, 0, "ld0121_isloaded"),
                                                     new System.Data.OleDb.OleDbParameter("ld0121_date", System.Data.OleDb.OleDbType.DBTimeStamp, 0, "ld0121_date")
		});


		// 
		// 查詢區
		// 
		this.da_SQL_current.SelectCommand = this.oleDbSelectCommand;				this.oleDbSelectCommand.CommandText = "SELECT * FROM [bld0121] WHERE (1=1) ";		this.oleDbSelectCommand.Connection = this.cn_DB;

		// 
		// 更新區
		// 
		this.da_SQL_current.UpdateCommand = this.oleDbUpdateCommand;
		this.oleDbUpdateCommand.CommandText = "UPDATE [bld0121] SET  [ld0121_md012no] = ?, [ld0121_seq] = ?, [ld0121_cg0211code] = ?, [ld0121_cf041code] = ?, [ld0121_amt] = ?, [ld0121_applied_amt] = ?, [ld0121_prepayl] = ?, [ld0121_reason] = ?, [ld0121_pname] = ?, [ld0121_pno] = ?, [ld0121_punit] = ?, [ld0121_ppicurl] = ?, [ld0121_received] = ?, [ld0121_receive_left] = ?, [ld0121_applied_received] = ?, [ld0121_isloaded] = ?, [ld0121_date] = ?  WHERE (([ld0121_md012no] = ?)) AND (([ld0121_seq] = ?)) ";
		this.oleDbUpdateCommand.Connection = this.cn_DB;
		this.oleDbUpdateCommand.Parameters.AddRange(new System.Data.OleDb.OleDbParameter[] {
		                                                           new System.Data.OleDb.OleDbParameter("ld0121_md012no", System.Data.OleDb.OleDbType.Char, 0, "ld0121_md012no"),
                                                     new System.Data.OleDb.OleDbParameter("ld0121_seq", System.Data.OleDb.OleDbType.SmallInt, 0, "ld0121_seq"),
                                                     new System.Data.OleDb.OleDbParameter("ld0121_cg0211code", System.Data.OleDb.OleDbType.Char, 0, "ld0121_cg0211code"),
                                                     new System.Data.OleDb.OleDbParameter("ld0121_cf041code", System.Data.OleDb.OleDbType.Char, 0, "ld0121_cf041code"),
                                                     new System.Data.OleDb.OleDbParameter("ld0121_amt", System.Data.OleDb.OleDbType.Char, 0, "ld0121_amt"),
                                                     new System.Data.OleDb.OleDbParameter("ld0121_applied_amt", System.Data.OleDb.OleDbType.Numeric, 0, "ld0121_applied_amt"),
                                                     new System.Data.OleDb.OleDbParameter("ld0121_prepayl", System.Data.OleDb.OleDbType.Numeric, 0, "ld0121_prepayl"),
                                                     new System.Data.OleDb.OleDbParameter("ld0121_reason", System.Data.OleDb.OleDbType.VarChar, 0, "ld0121_reason"),
                                                     new System.Data.OleDb.OleDbParameter("ld0121_pname", System.Data.OleDb.OleDbType.VarChar, 0, "ld0121_pname"),
                                                     new System.Data.OleDb.OleDbParameter("ld0121_pno", System.Data.OleDb.OleDbType.Numeric, 0, "ld0121_pno"),
                                                     new System.Data.OleDb.OleDbParameter("ld0121_punit", System.Data.OleDb.OleDbType.VarChar, 0, "ld0121_punit"),
                                                     new System.Data.OleDb.OleDbParameter("ld0121_ppicurl", System.Data.OleDb.OleDbType.VarChar, 0, "ld0121_ppicurl"),
                                                     new System.Data.OleDb.OleDbParameter("ld0121_received", System.Data.OleDb.OleDbType.Numeric, 0, "ld0121_received"),
                                                     new System.Data.OleDb.OleDbParameter("ld0121_receive_left", System.Data.OleDb.OleDbType.Numeric, 0, "ld0121_receive_left"),
                                                     new System.Data.OleDb.OleDbParameter("ld0121_applied_received", System.Data.OleDb.OleDbType.Numeric, 0, "ld0121_applied_received"),
                                                     new System.Data.OleDb.OleDbParameter("ld0121_isloaded", System.Data.OleDb.OleDbType.Char, 0, "ld0121_isloaded"),
                                                     new System.Data.OleDb.OleDbParameter("ld0121_date", System.Data.OleDb.OleDbType.DBTimeStamp, 0, "ld0121_date"),
                                                     new System.Data.OleDb.OleDbParameter("Original_ld0121_md012no", System.Data.OleDb.OleDbType.Char, 0, System.Data.ParameterDirection.Input, false, ((byte)(14)), ((byte)(0)), "ld0121_md012no", System.Data.DataRowVersion.Original, null),
                                                     new System.Data.OleDb.OleDbParameter("Original_ld0121_seq", System.Data.OleDb.OleDbType.SmallInt, 0, System.Data.ParameterDirection.Input, false, ((byte)(5)), ((byte)(0)), "ld0121_seq", System.Data.DataRowVersion.Original, null)
                                                });

		((System.ComponentModel.ISupportInitialize)(this.ds_Data)).EndInit();
		((System.ComponentModel.ISupportInitialize)(this.dv_View)).EndInit();


	}
	#endregion

	// =========================================================================
	/// <summary>
	/// 函式描述：自訂初始化函式（覆蓋上層）
	/// </summary>
	protected override void uf_InitializeComponent()
	{
		// 先將 DataSet 宣告為指定的結構再初始化
		this.ds_Data = new d_bld0121();
		this.uf_Initialize();
	}
}
