// *********************************************************************************
// 1. 程式描述：hca205資料元件–無傳入值
// 2. 撰寫人員：generated by WITSTER  0.2.2 beta (by QFLin)
// *********************************************************************************
using System;
using System.ComponentModel;
using System.Collections;
using System.Diagnostics;

/// <summary>
/// hca205資料元件–無傳入值
/// </summary>
public class ndb_hca205 : WIT.Template.Project.n_dbbase
{
	private System.Data.OleDb.OleDbCommand oleDbDeleteCommand;
	private System.Data.OleDb.OleDbCommand oleDbInsertCommand;
	private System.Data.OleDb.OleDbCommand oleDbSelectCommand;
	private System.Data.OleDb.OleDbCommand oleDbUpdateCommand;
	private System.Data.OleDb.OleDbDataAdapter da_SQL_current;
	
	public ndb_hca205(System.ComponentModel.IContainer container)
	{
		container.Add(this);
		InitializeComponent();
		// 將資料配接器設為 current
		da_SQL = da_SQL_current;
	}

	public ndb_hca205()
	{
		InitializeComponent();
		// 將資料配接器設為 current
		da_SQL = da_SQL_current;
	}

	#region Component Designer generated code
	
	/// <summary>
	/// 此為設計工具支援所必需的方法 - 請勿使用程式碼編輯器修改
	/// 這個方法的內容。
	/// </summary>
	private void InitializeComponent()
	{
		System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(ndb_hca205));
		this.da_SQL_current = new System.Data.OleDb.OleDbDataAdapter();
		this.oleDbDeleteCommand = new System.Data.OleDb.OleDbCommand();
		this.oleDbInsertCommand = new System.Data.OleDb.OleDbCommand();
		this.oleDbSelectCommand = new System.Data.OleDb.OleDbCommand();
		this.oleDbUpdateCommand = new System.Data.OleDb.OleDbCommand();
		((System.ComponentModel.ISupportInitialize)(this.ds_Data)).BeginInit();
		((System.ComponentModel.ISupportInitialize)(this.dv_View)).BeginInit();
		// 
		// da_SQL_current
		// 
		this.da_SQL_current.DeleteCommand = this.oleDbDeleteCommand;
		this.da_SQL_current.InsertCommand = this.oleDbInsertCommand;
		this.da_SQL_current.SelectCommand = this.oleDbSelectCommand;
		this.da_SQL_current.TableMappings.AddRange(new System.Data.Common.DataTableMapping[] {
            new System.Data.Common.DataTableMapping("Table", "hca205", new System.Data.Common.DataColumnMapping[] {
                        new System.Data.Common.DataColumnMapping("hca205_id", "hca205_id"),
                        new System.Data.Common.DataColumnMapping("hca205_hca212id", "hca205_hca212id"),
                        new System.Data.Common.DataColumnMapping("hca205_name", "hca205_name"),
                        new System.Data.Common.DataColumnMapping("hca205_sort", "hca205_sort"),
                        new System.Data.Common.DataColumnMapping("hca205_stop", "hca205_stop"),
                        new System.Data.Common.DataColumnMapping("hca205_aid", "hca205_aid"),
                        new System.Data.Common.DataColumnMapping("hca205_adt", "hca205_adt"),
                        new System.Data.Common.DataColumnMapping("hca205_uid", "hca205_uid"),
                        new System.Data.Common.DataColumnMapping("hca205_udt", "hca205_udt")})});
		this.da_SQL_current.UpdateCommand = this.oleDbUpdateCommand;
		// 
		// oleDbDeleteCommand
		// 
		this.oleDbDeleteCommand.CommandText = "DELETE FROM [hca205] WHERE (([hca205_id] = ?))";
		this.oleDbDeleteCommand.Connection = this.cn_DB;
		this.oleDbDeleteCommand.Parameters.AddRange(new System.Data.OleDb.OleDbParameter[] {
            new System.Data.OleDb.OleDbParameter("Original_hca205_id", System.Data.OleDb.OleDbType.WChar, 0, System.Data.ParameterDirection.Input, false, ((byte)(0)), ((byte)(0)), "hca205_id", System.Data.DataRowVersion.Original, null)});
		// 
		// oleDbInsertCommand
		// 
		this.oleDbInsertCommand.CommandText = "INSERT INTO [hca205] ([hca205_id], [hca205_hca212id], [hca205_name], [hca205_sort" +
			"], [hca205_stop], [hca205_aid], [hca205_adt], [hca205_uid], [hca205_udt]) VALUES" +
			" (?, ?, ?, ?, ?, ?, ?, ?, ?)";
		this.oleDbInsertCommand.Connection = this.cn_DB;
		this.oleDbInsertCommand.Parameters.AddRange(new System.Data.OleDb.OleDbParameter[] {
            new System.Data.OleDb.OleDbParameter("hca205_id", System.Data.OleDb.OleDbType.WChar, 0, "hca205_id"),
            new System.Data.OleDb.OleDbParameter("hca205_hca212id", System.Data.OleDb.OleDbType.WChar, 0, "hca205_hca212id"),
            new System.Data.OleDb.OleDbParameter("hca205_name", System.Data.OleDb.OleDbType.VarWChar, 0, "hca205_name"),
            new System.Data.OleDb.OleDbParameter("hca205_sort", System.Data.OleDb.OleDbType.SmallInt, 0, "hca205_sort"),
            new System.Data.OleDb.OleDbParameter("hca205_stop", System.Data.OleDb.OleDbType.WChar, 0, "hca205_stop"),
            new System.Data.OleDb.OleDbParameter("hca205_aid", System.Data.OleDb.OleDbType.VarWChar, 0, "hca205_aid"),
            new System.Data.OleDb.OleDbParameter("hca205_adt", System.Data.OleDb.OleDbType.DBTimeStamp, 0, "hca205_adt"),
            new System.Data.OleDb.OleDbParameter("hca205_uid", System.Data.OleDb.OleDbType.VarWChar, 0, "hca205_uid"),
            new System.Data.OleDb.OleDbParameter("hca205_udt", System.Data.OleDb.OleDbType.DBTimeStamp, 0, "hca205_udt")});
		// 
		// oleDbSelectCommand
		// 
		this.oleDbSelectCommand.CommandText = "SELECT * FROM [hca205] WHERE (1=1) ";
		this.oleDbSelectCommand.Connection = this.cn_DB;
		// 
		// oleDbUpdateCommand
		// 
		this.oleDbUpdateCommand.CommandText = "UPDATE [hca205] SET [hca205_id] = ?, [hca205_hca212id] = ?, [hca205_name] = ?, [hca205_sort] = ?, [hca205_stop] = ?, [hca205_aid] = ?, [hca205_adt] = ?, [hca205_uid] = ?, [hca205_udt] = ? WHERE (([hca205_id] = ?))";
		this.oleDbUpdateCommand.Connection = this.cn_DB;
		this.oleDbUpdateCommand.Parameters.AddRange(new System.Data.OleDb.OleDbParameter[] {
            new System.Data.OleDb.OleDbParameter("hca205_id", System.Data.OleDb.OleDbType.WChar, 0, "hca205_id"),
            new System.Data.OleDb.OleDbParameter("hca205_hca212id", System.Data.OleDb.OleDbType.WChar, 0, "hca205_hca212id"),
            new System.Data.OleDb.OleDbParameter("hca205_name", System.Data.OleDb.OleDbType.VarWChar, 0, "hca205_name"),
            new System.Data.OleDb.OleDbParameter("hca205_sort", System.Data.OleDb.OleDbType.SmallInt, 0, "hca205_sort"),
            new System.Data.OleDb.OleDbParameter("hca205_stop", System.Data.OleDb.OleDbType.WChar, 0, "hca205_stop"),
            new System.Data.OleDb.OleDbParameter("hca205_aid", System.Data.OleDb.OleDbType.VarWChar, 0, "hca205_aid"),
            new System.Data.OleDb.OleDbParameter("hca205_adt", System.Data.OleDb.OleDbType.DBTimeStamp, 0, "hca205_adt"),
            new System.Data.OleDb.OleDbParameter("hca205_uid", System.Data.OleDb.OleDbType.VarWChar, 0, "hca205_uid"),
            new System.Data.OleDb.OleDbParameter("hca205_udt", System.Data.OleDb.OleDbType.DBTimeStamp, 0, "hca205_udt"),
            new System.Data.OleDb.OleDbParameter("Original_hca205_id", System.Data.OleDb.OleDbType.WChar, 0, System.Data.ParameterDirection.Input, false, ((byte)(0)), ((byte)(0)), "hca205_id", System.Data.DataRowVersion.Original, null)});
		((System.ComponentModel.ISupportInitialize)(this.ds_Data)).EndInit();
		((System.ComponentModel.ISupportInitialize)(this.dv_View)).EndInit();

	}
	#endregion

	// =========================================================================
	/// <summary>
	/// 函式描述：自訂初始化函式（覆蓋上層）
	/// </summary>
	protected override void uf_InitializeComponent()
	{
		// 先將 DataSet 宣告為指定的結構再初始化
		this.ds_Data = new d_hca205();
		this.uf_Initialize();
	}
}
