// *********************************************************************************
// 1. 程式描述：hld201資料元件–無傳入值
// 2. 撰寫人員：generated by WITSTER  0.2.2 beta (by QFLin)
// *********************************************************************************
using System;
using System.ComponentModel;
using System.Collections;
using System.Diagnostics;

/// <summary>
/// hld201資料元件–無傳入值
/// </summary>
public class ndb_hld201 : WIT.Template.Project.n_dbbase
{
	private System.Data.OleDb.OleDbCommand oleDbDeleteCommand;
	private System.Data.OleDb.OleDbCommand oleDbInsertCommand;
	private System.Data.OleDb.OleDbCommand oleDbSelectCommand;
	private System.Data.OleDb.OleDbCommand oleDbUpdateCommand;
	private System.Data.OleDb.OleDbDataAdapter da_SQL_current;
	
	public ndb_hld201(System.ComponentModel.IContainer container)
	{
		container.Add(this);
		InitializeComponent();
		// 將資料配接器設為 current
		da_SQL = da_SQL_current;
	}

	public ndb_hld201()
	{
		InitializeComponent();
		// 將資料配接器設為 current
		da_SQL = da_SQL_current;
	}

	#region Component Designer generated code
	
	/// <summary>
	/// 此為設計工具支援所必需的方法 - 請勿使用程式碼編輯器修改
	/// 這個方法的內容。
	/// </summary>
	private void InitializeComponent()
	{
		this.da_SQL_current = new System.Data.OleDb.OleDbDataAdapter();
		this.oleDbDeleteCommand = new System.Data.OleDb.OleDbCommand();
		this.oleDbInsertCommand = new System.Data.OleDb.OleDbCommand();
		this.oleDbSelectCommand = new System.Data.OleDb.OleDbCommand();
		this.oleDbUpdateCommand = new System.Data.OleDb.OleDbCommand();
		
		((System.ComponentModel.ISupportInitialize)(this.ds_Data)).BeginInit();
		((System.ComponentModel.ISupportInitialize)(this.dv_View)).BeginInit();

		// 
		// 容器
		// 
		this.da_SQL_current.TableMappings.AddRange(new System.Data.Common.DataTableMapping[] {
			
                                           new System.Data.Common.DataTableMapping("Table", "hld201", new System.Data.Common.DataColumnMapping[] {
                                           new System.Data.Common.DataColumnMapping("hld201_logid", "hld201_logid"),
                                           new System.Data.Common.DataColumnMapping("hld201_vid", "hld201_vid"),
                                           new System.Data.Common.DataColumnMapping("hld201_logtype", "hld201_logtype"),
                                           new System.Data.Common.DataColumnMapping("hld201_logdate", "hld201_logdate"),
                                           new System.Data.Common.DataColumnMapping("hld201_ps", "hld201_ps"),
                                           new System.Data.Common.DataColumnMapping("hld201_aid", "hld201_aid"),
                                           new System.Data.Common.DataColumnMapping("hld201_adt", "hld201_adt"),
                                           new System.Data.Common.DataColumnMapping("hld201_uid", "hld201_uid"),
                                           new System.Data.Common.DataColumnMapping("hld201_udt", "hld201_udt")
                                           })
            });
                                           
		// 
		// 刪除命令
		// 
		this.da_SQL_current.DeleteCommand = this.oleDbDeleteCommand;
		this.oleDbDeleteCommand.CommandText = "DELETE FROM [hld201] WHERE (([hld201_logid] = ?)) ";
		this.oleDbDeleteCommand.Connection = this.cn_DB;
		this.oleDbDeleteCommand.Parameters.AddRange(new System.Data.OleDb.OleDbParameter[] {
		                                                           new System.Data.OleDb.OleDbParameter("Original_hld201_logid", System.Data.OleDb.OleDbType.Numeric, 0, System.Data.ParameterDirection.Input, false, ((byte)(18)), ((byte)(0)), "hld201_logid", System.Data.DataRowVersion.Original, null)
		});


		// 
		// 新增區
		// 
		this.da_SQL_current.InsertCommand = this.oleDbInsertCommand;
		this.oleDbInsertCommand.CommandText = "INSERT INTO [hld201] ([hld201_vid],[hld201_logtype],[hld201_logdate],[hld201_ps],[hld201_aid],[hld201_adt],[hld201_uid],[hld201_udt]) VALUES (?,?,?,?,?,?,?,?)";
		this.oleDbInsertCommand.Connection = this.cn_DB;
		this.oleDbInsertCommand.Parameters.AddRange(new System.Data.OleDb.OleDbParameter[] {
		                                                           new System.Data.OleDb.OleDbParameter("hld201_vid", System.Data.OleDb.OleDbType.VarChar, 0, "hld201_vid"),
                                                     new System.Data.OleDb.OleDbParameter("hld201_logtype", System.Data.OleDb.OleDbType.Char, 0, "hld201_logtype"),
                                                     new System.Data.OleDb.OleDbParameter("hld201_logdate", System.Data.OleDb.OleDbType.DBTimeStamp, 0, "hld201_logdate"),
                                                     new System.Data.OleDb.OleDbParameter("hld201_ps", System.Data.OleDb.OleDbType.VarChar, 0, "hld201_ps"),
                                                     new System.Data.OleDb.OleDbParameter("hld201_aid", System.Data.OleDb.OleDbType.VarChar, 0, "hld201_aid"),
                                                     new System.Data.OleDb.OleDbParameter("hld201_adt", System.Data.OleDb.OleDbType.DBTimeStamp, 0, "hld201_adt"),
                                                     new System.Data.OleDb.OleDbParameter("hld201_uid", System.Data.OleDb.OleDbType.VarChar, 0, "hld201_uid"),
                                                     new System.Data.OleDb.OleDbParameter("hld201_udt", System.Data.OleDb.OleDbType.DBTimeStamp, 0, "hld201_udt")
		});


		// 
		// 查詢區
		// 
		this.da_SQL_current.SelectCommand = this.oleDbSelectCommand;				this.oleDbSelectCommand.CommandText = "SELECT * FROM [hld201] WHERE (1=1) ";		this.oleDbSelectCommand.Connection = this.cn_DB;

		// 
		// 更新區
		// 
		this.da_SQL_current.UpdateCommand = this.oleDbUpdateCommand;
		this.oleDbUpdateCommand.CommandText = "UPDATE [hld201] SET  [hld201_logid] = ?, [hld201_vid] = ?, [hld201_logtype] = ?, [hld201_logdate] = ?, [hld201_ps] = ?, [hld201_aid] = ?, [hld201_adt] = ?, [hld201_uid] = ?, [hld201_udt] = ?  WHERE (([hld201_logid] = ?))";
		this.oleDbUpdateCommand.Connection = this.cn_DB;
		this.oleDbUpdateCommand.Parameters.AddRange(new System.Data.OleDb.OleDbParameter[] {
		                                                           new System.Data.OleDb.OleDbParameter("hld201_logid", System.Data.OleDb.OleDbType.Numeric, 0, "hld201_logid"),
                                                     new System.Data.OleDb.OleDbParameter("hld201_vid", System.Data.OleDb.OleDbType.VarChar, 0, "hld201_vid"),
                                                     new System.Data.OleDb.OleDbParameter("hld201_logtype", System.Data.OleDb.OleDbType.Char, 0, "hld201_logtype"),
                                                     new System.Data.OleDb.OleDbParameter("hld201_logdate", System.Data.OleDb.OleDbType.DBTimeStamp, 0, "hld201_logdate"),
                                                     new System.Data.OleDb.OleDbParameter("hld201_ps", System.Data.OleDb.OleDbType.VarChar, 0, "hld201_ps"),
                                                     new System.Data.OleDb.OleDbParameter("hld201_aid", System.Data.OleDb.OleDbType.VarChar, 0, "hld201_aid"),
                                                     new System.Data.OleDb.OleDbParameter("hld201_adt", System.Data.OleDb.OleDbType.DBTimeStamp, 0, "hld201_adt"),
                                                     new System.Data.OleDb.OleDbParameter("hld201_uid", System.Data.OleDb.OleDbType.VarChar, 0, "hld201_uid"),
                                                     new System.Data.OleDb.OleDbParameter("hld201_udt", System.Data.OleDb.OleDbType.DBTimeStamp, 0, "hld201_udt"),
                                                     new System.Data.OleDb.OleDbParameter("Original_hld201_logid", System.Data.OleDb.OleDbType.Numeric, 0, System.Data.ParameterDirection.Input, false, ((byte)(18)), ((byte)(0)), "hld201_logid", System.Data.DataRowVersion.Original, null)                                                });

		((System.ComponentModel.ISupportInitialize)(this.ds_Data)).EndInit();
		((System.ComponentModel.ISupportInitialize)(this.dv_View)).EndInit();


	}
	#endregion

	// =========================================================================
	/// <summary>
	/// 函式描述：自訂初始化函式（覆蓋上層）
	/// </summary>
	protected override void uf_InitializeComponent()
	{
		// 先將 DataSet 宣告為指定的結構再初始化
		this.ds_Data = new d_hld201();
		this.uf_Initialize();
	}
}
