// *********************************************************************************
// 1. 程式描述：hmf302資料元件–無傳入值
// 2. 撰寫人員：generated by WITSTER  0.2.2 beta (by QFLin)
// *********************************************************************************
using System;
using System.ComponentModel;
using System.Collections;
using System.Diagnostics;

/// <summary>
/// hmf302資料元件–無傳入值
/// </summary>
public class ndb_hmf302 : WIT.Template.Project.n_dbbase
{
	private System.Data.OleDb.OleDbCommand oleDbDeleteCommand;
	private System.Data.OleDb.OleDbCommand oleDbInsertCommand;
	private System.Data.OleDb.OleDbCommand oleDbSelectCommand;
	private System.Data.OleDb.OleDbCommand oleDbUpdateCommand;
	private System.Data.OleDb.OleDbDataAdapter da_SQL_current;
	
	public ndb_hmf302(System.ComponentModel.IContainer container)
	{
		container.Add(this);
		InitializeComponent();
		// 將資料配接器設為 current
		da_SQL = da_SQL_current;
	}

	public ndb_hmf302()
	{
		InitializeComponent();
		// 將資料配接器設為 current
		da_SQL = da_SQL_current;
	}

	#region Component Designer generated code
	
	/// <summary>
	/// 此為設計工具支援所必需的方法 - 請勿使用程式碼編輯器修改
	/// 這個方法的內容。
	/// </summary>
	private void InitializeComponent()
	{
		this.da_SQL_current = new System.Data.OleDb.OleDbDataAdapter();
		this.oleDbDeleteCommand = new System.Data.OleDb.OleDbCommand();
		this.oleDbInsertCommand = new System.Data.OleDb.OleDbCommand();
		this.oleDbSelectCommand = new System.Data.OleDb.OleDbCommand();
		this.oleDbUpdateCommand = new System.Data.OleDb.OleDbCommand();
		
		((System.ComponentModel.ISupportInitialize)(this.ds_Data)).BeginInit();
		((System.ComponentModel.ISupportInitialize)(this.dv_View)).BeginInit();

		// 
		// 容器
		// 
		this.da_SQL_current.TableMappings.AddRange(new System.Data.Common.DataTableMapping[] {
			
                                           new System.Data.Common.DataTableMapping("Table", "hmf302", new System.Data.Common.DataColumnMapping[] {
                                           new System.Data.Common.DataColumnMapping("hmf302_trainid", "hmf302_trainid"),
                                           new System.Data.Common.DataColumnMapping("hmf302_vid", "hmf302_vid"),
                                           new System.Data.Common.DataColumnMapping("hmf302_score", "hmf302_score"),
                                           new System.Data.Common.DataColumnMapping("hmf302_passed", "hmf302_passed"),
                                           new System.Data.Common.DataColumnMapping("hmf302_ps", "hmf302_ps"),
                                           new System.Data.Common.DataColumnMapping("hmf302_aid", "hmf302_aid"),
                                           new System.Data.Common.DataColumnMapping("hmf302_adt", "hmf302_adt"),
                                           new System.Data.Common.DataColumnMapping("hmf302_uid", "hmf302_uid"),
                                           new System.Data.Common.DataColumnMapping("hmf302_udt", "hmf302_udt")
                                           })
            });
                                           
		// 
		// 刪除命令
		// 
		this.da_SQL_current.DeleteCommand = this.oleDbDeleteCommand;
		this.oleDbDeleteCommand.CommandText = "DELETE FROM [hmf302] WHERE (([hmf302_trainid] = ?))  AND (([hmf302_vid] = ?)) ";
		this.oleDbDeleteCommand.Connection = this.cn_DB;
		this.oleDbDeleteCommand.Parameters.AddRange(new System.Data.OleDb.OleDbParameter[] {
		                                                           new System.Data.OleDb.OleDbParameter("Original_hmf302_trainid", System.Data.OleDb.OleDbType.VarChar, 0, System.Data.ParameterDirection.Input, false, ((byte)(20)), ((byte)(0)), "hmf302_trainid", System.Data.DataRowVersion.Original, null),
                                                     new System.Data.OleDb.OleDbParameter("Original_hmf302_vid", System.Data.OleDb.OleDbType.VarChar, 0, System.Data.ParameterDirection.Input, false, ((byte)(20)), ((byte)(0)), "hmf302_vid", System.Data.DataRowVersion.Original, null)

		});


		// 
		// 新增區
		// 
		this.da_SQL_current.InsertCommand = this.oleDbInsertCommand;
		this.oleDbInsertCommand.CommandText = "INSERT INTO [hmf302] ([hmf302_trainid],[hmf302_vid],[hmf302_score],[hmf302_passed],[hmf302_ps],[hmf302_aid],[hmf302_adt],[hmf302_uid],[hmf302_udt]) VALUES (?,?,?,?,?,?,?,?,?)";
		this.oleDbInsertCommand.Connection = this.cn_DB;
		this.oleDbInsertCommand.Parameters.AddRange(new System.Data.OleDb.OleDbParameter[] {
		                                                           new System.Data.OleDb.OleDbParameter("hmf302_trainid", System.Data.OleDb.OleDbType.VarChar, 0, "hmf302_trainid"),
                                                     new System.Data.OleDb.OleDbParameter("hmf302_vid", System.Data.OleDb.OleDbType.VarChar, 0, "hmf302_vid"),
                                                     new System.Data.OleDb.OleDbParameter("hmf302_score", System.Data.OleDb.OleDbType.SmallInt, 0, "hmf302_score"),
                                                     new System.Data.OleDb.OleDbParameter("hmf302_passed", System.Data.OleDb.OleDbType.Char, 0, "hmf302_passed"),
                                                     new System.Data.OleDb.OleDbParameter("hmf302_ps", System.Data.OleDb.OleDbType.LongVarChar, 0, "hmf302_ps"),
                                                     new System.Data.OleDb.OleDbParameter("hmf302_aid", System.Data.OleDb.OleDbType.VarChar, 0, "hmf302_aid"),
                                                     new System.Data.OleDb.OleDbParameter("hmf302_adt", System.Data.OleDb.OleDbType.DBTimeStamp, 0, "hmf302_adt"),
                                                     new System.Data.OleDb.OleDbParameter("hmf302_uid", System.Data.OleDb.OleDbType.VarChar, 0, "hmf302_uid"),
                                                     new System.Data.OleDb.OleDbParameter("hmf302_udt", System.Data.OleDb.OleDbType.DBTimeStamp, 0, "hmf302_udt")
		});


		// 
		// 查詢區
		// 
		this.da_SQL_current.SelectCommand = this.oleDbSelectCommand;				this.oleDbSelectCommand.CommandText = "SELECT * FROM [hmf302] WHERE (1=1) ";		this.oleDbSelectCommand.Connection = this.cn_DB;

		// 
		// 更新區
		// 
		this.da_SQL_current.UpdateCommand = this.oleDbUpdateCommand;
		this.oleDbUpdateCommand.CommandText = "UPDATE [hmf302] SET  [hmf302_trainid] = ?, [hmf302_vid] = ?, [hmf302_score] = ?, [hmf302_passed] = ?, [hmf302_ps] = ?, [hmf302_aid] = ?, [hmf302_adt] = ?, [hmf302_uid] = ?, [hmf302_udt] = ?  WHERE (([hmf302_trainid] = ?)) AND (([hmf302_vid] = ?)) ";
		this.oleDbUpdateCommand.Connection = this.cn_DB;
		this.oleDbUpdateCommand.Parameters.AddRange(new System.Data.OleDb.OleDbParameter[] {
		                                                           new System.Data.OleDb.OleDbParameter("hmf302_trainid", System.Data.OleDb.OleDbType.VarChar, 0, "hmf302_trainid"),
                                                     new System.Data.OleDb.OleDbParameter("hmf302_vid", System.Data.OleDb.OleDbType.VarChar, 0, "hmf302_vid"),
                                                     new System.Data.OleDb.OleDbParameter("hmf302_score", System.Data.OleDb.OleDbType.SmallInt, 0, "hmf302_score"),
                                                     new System.Data.OleDb.OleDbParameter("hmf302_passed", System.Data.OleDb.OleDbType.Char, 0, "hmf302_passed"),
                                                     new System.Data.OleDb.OleDbParameter("hmf302_ps", System.Data.OleDb.OleDbType.LongVarChar, 0, "hmf302_ps"),
                                                     new System.Data.OleDb.OleDbParameter("hmf302_aid", System.Data.OleDb.OleDbType.VarChar, 0, "hmf302_aid"),
                                                     new System.Data.OleDb.OleDbParameter("hmf302_adt", System.Data.OleDb.OleDbType.DBTimeStamp, 0, "hmf302_adt"),
                                                     new System.Data.OleDb.OleDbParameter("hmf302_uid", System.Data.OleDb.OleDbType.VarChar, 0, "hmf302_uid"),
                                                     new System.Data.OleDb.OleDbParameter("hmf302_udt", System.Data.OleDb.OleDbType.DBTimeStamp, 0, "hmf302_udt"),
                                                     new System.Data.OleDb.OleDbParameter("Original_hmf302_trainid", System.Data.OleDb.OleDbType.VarChar, 0, System.Data.ParameterDirection.Input, false, ((byte)(20)), ((byte)(0)), "hmf302_trainid", System.Data.DataRowVersion.Original, null),
                                                     new System.Data.OleDb.OleDbParameter("Original_hmf302_vid", System.Data.OleDb.OleDbType.VarChar, 0, System.Data.ParameterDirection.Input, false, ((byte)(20)), ((byte)(0)), "hmf302_vid", System.Data.DataRowVersion.Original, null)
                                                });

		((System.ComponentModel.ISupportInitialize)(this.ds_Data)).EndInit();
		((System.ComponentModel.ISupportInitialize)(this.dv_View)).EndInit();


	}
	#endregion

	// =========================================================================
	/// <summary>
	/// 函式描述：自訂初始化函式（覆蓋上層）
	/// </summary>
	protected override void uf_InitializeComponent()
	{
		// 先將 DataSet 宣告為指定的結構再初始化
		this.ds_Data = new d_hmf302();
		this.uf_Initialize();
	}
}
