// *********************************************************************************
// 1. 程式描述：hlh102資料元件–無傳入值
// 2. 撰寫人員：generated by WITSTER  0.2.2 beta (by QFLin)
// *********************************************************************************
using System;
using System.ComponentModel;
using System.Collections;
using System.Diagnostics;

/// <summary>
/// hlh102資料元件–無傳入值
/// </summary>
public class ndb_hlh102 : WIT.Template.Project.n_dbbase
{
	private System.Data.OleDb.OleDbCommand oleDbDeleteCommand;
	private System.Data.OleDb.OleDbCommand oleDbInsertCommand;
	private System.Data.OleDb.OleDbCommand oleDbSelectCommand;
	private System.Data.OleDb.OleDbCommand oleDbUpdateCommand;
	private System.Data.OleDb.OleDbDataAdapter da_SQL_current;
	
	public ndb_hlh102(System.ComponentModel.IContainer container)
	{
		container.Add(this);
		InitializeComponent();
		// 將資料配接器設為 current
		da_SQL = da_SQL_current;
	}

	public ndb_hlh102()
	{
		InitializeComponent();
		// 將資料配接器設為 current
		da_SQL = da_SQL_current;
	}

	#region Component Designer generated code
	
	/// <summary>
	/// 此為設計工具支援所必需的方法 - 請勿使用程式碼編輯器修改
	/// 這個方法的內容。
	/// </summary>
	private void InitializeComponent()
	{
        System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(ndb_hlh102));
        this.da_SQL_current = new System.Data.OleDb.OleDbDataAdapter();
        this.oleDbDeleteCommand = new System.Data.OleDb.OleDbCommand();
        this.oleDbInsertCommand = new System.Data.OleDb.OleDbCommand();
        this.oleDbSelectCommand = new System.Data.OleDb.OleDbCommand();
        this.oleDbUpdateCommand = new System.Data.OleDb.OleDbCommand();
        ((System.ComponentModel.ISupportInitialize)(this.ds_Data)).BeginInit();
        ((System.ComponentModel.ISupportInitialize)(this.dv_View)).BeginInit();
        // 
        // da_SQL_current
        // 
        this.da_SQL_current.DeleteCommand = this.oleDbDeleteCommand;
        this.da_SQL_current.InsertCommand = this.oleDbInsertCommand;
        this.da_SQL_current.SelectCommand = this.oleDbSelectCommand;
        this.da_SQL_current.TableMappings.AddRange(new System.Data.Common.DataTableMapping[] {
            new System.Data.Common.DataTableMapping("Table", "hlh102", new System.Data.Common.DataColumnMapping[] {
                        new System.Data.Common.DataColumnMapping("hlh102_MessageID", "hlh102_MessageID"),
                        new System.Data.Common.DataColumnMapping("hlh102_logid", "hlh102_logid"),
                        new System.Data.Common.DataColumnMapping("hlh102_cname", "hlh102_cname"),
                        new System.Data.Common.DataColumnMapping("hlh102_to", "hlh102_to"),
                        new System.Data.Common.DataColumnMapping("hlh102_msgid", "hlh102_msgid"),
                        new System.Data.Common.DataColumnMapping("hlh102_message", "hlh102_message"),
                        new System.Data.Common.DataColumnMapping("hlh102_status", "hlh102_status"),
                        new System.Data.Common.DataColumnMapping("hlh102_aid", "hlh102_aid"),
                        new System.Data.Common.DataColumnMapping("hlh102_adt", "hlh102_adt"),
                        new System.Data.Common.DataColumnMapping("hlh102_uid", "hlh102_uid"),
                        new System.Data.Common.DataColumnMapping("hlh102_udt", "hlh102_udt")})});
        this.da_SQL_current.UpdateCommand = this.oleDbUpdateCommand;
        // 
        // oleDbDeleteCommand
        // 
        this.oleDbDeleteCommand.CommandText = "DELETE FROM [hlh102] WHERE (([hlh102_MessageID] = ?))";
        this.oleDbDeleteCommand.Connection = this.cn_DB;
        this.oleDbDeleteCommand.Parameters.AddRange(new System.Data.OleDb.OleDbParameter[] {
            new System.Data.OleDb.OleDbParameter("Original_hlh102_MessageID", System.Data.OleDb.OleDbType.Integer, 0, System.Data.ParameterDirection.Input, false, ((byte)(0)), ((byte)(0)), "hlh102_MessageID", System.Data.DataRowVersion.Original, null)});
        // 
        // oleDbInsertCommand
        // 
        this.oleDbInsertCommand.CommandText = "INSERT INTO [hlh102] ([hlh102_logid], [hlh102_cname], [hlh102_to], [hlh102_msgid], [hlh102_message], [hlh102_status], [hlh102_aid], [hlh102_adt], [hlh102_uid], [hlh102_udt]) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
        this.oleDbInsertCommand.Connection = this.cn_DB;
        this.oleDbInsertCommand.Parameters.AddRange(new System.Data.OleDb.OleDbParameter[] {
            new System.Data.OleDb.OleDbParameter("hlh102_logid", System.Data.OleDb.OleDbType.VarChar, 0, "hlh102_logid"),
            new System.Data.OleDb.OleDbParameter("hlh102_cname", System.Data.OleDb.OleDbType.VarChar, 0, "hlh102_cname"),
            new System.Data.OleDb.OleDbParameter("hlh102_to", System.Data.OleDb.OleDbType.VarChar, 0, "hlh102_to"),
            new System.Data.OleDb.OleDbParameter("hlh102_msgid", System.Data.OleDb.OleDbType.VarChar, 0, "hlh102_msgid"),
            new System.Data.OleDb.OleDbParameter("hlh102_message", System.Data.OleDb.OleDbType.VarChar, 0, "hlh102_message"),
            new System.Data.OleDb.OleDbParameter("hlh102_status", System.Data.OleDb.OleDbType.VarChar, 0, "hlh102_status"),
            new System.Data.OleDb.OleDbParameter("hlh102_aid", System.Data.OleDb.OleDbType.VarChar, 0, "hlh102_aid"),
            new System.Data.OleDb.OleDbParameter("hlh102_adt", System.Data.OleDb.OleDbType.DBTimeStamp, 0, "hlh102_adt"),
            new System.Data.OleDb.OleDbParameter("hlh102_uid", System.Data.OleDb.OleDbType.VarChar, 0, "hlh102_uid"),
            new System.Data.OleDb.OleDbParameter("hlh102_udt", System.Data.OleDb.OleDbType.DBTimeStamp, 0, "hlh102_udt")});
        // 
        // oleDbSelectCommand
        // 
        this.oleDbSelectCommand.CommandText = "SELECT * FROM [hlh102] WHERE (1=1) ";
        this.oleDbSelectCommand.Connection = this.cn_DB;
        // 
        // oleDbUpdateCommand
        // 
        this.oleDbUpdateCommand.CommandText = "UPDATE [hlh102] SET [hlh102_logid] = ?, [hlh102_cname] = ?, [hlh102_to] = ?, [hlh102_msgid] = ?, [hlh102_message] = ?, [hlh102_status] = ?, [hlh102_aid] = ?, [hlh102_adt] = ?, [hlh102_uid] = ?, [hlh102_udt] = ? WHERE (([hlh102_MessageID] = ?))";
        this.oleDbUpdateCommand.Connection = this.cn_DB;
        this.oleDbUpdateCommand.Parameters.AddRange(new System.Data.OleDb.OleDbParameter[] {
            new System.Data.OleDb.OleDbParameter("hlh102_logid", System.Data.OleDb.OleDbType.VarChar, 0, "hlh102_logid"),
            new System.Data.OleDb.OleDbParameter("hlh102_cname", System.Data.OleDb.OleDbType.VarChar, 0, "hlh102_cname"),
            new System.Data.OleDb.OleDbParameter("hlh102_to", System.Data.OleDb.OleDbType.VarChar, 0, "hlh102_to"),
            new System.Data.OleDb.OleDbParameter("hlh102_msgid", System.Data.OleDb.OleDbType.VarChar, 0, "hlh102_msgid"),
            new System.Data.OleDb.OleDbParameter("hlh102_message", System.Data.OleDb.OleDbType.VarChar, 0, "hlh102_message"),
            new System.Data.OleDb.OleDbParameter("hlh102_status", System.Data.OleDb.OleDbType.VarChar, 0, "hlh102_status"),
            new System.Data.OleDb.OleDbParameter("hlh102_aid", System.Data.OleDb.OleDbType.VarChar, 0, "hlh102_aid"),
            new System.Data.OleDb.OleDbParameter("hlh102_adt", System.Data.OleDb.OleDbType.DBTimeStamp, 0, "hlh102_adt"),
            new System.Data.OleDb.OleDbParameter("hlh102_uid", System.Data.OleDb.OleDbType.VarChar, 0, "hlh102_uid"),
            new System.Data.OleDb.OleDbParameter("hlh102_udt", System.Data.OleDb.OleDbType.DBTimeStamp, 0, "hlh102_udt"),
            new System.Data.OleDb.OleDbParameter("Original_hlh102_MessageID", System.Data.OleDb.OleDbType.Integer, 0, System.Data.ParameterDirection.Input, false, ((byte)(0)), ((byte)(0)), "hlh102_MessageID", System.Data.DataRowVersion.Original, null)});
        ((System.ComponentModel.ISupportInitialize)(this.ds_Data)).EndInit();
        ((System.ComponentModel.ISupportInitialize)(this.dv_View)).EndInit();

	}
	#endregion

	// =========================================================================
	/// <summary>
	/// 函式描述：自訂初始化函式（覆蓋上層）
	/// </summary>
	protected override void uf_InitializeComponent()
	{
		// 先將 DataSet 宣告為指定的結構再初始化
		this.ds_Data = new d_hlh102();
		this.uf_Initialize();
	}
}
