// *********************************************************************************
// 1. 程式描述：
// 2. 撰寫人員：Generated by WITSETER (by QFLin)
// *********************************************************************************
using System;
using System.Data;
using System.Configuration;
using System.Collections;
using System.Web;
using System.Web.Security;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Web.UI.WebControls.WebParts;
using System.Web.UI.HtmlControls;
using WIT.Template.Project;
using System.Data.OleDb;

public partial class sys_d_d02_p_d0201_02 : p_hrBase
{
    #region ☆ Declare Variables -------------------------------------- 撰寫人員：WITSETER (by QFLin)

    /// <summary>變數描述：人員類別資料元件</summary>
    protected ndb_hmd201 indb_hmd201 = new ndb_hmd201();
	protected ndb_hmc101_102 indb_hmc101_102 = new ndb_hmc101_102();
	protected ndb_hld201 indb_hld201 = new ndb_hld201();
    private SIMCrypto io_Crypto = new SIMCrypto();
    #endregion

    // =========================================================================
    /// <summary>
    /// 事件描述：網頁開啟
    /// </summary>
    protected void Page_Load(object sender, EventArgs e)
    {

        // 初始化
        this.uf_InitializeQuery(null, this.indb_hmd201, null);
        this.uf_InitializeComponent(dwF, null, this.indb_hmd201, u_Edit_F);
        this.dgG_Sort = string.Join(",", this.dgG_PrimaryKey);
        this.IsQuery_SessionRemove = false;

        // 註冊執行事件
        this.ue_DataInsert_PreEndEdit += new DataHandler(this.u_Edit_F_PreEndEdit);
        this.ue_DataUpdate_PreEndEdit += new DataHandler(this.u_Edit_F_PreEndEdit);
        this.ue_DataInsert_AfterSave += new DataHandler(this.u_Edit_F_AfterSave);
        this.ue_DataUpdate_AfterSave += new DataHandler(this.u_Edit_F_AfterSave);
        this.ue_DataDelete_AfterSave += new DataHandler(this.u_Edit_F_AfterSave);

        // 如果是第一次執行此網頁
        if (!this.IsPostBack)
        {
            // 接收傳入值
            if (this.Request["args"] != null)
                this.StoredKey = this.Request["args"].Trim();

            this.Session["md201vid"] = this.StoredKey;

            // 將頁面切換到此頁
            this.uf_AddJavaScript("uf_SelectFrame(2);");
			u_Edit_F.UseButton = "IUC";
        }

        this.indb_hmd201.dv_View.Table.Columns["hmd201_creatway"].DefaultValue = "人工登錄";

        this.dwF_hmd201_pwd.Attributes.Add("value", "");


        // 將主鍵值記錄為尋找資料的條件
        this.dgG_FindValue = new object[1];
        this.dgG_FindValue[0] = this.StoredKey;
    }

    // =========================================================================
    /// <summary>
    /// 事件描述：按下 bt_Upload 《上傳照片》按鈕所做的處理
    /// </summary>
    protected void bt_GotoUploadPic_Click(object sender, EventArgs e)
    {
        // 將頁面切換到此頁
        this.uf_AddJavaScript("uf_LinkFrame('p_d0201_03.aspx', '03Frame', '" + this.StoredKey + "'); uf_SelectFrame(3);");
    }

    // =========================================================================
    /// <summary>
    /// 事件描述：當可服勤時數Checkbox群的值有改變的時候
    /// </summary>
    protected void rcWorkDay(object sender, EventArgs e)
    {
        string magicword = "";
        magicword = magicword + (dwF_CB_A.Checked == true ? "A" : "");
        magicword = magicword + (dwF_CB_B.Checked == true ? "B" : "");
        magicword = magicword + (dwF_CB_C.Checked == true ? "C" : "");
        magicword = magicword + (dwF_CB_D.Checked == true ? "D" : "");
        magicword = magicword + (dwF_CB_E.Checked == true ? "E" : "");
        magicword = magicword + (dwF_CB_F.Checked == true ? "F" : "");
        magicword = magicword + (dwF_CB_G.Checked == true ? "G" : "");
        magicword = magicword + (dwF_CB_H.Checked == true ? "H" : "");
        magicword = magicword + (dwF_CB_I.Checked == true ? "I" : "");
        magicword = magicword + (dwF_CB_J.Checked == true ? "J" : "");
        magicword = magicword + (dwF_CB_K.Checked == true ? "K" : "");
        magicword = magicword + (dwF_CB_L.Checked == true ? "L" : "");
        magicword = magicword + (dwF_CB_M.Checked == true ? "M" : "");
        magicword = magicword + (dwF_CB_N.Checked == true ? "N" : "");
        dwF_hmd201_workday.Text = magicword;
    }

    // =========================================================================
    /// <summary>
    /// 事件描述：change data from hmd201_workday into checkbox 
    /// </summary>
    private void makeWorkDay(string magicword)
    {
        magicword = dwF_hmd201_workday.Text;

        dwF_CB_A.Checked = (magicword.IndexOf("A") > -1) ? true : false;
        dwF_CB_B.Checked = (magicword.IndexOf("B") > -1) ? true : false;
        dwF_CB_C.Checked = (magicword.IndexOf("C") > -1) ? true : false;
        dwF_CB_D.Checked = (magicword.IndexOf("D") > -1) ? true : false;
        dwF_CB_E.Checked = (magicword.IndexOf("E") > -1) ? true : false;
        dwF_CB_F.Checked = (magicword.IndexOf("F") > -1) ? true : false;
        dwF_CB_G.Checked = (magicword.IndexOf("G") > -1) ? true : false;
        dwF_CB_H.Checked = (magicword.IndexOf("H") > -1) ? true : false;
        dwF_CB_I.Checked = (magicword.IndexOf("I") > -1) ? true : false;
        dwF_CB_J.Checked = (magicword.IndexOf("J") > -1) ? true : false;
        dwF_CB_K.Checked = (magicword.IndexOf("K") > -1) ? true : false;
        dwF_CB_L.Checked = (magicword.IndexOf("L") > -1) ? true : false;
        dwF_CB_M.Checked = (magicword.IndexOf("M") > -1) ? true : false;
        dwF_CB_N.Checked = (magicword.IndexOf("N") > -1) ? true : false;
    }

    // =========================================================================
    /// <summary>
    /// 事件描述：按下 u_Edit_F 按鈕資料結束編輯之前所做的處理（新增）
    /// </summary>
    private bool u_Edit_F_PreEndEdit(Control adwF, n_dbbase andb_Data, DataRow adr_Row, DataRowView adrv_Row)
    {
        if (adrv_Row == null) return true;

        int li_count = 0;

        // 如果資料為新增的
		if (adrv_Row.IsNew)
		{
			DbMethods.uf_ExecSQL("Select Count(*) From hmd201 Where hmd201_ssn = '" + dwF_hmd201_SSN.Text.Trim() + "'", ref li_count);

			if (li_count > 0)
			{
				uf_Msg("此志工身分證已存在，請確認資料是否有誤！");
				return false;
			}

			DbMethods.uf_ExecSQL("Select Count(*) From hmd201 Where hmd201_account = '" + dwF_hmd201_account.Text.Trim() + "'", ref li_count);

			if (li_count > 0)
			{
				uf_Msg("此志工網帳號已存在，請確認資料是否有誤！");
				return false;
			}

			string NY = "0000000000000000" + Convert.ToString((DateTime.Now.Year - 1911));
			NY = NY.Substring(NY.Length - 3, 3);

			string NM = "0000000000000000" + Convert.ToString((DateTime.Now.Month));
			NM = NM.Substring(NM.Length - 2, 2);

			string ND = "0000000000000000" + Convert.ToString((DateTime.Now.Day));
			ND = ND.Substring(ND.Length - 2, 2);

			// 取得流水號的系統編號–資料庫最大值+1
			adrv_Row["hmd201_vid"] = d02Project.uf_Get_SystemNo("hmd201.hmd201_vid", "V" + NY + "-");
			dwF_hmd201_vid.Text = adrv_Row["hmd201_vid"].ToString();

			adrv_Row["hmd201_id"] = c01Project.uf_Get_SystemNo("hmc101.hmc101_id", "");
			dwF_hmd201_id.Text = adrv_Row["hmd201_id"].ToString();
			// 新增志工時也同時新增分類管理為志工的資料 by rong 2009/09/08
			indb_hmc101_102.uf_Retrieve(" AND hmc101_id = '" + dwF_hmd201_id.Text.Trim() + "' AND hmc102_id = 2");
			if (indb_hmc101_102.uf_RowCount() == 0)
			{
				DataRowView ldrv_Row2;
				this.indb_hmc101_102.uf_InsertRow(out ldrv_Row2);

				ldrv_Row2["hmc101_id"] = dwF_hmd201_id.Text.Trim();
				ldrv_Row2["hmc102_id"] = 2;
				ldrv_Row2["hmc101_102_uid"] = LoginUser.ID;
				ldrv_Row2["hmc101_102_udt"] = DbMethods.uf_GetDateTime();

				ldrv_Row2.EndEdit();
			}
		}
		else
		{
			if (adrv_Row.Row["hmd201_account", DataRowVersion.Original].ToString().Trim() != adrv_Row["hmd201_account"].ToString().Trim())
			{
				DbMethods.uf_ExecSQL("Select Count(*) From hmd201 Where hmd201_account = '" + dwF_hmd201_account.Text.Trim() + "'", ref li_count);

				if (li_count > 0)
				{
					uf_Msg("此志工網帳號已存在，請確認資料是否有誤！");
					return false;
				}
			}

			if (adrv_Row.Row["hmd201_ssn", DataRowVersion.Original].ToString().Trim() != adrv_Row["hmd201_ssn"].ToString().Trim())
			{
				DbMethods.uf_ExecSQL("Select Count(*) From hmd201 Where hmd201_ssn = '" + dwF_hmd201_SSN.Text.Trim() + "'", ref li_count);

				if (li_count > 0)
				{
					uf_Msg("此志工身分證已存在，請確認資料是否有誤！");
					return false;
				}
			}			
		}
        adrv_Row["hmd201_enCodeID"] = this.io_Crypto.uf_Encrypt(dwF_hmd201_vid.Text.Replace("V","").Replace("-",""));

       

        return true;
    }

	// =========================================================================
	/// <summary>
	/// 覆寫新增的內容
	/// </summary>
	protected override bool uf_Data_Insert(Control adwF, DataGrid adgG, WIT.Template.Project.n_dbbase andb_Data, params WIT.Template.Project.n_dbbase[] andba_Save)
	{
		return base.uf_Data_Insert(adwF, adgG, andb_Data, indb_hmc101_102, indb_hld201);
	}

	// =========================================================================
	/// <summary>
	/// 覆寫修改的內容
	/// </summary>
	protected override bool uf_Data_Update(Control adwF, DataGrid adgG, WIT.Template.Project.n_dbbase andb_Data, params WIT.Template.Project.n_dbbase[] andba_Save)
	{
		return base.uf_Data_Update(adwF, adgG, andb_Data, indb_hld201);
	}


    // =========================================================================
    /// <summary>
    /// 事件描述：按下 u_Edit_F 按鈕資料儲存之後所做的處理（新增、修改、刪除）
    /// </summary>
    private bool u_Edit_F_AfterSave(Control adwF, n_dbbase andb_Data, DataRow adr_Row, DataRowView adrv_Row)
    {
        // 重新取出查詢及清單資料
        this.uf_AddJavaScript("parent.frames[1].__doPostBack('',''); uf_SelectFrame(1);");
        return true;
    }

    #region ☆ Override Methods --------------------------------------- 撰寫人員：fen

    // =========================================================================
    /// <summary>
    /// 函式描述：資料控制項容器做相關處理之後針對特殊或不能處理的子控制項做相關處理（覆蓋上層）
    /// </summary>
    /// <param name="acto_Child">資料控制項容器上的子控制項</param>
    /// <param name="as_Value">子控制項對應欄位的值(如為取出則沒去空白)</param>
    /// <param name="a_Action">處理種類–新增(New)；取出(Get)；放入(Set)；繫結(Bind)</param>
    /// <param name="adrv_Row">當筆資料列</param>
    /// <returns>成功(true)；失敗(false)</returns>
    protected override bool uf_DwF_DataAfter(Control acto_Child, ref string as_Value, DwActions a_Action, DataRowView adrv_Row)
    {
        if (a_Action == DwActions.New)
        {
            if (acto_Child == dwF_hmd201_passed)
            {
                dwF_hmd201_passed.Checked = this.uf_Dg_BindBool("Y", as_Value);
                return true;
            }
            if (acto_Child == dwF_hmd201_rejectepaper)
            {
                dwF_hmd201_rejectepaper.Checked = this.uf_Dg_BindBool("Y", as_Value);
                return true;
            }
			if (acto_Child == dwF_hmd201_addid_h)
			{
				dwF_hmd201_addid_b.DataTextField = "";
				Dbcfg.uf_Bind(dwF_hmd201_addid_b, "hca205", "", " AND (1 = 2)", false);
			}

        }
        else if (a_Action == DwActions.Get)
        {

            makeWorkDay("");
            if (acto_Child == dwF_hmd201_passed)
            {
                dwF_hmd201_passed.Checked = this.uf_Dg_BindBool("Y", as_Value);
                return true;
            }
            if (acto_Child == dwF_hmd201_rejectepaper)
            {
                dwF_hmd201_rejectepaper.Checked = this.uf_Dg_BindBool("Y", as_Value);

                return true;
            }
            if (acto_Child == dwF_hmd201_pwd)
            {
                dwF_hmd201_pwd.Text = as_Value;
                ViewState["hmd201_pwd"] = as_Value.Trim();
                this.dwF_hmd201_pwd.Attributes.Add("value", as_Value.Trim());
                return true;
            }
			if (acto_Child == dwF_hmd201_addid_b)
			{
				dwF_hmd201_addid_OnTextChanged(null, EventArgs.Empty);
			}

			if (acto_Child == dwF_hmd201_udt)
			{
				uf_show_hld201_data();
			}

			if (acto_Child == dwF_hmd201_status)
			{
				dwF_hmd201_status.SelectedValue = as_Value.Trim();
			}

        }
        else if (a_Action == DwActions.Set)
        {
            if (acto_Child == dwF_hmd201_passed)
            {
                as_Value = this.uf_Dg_BindBool("Y,N", dwF_hmd201_passed.Checked);

                return true;
            }
            if (acto_Child == dwF_hmd201_rejectepaper)
            {
                as_Value = this.uf_Dg_BindBool("Y,N", dwF_hmd201_rejectepaper.Checked);

                return true;
            }
            if (acto_Child == dwF_hmd201_pwd)
            {
                //ViewState["hmd201_pwd"] = dwF_hmd201_pwd.Text;
                return true;
            }

        }
        else if (a_Action == DwActions.Bind)
        {
            makeWorkDay("");
        }

		if (acto_Child == dwF_hmd201_SSN)
		{
			if (dwF_hmd201_ssntype.SelectedIndex == 0)
			{
				dwF_hmd201_SSN.Attributes["onBlur"] = "uf_Check_Id(this);";
			}
			else
			{
				dwF_hmd201_SSN.Attributes["onBlur"] = "";
			}
		}

		if (acto_Child == dwF_hmd201_account)
		{
			if (as_Value != "")
				dwF_hmd201_account.Enabled = false;
			else
				dwF_hmd201_account.Enabled = true;
		}
        return true;
    }

    #endregion

    protected void dwF_report2_Click(object sender, EventArgs e)
    {
        string ls_vid = "";
        if (dwF_hmd201_vid.Text.Trim() == "")
        {
            this.uf_Msg("請選擇志工！");
            return;
        }

        ls_vid = dwF_hmd201_vid.Text.Trim();

        this.uf_AddJavaScript("uf_OpenWindow('" + this.Request.ApplicationPath + "/proj_uctrl/p_render.aspx?path=" + "/NMMST_HR_Report/rs_d0201_1&format=" + "PDF" + "&query=vid=" + ls_vid + "','',1024,768,'no','no');");

    }
    protected void dwF_hmd201_ssntype_SelectedIndexChanged(object sender, EventArgs e)
    {
        if (dwF_hmd201_ssntype.SelectedIndex == 0)
        {
            this.uf_SetFocus(dwF_hmd201_SSN);
            dwF_hmd201_SSN.Attributes["onBlur"] = "uf_Check_Id(" + dwF_hmd201_SSN.ClientID + ");";
        }
        else
        {
            this.uf_SetFocus(dwF_hmd201_SSN);
            dwF_hmd201_SSN.Attributes["onBlur"] = "";
        }

    }

    // =========================================================================
    // 事件
    // =========================================================================
    /// <summary>
    /// 事件描述：Html 送出前所要做的動作
    /// </summary>
    protected void Page_PreRender(object sender, System.EventArgs e)
    {
			this.dwF_hmd201_pwd.Attributes.Add("value", dwF_hmd201_pwd.Text.Trim());
    }

	// add by rong 2009/09/09
	// =========================================================================
	/// <summary>
	/// 事件描述：輸入郵遞區號時
	/// </summary>
	protected void dwF_hmd201_addid_OnTextChanged(object sender, EventArgs e)
	{
		string ls_hca212_id = "";
		if (dwF_hmd201_addid.Text.Trim().Length >= 3)
		{
			int li_count = 0;
			DbMethods.uf_ExecSQL("SELECT count(*) FROM hca205 where hca205_id = Substring('" + dwF_hmd201_addid.Text.Trim() + "',1,3)", ref li_count);
			if (li_count == 0)
			{
				uf_Msg("此郵遞區號不存在！請重新輸入");
				return;
			}
			DbMethods.uf_ExecSQL("SELECT hca205_hca212id FROM hca205 WHERE hca205_id ='" + dwF_hmd201_addid.Text.Trim().Substring(0, 3) + "'", ref ls_hca212_id);
			dwF_hmd201_addid_h.SelectedValue = ls_hca212_id;
			dwF_hmd201_addid_b.DataTextField = "";
			Dbcfg.uf_Bind(dwF_hmd201_addid_b, "hca205", "", " AND hca205_hca212id ='" + ls_hca212_id + "'", false);
			dwF_hmd201_addid_b.SelectedValue = dwF_hmd201_addid.Text.Trim().Substring(0, 3);
			dwF_hmd201_addot.Text = dwF_hmd201_addid_b.SelectedItem.ToString().Trim();
		}
	}


	// =========================================================================
	/// <summary>
	/// 事件描述：下拉縣市時
	/// </summary>
	protected void dwF_hmd201_addid_h_OnSelectedIndexChanged(object sender, EventArgs e)
	{
		dwF_hmd201_addid_b.DataTextField = "";
		Dbcfg.uf_Bind(dwF_hmd201_addid_b, "hca205", "", " AND hca205_hca212id ='" + dwF_hmd201_addid_h.SelectedValue + "'", false);
		dwF_hmd201_addot.Text = dwF_hmd201_addid_b.SelectedItem.ToString().Trim();
	}

	// =========================================================================
	/// <summary>
	/// 事件描述：下拉鄉鎮時
	/// </summary>
	protected void dwF_hmd201_addid_b_OnSelectedIndexChanged(object sender, EventArgs e)
	{
		dwF_hmd201_addid.Text = dwF_hmd201_addid_b.Text;
		dwF_hmd201_addot.Text = dwF_hmd201_addid_b.SelectedItem.ToString().Trim();
	}

	protected void uf_show_hld201_data()
	{
		dwF_hld201_logdate.Text = "";
		dwF_hld201_ps.Text = "";
		DataSet lds_data;
		DbMethods.uf_Retrieve_FromSQL(out lds_data, "SELECT hld201_logdate, hld201_ps FROM hld201 WHERE hld201_vid ='" + this.StoredKey.ToString().Trim() + "' AND hld201_logtype = 'N' AND IsNull(hld201_ps,'') <> '新入隊'  order by hld201_logdate desc");
		if (lds_data.Tables[0].Rows.Count > 0)
		{
			dwF_hld201_logdate.Text = DateMethods.uf_YYYY_To_YYY(lds_data.Tables[0].Rows[0]["hld201_logdate"].ToString(), false);
			dwF_hld201_ps.Text = lds_data.Tables[0].Rows[0]["hld201_ps"].ToString();
		}
	}
}
